### ISSUE TITLE
/sys/firmware/efi/vars is deprecated and gone on some platforms

### ISSUE THREAD

**Issue by ggardet** [dracutdevs/dracut#1001]
**Describe the bug**
`/sys/firmware/efi/vars` is deprecated since a long time and kernel 5.10 dropped it for non-x86 systems, such as aarch64.
`/sys/firmware/efi/efivars` should now be used.
Kernel commit: https://github.com/torvalds/linux/commit/963fabf37f6a94214a823df0a785e653cb8ad6ea

I spotted 2 occurrences:
* https://github.com/dracutdevs/dracut/blob/master/modules.d/95fcoe-uefi/parse-uefifcoe.sh#L31
* https://github.com/dracutdevs/dracut/blob/master/modules.d/99uefi-lib/uefi-lib.sh#L43

**Distribution used**
openSUSE Tumbleweed

**Dracut version**
051

**Init system**
systemd

**To Reproduce**
N/A

**Expected behavior**
dracut should be updated to use the new path layout.

**Additional context**

**Comment by danimo** [comment]
Good catch!
