### ISSUE TITLE
Dracut not installing `cryptsetup` when using the systemd module

### ISSUE THREAD

**Issue by dragetd** [dracutdevs/dracut#1023]
System: Gentoo amd64, Kernel 5.10.7 with dracut-51 and systemd as init (and packages installed for lvm, cryptsetup, dm etc.)

Gentoo recently started offering Distribution-Kernels, which automatically configure and compile the kernel and call initramfs generation scripts, that in my case, call dracut.

By default, the Gentoo package seems configure all the default dracut modules, which are quiet a bit, including the systemd module.

This is why my /etc/dracut.conf.d/99_unneeded.conf contains this, to reduce the size some:
```
omit_dracutmodules+=" bash network network-manager bootchart stratis cifs fcoe fcoe-uefi iscsi nfs nbd qemu qemu-net lunmask resume "
```

This results in the following dracut execution:
```
dracut: Executing: /usr/bin/dracut --force --kernel-image /usr/src/linux-5.10.7/arch/x86/boot/bzImage /usr/src/linux-5.10.7/arch/x86/boot/initrd 5.10.7
dracut: dracut module 'dash' will not be installed, because command '/bin/dash' could not be found!                   
dracut: dracut module 'mksh' will not be installed, because command '/bin/mksh' could not be found!                                                                                                                                         
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!                                                                                                                                              
dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!                                                                                                                                  
dracut: dracut module 'btrfs' will not be installed, because command 'btrfs' could not be found!                                                                                                                                            
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'dmsquash-live-ntfs' will not be installed, because command 'ntfs-3g' could not be found!
dracut: dracut module 'multipath' will not be installed, because command 'multipath' could not be found!
dracut: dracut module 'nvmf' depends on 'bash', which can't be installed
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack
dracut: dracut-squash module requires squashfs-tools
dracut: *** Including module: systemd ***
dracut: *** Including module: systemd-initrd ***
dracut: *** Including module: modsign ***
dracut: *** Including module: i18n ***
dracut: *** Including module: crypt ***
dracut: *** Including module: dm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 60-persistent-storage-dm.rules
dracut: Skipping udev rule: 55-dm.rules
dracut: *** Including module: kernel-modules ***
dracut: *** Including module: kernel-modules-extra ***
dracut: *** Including module: lvm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 56-lvm.rules
dracut: Skipping udev rule: 60-persistent-storage-lvm.rules 
dracut: *** Including module: mdraid ***
dracut: Skipping udev rule: 64-md-raid.rules
dracut: *** Including module: nvdimm ***
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: terminfo ***
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: dracut-systemd ***
dracut: *** Including module: usrmount ***
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including module: shutdown ***
dracut: *** Including modules done ***
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done ***
dracut: *** Generating early-microcode cpio image ***
dracut: *** Constructing GenuineIntel.bin ***
dracut: *** Store current command line parameters ***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Creating image file '/usr/src/linux-5.10.7/arch/x86/boot/initrd' ***
dracut: *** Creating initramfs image file '/usr/src/linux-5.10.7/arch/x86/boot/initrd' done ***
```

My setup is the following: NVMe disk with plain UEF boot partition and one additional partition. The additional partition is encrypted using luks and hosts an LVM which then again hosts root and other things.
Also:
```
"root=UUID=<the UUID of the root disk> rd.auto rd.luks.uuid=<the UUID of the luks disk> rd.lvm.vg=vg0 rd.luks.allow-discards rd.vconsole.keymap=de"
```

When booting the kernel with this initrd, dracut stops the boot (waiting for something?) before failing and dropping to the rescue shell. And once there, I noticed the lack of `cryptsetup`.
Since dracut allows manually adding things with an option, I configured `cryptsetup` to be added explicitly. The system would again hang on boot before dropping into the rescue shell, but I would have `cryptsetup` available. And the moment I decrypted root, the system booted without issues right away.

I was not trying to figure out why cryptsetup was not included. I stumbled over this line:
https://github.com/dracutdevs/dracut/blob/3c8ca29650ff7fc0876f9523e5434e6f15e22ff4/modules.d/90crypt/module-setup.sh#L84

And further debugging showed indeed: Having the `systemd` module enabled causes cryptsetup to be ignored. The docs read like systemd should do some magic at this point, but I really do not know how it shoudl do anything without cryptsetup. Not sure if my systemd config is broken in a ways that makes dracut install it incorrectly into my initrd or if this is a bug!

Disabling the `systemd` module caused the system to ask for the password and boot. But with strange console output and not initsystem output… nut sure why that is. Not sure if I 'need' the systemd module to cleanly boot into a systemd based init.

**Comment by johannbg** [comment]
I have glazed over the module and nothing seems out of the ordinary so double check your kernel command line parameters are correct based on your cryptsetup.  If it's wrong or something is missing everything else will fail regardless if you use systemd or something else.

**Comment by dragetd** [comment]
How is unlocking a lucks device supposed to work without cryptsetup? The next line says 'inst_multiple cryptsetup…' and is not executed if the systemd module is loaded.

I am unpacking the image before even rebooting and checking for if there is any `cryptsetup` binary in there (also no systemd_cryptsetup which I have seen referenced elsewhere, but could not find out what it should be)

Maybe my assumption is wrong that crypt NEEDS `cryptsetup` but might work without it with systemd somehow reimplementing cryptsetup. (which would be totally stupid of systemd, but also not suprising. :P)

**Comment by johannbg** [comment]
Sorry not following systemd uses cryptsetup library ( usr/lib/libcryptsetup.so.12 ) and it's clearly stated in 90crypt what should be included if the systemd module is enable 
 
     if dracut_module_included "systemd"; then
         # the cryptsetup targets are already pulled in by 00systemd, but not
         # the enablement symlinks
         inst_multiple -o \
                       $systemdutildir/system-generators/systemd-cryptsetup-generator \
                       $systemdutildir/systemd-cryptsetup \
                       $systemdsystemunitdir/systemd-ask-password-console.path \
                       $systemdsystemunitdir/systemd-ask-password-console.service \
                       $systemdsystemunitdir/cryptsetup.target \
                       $systemdsystemunitdir/sysinit.target.wants/cryptsetup.target \
                       $systemdsystemunitdir/remote-cryptsetup.target \
                       $systemdsystemunitdir/initrd-root-device.target.wants/remote-cryptsetup.target \
                       systemd-ask-password systemd-tty-ask-password-agent
     fi

So it's the above related systemd files + libcryptsetup.so.12  based what I can read from systemd's code that should  exist in your initrd 

Does your image contain these? If not which files where missing?
If adding those files fails try adding as well  
/usr/bin/cryptsetup ( afaikt systemd is not using it )
/etc/crypttab ( should be optional )

So we can narrow down which files are missing.

**Comment by dragetd** [comment]
As you said, I think the crypttab is optional. My kernel options specify the luks root. Tho, I configured this file as well just to be sure.

I just came back from reading about the systemd-cryptsetup implementation, and that it indeed has its own cryptsetup imeplementation. It would not use any '/sbin/cryptsetup' binary. Oh well.

But this should still mean I should find traces of 'systemd-cryptsetup' in my initramfs.

I just added the 'systemd' module again and rebuild, then inspecting it with `lsinitrd foo.img | grep cryptsetup` and it does not show any of systemd-cryptsetup, cryptsetup.target, systemd-cryptsetup-generator etc. (it lists all files)

From the setup script, the things like `systemd-tty-ask-password-agent` are included, but nothing with 'cryptsetup' in the filename.
My systemd is installed without cryptsetup support and this is the reason why my system lacks those files. The questions remaining for me:
- Should dracut check and realize there is also no systemd-cryptsetup and fail building, giving the user a warning?
- What is the advantage about using systemd in my initramfs? Any disadvantage if I just disable the systemd module for my initramfs?

**Comment by johannbg** [comment]
Obviously you need the 90crypt module if you want to include those files. 
I'm currently reworking and improving ( and splitting ) the systemd implementation in dracut which will hopefully be done before next release ( which should happen in about ca 2 weeks ) at that point you probably dont need the 90crypt module ( but will instead need a specific systemd-cryptsetup module or just enable the systemd module which will include that module by default then you will get your expected behaviour ).

**Comment by dragetd** [comment]
But would you consider the current crypt module ignoring the missing systemd-cryptsetup implementation and silently building a non-working initramfs as a bug?

My setup might be a less common setup as a Gentoo user who can actually install SystemD without 'cryptsetup' support, but when not using SystemD, dracut catches a missing 'cryptsetup' binary. So I would somehow expect it to also tell me if systemd-cryptestup files/libs/services are missing.

But if you think this is not worth keeping an issue about since you want to rework some things anyways, feel free to close this issue. Thank you very much for the input, it works now for me!

**Comment by mmokrejs** [comment]
I hit a similar issue with dracut being unable to find my luks key on any device provided. The `rd.luks.key=/foo/bar.key` should be enough to find it. It does not even try it and just falls back to ask for a password, which is useless in my scenario. The fallback should ask for a file path at some moment too and before that, allow to exit temporarity to a shell so use could mount the device. Then exit back to continue.

I can at least mount the device housing the key, symlink the path to the intended keyfile and run `systemd-cryptsetup` on it:

```
mkdir /tmp/removable; mount /dev/sdaX /tmp/removable
cd /; ln -s /tmp/removable/foo .
systemd-cryptsetup attach luks-$id /dev/md127 /foo/bar.key
exit
```

The systems booted fine. Incidentally, I had to restart sddm and that triggered:

```
 systemctl stop sddm
🔐 Please enter passphrase for disk luks-$id:
Broadcast message from root@foo (Sun 2024-03-24 09:02:28 CET):

Password entry required for 'Please enter passphrase for disk luks-$id:' (PID 3139).
Please enter password with the systemd-tty-ask-password-agent tool.
```

So, still, somewhere in a proper config variable I need to tell systemd-cryptsetup to poke over any attached filesystems and search for /foo/bar.key and my kernel variable `rd.luks.key=/foo/bar.key` states.

Indeed it is funny we have to drop `systemd` from dracut to be able to use old but working cryptsetup. See also https://unix.stackexchange.com/questions/384296/how-to-add-cryptsetup-to-dracut 

BTW, here is my setup:

```
# cat /etc/dracut.conf.d/dracut.conf 
add_dracutmodules+=" crypt-gpg crypt-loop crypt ssh-client bash busybox mdraid rescue "
install_items+=" cryptsetup ssh scp e2fsck fsck.ext2 fsck.ext3 fsck.ext4 fsck.fat fsck.vfat lsscsi gpg-agent fsck.ext4 strace "
# the next line should avoid systemd-cryptsetup altogether
# omit_dracutmodules+=" systemd "
# 
hostonly="yes"
compress="gzip"
add_drivers+=" i915 "
#
```

```
# dracut --version
dracut 060
# 
```
