### ISSUE TITLE
Bonds set up in Dracut are not statusable and do not fail over

### ISSUE THREAD

**Issue by tyeo098** [dracutdevs/dracut#1033]
When a bond is set up in dracut in grub using bond=, the bond no longer appears to status correctly after the OS fully boots.
 
`# cat /proc/net/bonding/bond0
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)
Bonding Mode: load balancing (round-robin)
MII Status: up
[...]
Slave Interface: eth0
MII Status: up
[...]
Slave Interface: eth1
**MII Status: up**
[...]`

However ethtool reports that eth1 is link down:

`# ethtool eth1
Settings for eth1:
        [...]
        Link detected: no
`

This is in RHEL8.2 using dracut-049-70.git20200228.el8.x86_64 and SystemD

To reproduce, create a bond on the kernel cmdline with `bond=bond0:eth0,eth1`, status it, take down a slave with `ip link set dev <slave> down` status it again to reveal the proc subsystem was not updated to reflect the recently downed slave. 
Dracut cpio was build to disable NetworkManager in the initrd, instead using the network-legacy plugin. 

Expected to see when a slave is brought down, the MII Status also reflects that the slave goes down, like when bonds are brought up with NetworkManager in the rootfs. 

This is appears to be related to the stale #641

**Comment by tyeo098** [comment]
We have confirmed that in addition to setting the link down with IP, the same result appears if a cable is unplugged. 
A second bond that was set up outside of dracut (in NM via ifcfg-rh plugin) correctly reports the status if the link is either set down with IP or if the cable is unplugged. 
The MII Status is not updating correctly for bonds configured in Dracut

**Comment by tyeo098** [comment]
It looks like when dracut is bringing up the bonds, its not setting miimon correctly.   
This one set up by dracut:
`# cat /sys/class/net/eth0/bonding/miimon`
`0`
This one set up by NM:
`# cat /sys/class/net/eth2/bonding/miimon`
`100`

Should I push up a PR to add the default miimon=100 option to the `modprobe -q -b bonding` call?

**Comment by johannbg** [comment]
Not specifying the monitor frequency is by design. NM is simply doing it wrong. ( more saner default would be a 1000 )  
What happens when you add "bond=bond0:eth0,eth1:miimon=100" ? ( you might want to add use_carrier=0 if you are on some legacy system as in the line should then be "bond=bond0:eth0,eth1:miimon=100,use_carrier=0" )

**Comment by tyeo098** [comment]
Can I change my PR to add that to the documentation? Not having failover work on the bonds dracut set up (but the NM ones worked) threw us for a loop for a while.

**Comment by johannbg** [comment]
I'm not sure what that documentations would supposed to be I mean this is already documented in 1. and what's supported in the output of 2. all probably well explained in some kind of customer only access RH documentation for RHEL customers ( you are paying for service and support, so use it ). 

There is no point for us trying to duplicate those documents here upstream. It's better that people just read the documentation that already exist and are better documented than something that can reside here. 

1. https://www.kernel.org/doc/html/latest/networking/bonding.html#frequently-asked-questions
2. modinfo bonding
