### ISSUE TITLE
ci: add mkosi 

### ISSUE THREAD

**Issue by johannbg** [dracutdevs/dracut#1070]
* [ ] Add mkosi support to github workflows as a CI. 
     It should atleast perform build test for Arch,Fedora,OpenSuse,Debian on PR
* * [ ] Arch Build Test
* * [ ] Debian Build Test
* * [ ] Fedora Build Test
* * [ ] OpenSuse Build Test

* [ ] Update documentation ( HACKING.md ) on how to use mkosi for testing.

**Comment by haraldh** [comment]
Only `build` or even `boot` test?

**Comment by johannbg** [comment]
@haraldh we can do both actually, even potentially replace the entire test infrastructure with it, but the initial scope should just be getting basic build testing working, then add another scope that extends it further I think.
