### ISSUE TITLE
load kernel module with parameters not working

### ISSUE THREAD

**Issue by natxo** [dracutdevs/dracut#1095]
We have some sfp network adapters that require the ixgbe module with the parameter 'allow_unsupported_sfp=1'.

I am trying to bootstrap the installation of this server in a kickstart script and add this to the kernel cmdline: ixgbe.allow_unsupported_sfp=1 

After a long time dracut fallsback to its shell (is there a way to fail earlier, it takes really long, longer than half an hour), I can verify the module is loaded, but I do not see any parameter in /sys/modules/ixgbe/parameters (the latest dir does not exist). 
I can rmmod ixgbe && modprobe ixgbe allow_unsupported_sfp=1 succesfully ($? is zero), but the network interface does not work after adding ip/mask/gw information. 

This is in rhel 8.3 by the way.

Do I need to add this option to a custom ramdisk instead of the one leveraged by the redhat iso?

**Comment by haraldh** [comment]
Hmm, to my knowledge the kernel applies the parameters from the kernel command line also, if the parameter starts with the module name like `<module_name>.<parameter>`, although it might not appear in `/sys/modules/<module_name>/parameters` .

There is nothing dracut can do here, though.
