### ISSUE TITLE
when I run dracrt --add "anaconda " reports that no anaconda modules install ,how can I fix it ?

### ISSUE THREAD

**Issue by GitSoftwareNow** [dracutdevs/dracut#1116]

**Comment by haraldh** [comment]
dracut does not ship the `anaconda` dracut module. The `anaconda` software [does](https://github.com/rhinstaller/anaconda/tree/master/dracut), though. If you are using Fedora, you need to install the `anaconda-dracut.x86_64` rpm first.

Fixes: #1117

**Comment by GitSoftwareNow** [comment]
The anaconda-dracut rpm is installed aleady ,run dracut --list-modules anaconda in the list

**Comment by haraldh** [comment]
What is the exact output of the `dracut` run?

**Comment by Rtoax** [comment]
I got the error too:

```
$ sudo dracut --xz --no-early-microcode --add fips --add anaconda --force initramfs.img
dracut: dracut module 'coreos-installer' depends on 'clevis', which can't be installed
dracut: dracut module 'anaconda' cannot be found or installed.
```
