### ISSUE TITLE
Failure to run dracut

### ISSUE THREAD

**Issue by GitSoftwareNow** [dracutdevs/dracut#1122]
[root@bogon pxeboot]# dnf reinstall anaconda-dracut -y
Last metadata expiration check: 0:27:51 ago on 2021年02月22日 星期一 10时32分58秒.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                        Architecture                                  Version                                                      Repository                                         Size
===================================================================================================================================================================================================================
Reinstalling:
 anaconda                                       aarch64                                       29.24.7-28.16.p07.ky10                                       ks10-adv-os                                       428 k

Transaction Summary
===================================================================================================================================================================================================================

Total download size: 428 k
Installed size: 1.8 M
Downloading Packages:
anaconda-29.24.7-28.16.p07.ky10.aarch64.rpm                                                                                                                                        2.9 MB/s | 428 kB     00:00    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                              2.9 MB/s | 428 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Reinstalling     : anaconda-29.24.7-28.16.p07.ky10.aarch64                                                                                                                                                   1/2 
  Cleanup          : anaconda-29.24.7-28.16.p07.ky10.aarch64                                                                                                                                                   2/2 
  Running scriptlet: anaconda-29.24.7-28.16.p07.ky10.aarch64                                                                                                                                                   2/2 
  Verifying        : anaconda-29.24.7-28.16.p07.ky10.aarch64                                                                                                                                                   1/2 
  Verifying        : anaconda-29.24.7-28.16.p07.ky10.aarch64                                                                                                                                                   2/2 

Reinstalled:
  anaconda-29.24.7-28.16.p07.ky10.aarch64                                                                                                                                                                          

Complete!
[root@bogon pxeboot]# 
[root@bogon pxeboot]# 
[root@bogon pxeboot]# dracut --nomdadmconf --nolvmconf --xz --install '/.buildstamp' --no-early-microcode --add 'fips' --add 'anaconda pollcdrom qemu qemu-net prefixdevname-tools' initrd.img $(uname -r) --force
dracut: dracut module 'anaconda' cannot be found or installed.

**Comment by johannbg** [comment]
dracut does not ship or otherwise maintain the anaconda module, so consult anaconda's documentation, or contact the anaconda list for any question(s) or file an issue with anaconda upstream, if you are experiencing an issues with the dracut module they provide.

**Comment by haraldh** [comment]
This sounds like your distribution did not include the dracut stuff in the anaconda package. Please file a bug for your distribution.
