### ISSUE TITLE
skipcpio is broken if archive file data contains "TRAILER!!!"

### ISSUE THREAD

**Issue by ddiss** [dracutdevs/dracut#1123]
As documented at https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/cpio/CpioArchiveEntry.html , a serialized cpio archive carries a header for a special `TRAILER!!!` filename as the last entry in the archive.

Dracut's `skipcpio` is used by `lsinitrd` to skip past the CPU microcode cpio archive and dump the concatenated initramfs filesystem archive. It does so by reading 20 byte (2 * CPIO_ENDLEN) chunks from start to end and searching for `TRAILER!!!` in each chunk.
A cpio archive may carry file data with `TRAILER!!!` (e.g. for a nested archive), which could incorrectly be matched by the above logic and flagged as the end of the archive. `skipcpio` should only be checking for `TRAILER!!!` contents in the cpio filename field.

This was found purely via code inspection and to my knowledge hasn't been encountered in the wild. As such I think it can be marked low priority.

**Comment by ddiss** [comment]
In addressing this I think it makes sense to use a cpio library to perform the scan. I'd be happy to provide an implementation using libcpio from https://github.com/seL4/util_libs , libarchive or https://github.com/jcreekmore/cpio-rs , depending on upstream preference.

**Comment by haraldh** [comment]
Hmm, doesn't need a library. A loop like:
https://github.com/seL4/util_libs/blob/master/libcpio/src/cpio.c#L221-L251
would suffice... wouldn't it?

**Comment by ddiss** [comment]
> Hmm, doesn't need a library. A loop like:
> https://github.com/seL4/util_libs/blob/master/libcpio/src/cpio.c#L221-L251
> would suffice... wouldn't it?

It would, but keep in mind that the loop uses `cpio_parse_header()` to do most of the heavy lifting. Would "vendoring" libcpio be an option?

**Comment by haraldh** [comment]
Well, the cpio header format is pretty simple and stable.

**Comment by ddiss** [comment]
> Well, the cpio header format is pretty simple and stable.

True. I've gone a bit further with this and agree that a library is a bit overboard - skipcpio should only need the filename and data lengths and offsets to seek through to the first trailer. I'll submit my changes soon.

**Comment by haraldh** [comment]
Here is my take: https://github.com/dracutdevs/dracut/pull/1126
You triggered me. :smile:

**Comment by haraldh** [comment]
Please review or file your PR
