### ISSUE TITLE
90dmsquash-live: cannot handle overlayfs module built into kernel

### ISSUE THREAD

**Issue by AdrianVovk** [dracutdevs/dracut#1146]
**Describe the bug**
As of kmod 28, modprobe fails and spits out an error code if the kernel module you're trying to load is already built into the kernel. I'm not super sure if this is a kmod bug (I cross-opened an issue [there](https://github.com/kmod-project/kmod/issues/1) too, just in case), but this is currently breaking dracut. Dracut runs `modprobe overlay`, which fails because this module cannot be found (it's built-in) and then dracut stops and refuses to continue booting.

**Distribution used**
carbonOS 2021.1 (my own in-development distro)

**Dracut version**
53

**Init system**
systemd

**To Reproduce**
Build Linux with CONFIG_OVERLAY_FS as `y` instead of `m`. Ensure running on kmod 28. System will fail to boot into a live OS.

**Comment by haraldh** [comment]
Hmm, I can't reproduce this with kmod 28.

```console
# modprobe --version
kmod version 28
+ZSTD +XZ +ZLIB +LIBCRYPTO -EXPERIMENTAL

# modinfo sg
name:           sg
filename:       (builtin)
[…]

# modprobe sg; echo $?
0

# lsinitrd /lib/modules/5.11.16-300.fc34.x86_64/initrd -f usr/lib/modules/5.11.16-300.fc34.x86_64/modules.builtin  | grep sg.ko
kernel/block/bsg.ko
kernel/drivers/scsi/sg.ko
```

**Comment by haraldh** [comment]
This is likely the culprit: https://github.com/dracutdevs/dracut/pull/1436
