### ISSUE TITLE
initramfs are not compressed when early_microcode=yes

### ISSUE THREAD

**Issue by tpgxyz** [dracutdevs/dracut#1155]
**Describe the bug**
Why to compress image if it does not work ?

**Distribution used**
OpenMandriva Lx

**Dracut version**
053

**Init system**
systemd

**To Reproduce**
dracut -f --xz
[root@tpg-latitude5490 boot]# file -s /boot/initrd-5.10.14-desktop-1omv4002.img
initrd-5.10.14-desktop-1omv4002.img: ASCII cpio archive (SVR4 with no CRC)

**Expected behavior**
dracut -f --xz
[root@tpg-latitude5490 boot]# file -s initrd-5.10.14-desktop-1omv4002.img.xz.org 
initrd-5.10.14-desktop-1omv4002.img.xz.org: XZ compressed data

**Additional context**
Image is first created here as early_microcode is default enabled
https://github.com/dracutdevs/dracut/blob/2ec7fa190efe83e0cacd49aac55b582a32133e55/dracut.sh#L2274

Then it is appended by https://github.com/dracutdevs/dracut/blob/2ec7fa190efe83e0cacd49aac55b582a32133e55/dracut.sh#L2333
which does not work, in meaning that output file is not compressed.

**Comment by haraldh** [comment]
Are you sure? With `early_microcode=yes` we should have one uncompressed cpio prepended to the real compressed initramfs.
```shell
# dracut --xz test.img
# file test.img
test.img: ASCII cpio archive (SVR4 with no CRC)
# /usr/lib/dracut/skipcpio test.img >real-initramfs.img
# file real-initramfs.img
real-initramfs.img: XZ compressed data
```

**Comment by tpgxyz** [comment]
Maybe this have something to do with using bsdcpio ( from libarchive) by me as a standard cpio

**Comment by tpgxyz** [comment]
Sorry for the noise i checked with `/usr/lib/dracut/skipcpio test.img >real-initramfs.img` and yes it is compressed.
To bad i did not find any documentation on that.
