### ISSUE TITLE
network-manager has files missing on Arch Linux (+ other distros without /usr/libexec)

### ISSUE THREAD

**Issue by rosieeyes** [dracutdevs/dracut#1161]
**Describe the bug**
Including the network-manager dracut module on Arch Linux doesn't work fully; as Arch doesn't use libexec, both of /usr/lib/nm-dhcp-helper and /usr/lib/nm-initrd-generator are left out of the initrd.

**Distribution used**
Arch Linux

**Dracut version**
dracut-053

**Init system**
systemd

**To Reproduce**
Add `add_dracutmodules+=" network-manager"` to dracut.conf/dracut.conf.d on an Arch system (or on any system missing /usr/libexec) and generate an initramfs.

**Expected behavior**
Including the network-manager dracut module and then generating the initramfs works just fine, with no missing files.

**Additional context**
This is easily worked around by a quick symlink from libexec to lib.

**Comment by johannbg** [comment]
This was fixed with #1480 and #1473 hence closing
