### ISSUE TITLE
dracut github user

### ISSUE THREAD

**Issue by haraldh** [dracutdevs/dracut#120]
I would like to create a github "dracut" organization, but the @dracut user is in the way

**Comment by ivy** [comment]
Have you tried messaging GitHub support? I've found that they're generally more than happy to free up a name when the user hasn't been active. In this case, it looks like they don't have any repositories, stars, followers, or anything close to activity.

**Comment by johannbg** [comment]
I just went ahead and took the liberty to contact github support and asking them what we can do, to either get this dormant dracut user account handed to the project and or removed. ( For reference ticket ID: 796166 ).

**Comment by johannbg** [comment]
@haraldh Github support has responded and from the looks of it there is nothing that can be done ( unless involving some form of legal entity but even if the project had lawyer on retainer she/he would have a slim odds of success ). 

I'm including the full informative response from github support and closing this issue...

"
Hi Jóhann,

    As a project what can we do to either get this dormant user account handed to the project and or removed?

Thanks for reaching out, this is a great question, though the answer may not be quite what you're hoping for! I'll explain how this works for your own interest.

We have some advice and a couple of areas of policy designed for this. Our Name Squatting Policy and our Trademark Policy.

By far the easiest and what we recommend is to attempt to get in touch with the user yourself and politely ask for the username (which they don't need to give up of course). Sometimes a user has public facing contact information in their profile or it can be found in commit patches to public repositories. (It doesn't appear that the dracut user has this information on their profile in this specific case.)

I've conducted a dormancy audit for you on the dracut account and I'm afraid there's some activity that means it's not dormant (not all activity on GitHub is public) or available for release under our Name Squatting Policy:

https://docs.github.com/en/github/site-policy/github-username-policy#name-squatting-policy

While we do have the Name Squatting Policy, and I think this is what the commenter in the issue you linked was referring to, we find it's relatively rare that we can release usernames this way.

This leaves the Trademark Policy.

If you believe this user is infringing on your trademark, please take a look at our Trademark Policy page for more information on what's required and how to start that process:

https://docs.github.com/en/github/site-policy/github-trademark-policy

Trademark policy violations normally require some sort of misrepresentation and, although this will be handled by the GitHub legal team, it doesn't appear that this user is pretending to represent the project you're referencing, they just have the same name. GitHub usernames are issued on a first-come, first-serve basis.

That's not the official GitHub position at this stage of course, like I said our legal team would handle this and be better placed to give you the facts. I just want to manage your expectations and give you some information.

I hope this answers your question and like I said, sorry it's probably not what you were hoping for, but please let me know if you need anything else.

Best regards,
Billy"
