### ISSUE TITLE
98integrity/ima-keys-load.sh: bad style `for file in $(ls <dir>)`

### ISSUE THREAD

**Issue by haraldh** [dracutdevs/dracut#1267]
https://github.com/dracutdevs/dracut/blob/c5dd11f99fb54937346eaee7c224ff8c7527298c/modules.d/98integrity/ima-keys-load.sh#L20-L21

**Comment by aafeijoo-suse** [comment]
This was fixed by https://github.com/dracutdevs/dracut/pull/1823, I didn't realize this issue existed.
