### ISSUE TITLE
cant configure multiple bonds

### ISSUE THREAD

**Issue by bcg62** [dracutdevs/dracut#132]
Issue is referenced here:

https://bugzilla.redhat.com/show_bug.cgi?id=1282679

I'm experiencing the same behavior, the patch provided on the bug link seems to resolve the issue.

**Comment by bcg62** [comment]
redhat is now carrying the patch 

https://rhn.redhat.com/errata/RHBA-2016-2530.html

**Comment by bcg62** [comment]
I think this may also exist for vlans, looking at https://github.com/dracutdevs/dracut/blob/master/modules.d/40network/parse-vlan.sh I dont see how it could be looping more than one.

**Comment by haraldh** [comment]
yeah. I have to forward port the patches from RHEL-7 to master:
https://github.com/dracutdevs/dracut/blob/RHEL-7/modules.d/40network/parse-vlan.sh

**Comment by haraldh** [comment]
yeah, I have to forward port the RHEL-7 changes to master:
https://github.com/dracutdevs/dracut/commit/7a90c8b3434a27a347f6a963d0e673e04feb485a

**Comment by bcg62** [comment]
ah, thanks @haraldh - Im currently investigating some issues using multiple bonds in tandem with multiple vlans. Let me try this patch and see if the behavior is the same

**Comment by bcg62** [comment]
I can confirm the network module cleanup in the rhel7 branch resolves all my issues.

**Comment by haraldh** [comment]
Ok, I'll "just" have to forward port those :-/
