### ISSUE TITLE
Packit settings for COPR build

### ISSUE THREAD

**Issue by mfocko** [dracutdevs/dracut#1346]
Hi,

I see that you have set up COPR builds triggered by push to the `master`, there are over 100 errors accumulated on our side with:

    Copr project @dracut/Dracut not found.

I am not sure if it is a typo (I cannot seem to be able to find dracut nor dracutdevs group in the COPR) or permission issue.
Could you please have a look at it? And in case it is permission problem, add `packit` to either group or project?

Thanks :)

---
COPR builds apart from _push to master_ are fine :)
Related lines: https://github.com/dracutdevs/dracut/blob/651fe01e7937d86bbd471d9621581bed44f23dfa/.packit.yml#L57-L58

**Comment by johannbg** [comment]
@mfocko Where can I find packit onboarding guide for copr and or other documentation that shows best practices settings copr repo  to be used with packit? 

@haraldh presumably you need to use the dracut-maint? owner account for this and we update this accordingly and or remove it. Creating rpms in copr for all none EOL fedora release should help testing so there is value in having copr repo for this.

**Comment by mfocko** [comment]
Sorry for the delay. I glanced through the onboarding guide, we don't mention much about COPR settings there. Most of the COPR related changes are done after Packit is set up via comments on PRs with instructions.

You have basically 2 options:

- giving packit `admin` permissions
  - we take care of updating settings (e.g. chroots)
- giving packit `builder` permissions
  - if there is a need to make a change we post comment on PR with the changes in settings that need to be applied

Hope it helps :)

Link to COPR options in packit configuarion: https://packit.dev/docs/configuration/#supported-jobs
