### ISSUE TITLE
"logger" invocation borked.

### ISSUE THREAD

**Issue by poettering** [dracutdevs/dracut#1353]
This line is borked in current git:

https://github.com/dracutdevs/dracut/commit/aa225ca3b0170cf66dca1017eda273f143b8b8d3#diff-40881e2ec31488fb71f41038a33270005875c9c73969c8858a3f031346b6390cR243

i.e. i.e. printf and "--" work differently than it is assumed in that commit. Example:

```
$ printf "%s" -- "foo."
--foo.
```

i.e. the "--" is output, but as I grok the commit that's not expected

(not a shell guru myself enough to prep a fix)

**Comment by johannbg** [comment]
@poettering fairly recent refactoring/shellcheck fallout and there exist already a PR to fix this ( #1351 ) it's just waiting for ack from @haraldh and or @danimo ...

**Comment by poettering** [comment]
Ah, nice, then I guess we don't need to track this once more. Let's close.
