### ISSUE TITLE
when execute the command 'dracut --force' no log output and exit 

### ISSUE THREAD

**Issue by sunnyccr** [dracutdevs/dracut#1364]
**Describe the bug**
rpm -ivh /tmp/xxx.rpm
and it contains the command 'dracut --force'
when execute the command 'dracut --force' no log output and exit 

**Distribution used**
CentOs-7.6

**Dracut version**
CentOs-7.6

**Init system**
CentOs-7.6  
Version: 033-554.el7

**To Reproduce**
rpm -ivh /tmp/xxx.rpm

**Expected behavior**
Apr  8 17:27:47 ve139 dracut: Executing: /sbin/dracut --force
Apr  8 17:27:48 ve139 dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
Apr  8 17:27:48 ve139 dracut: dracut module 'dmsquash-live-ntfs' will not be installed, because command 'ntfs-3g' could not be found!
Apr  8 17:27:49 ve139 dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
Apr  8 17:27:50 ve139 dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
Apr  8 17:27:50 ve139 dracut: dracut module 'dmsquash-live-ntfs' will not be installed, because command 'ntfs-3g' could not be found!
Apr  8 17:27:51 ve139 dracut: *** Including module: bash ***
Apr  8 17:27:51 ve139 dracut: *** Including module: nss-softokn ***
Apr  8 17:27:51 ve139 dracut: *** Including module: i18n ***
Apr  8 17:27:52 ve139 dracut: *** Including module: network ***
Apr  8 17:27:52 ve139 dracut: *** Including module: ifcfg ***
Apr  8 17:27:52 ve139 dracut: *** Including module: drm ***
Apr  8 17:27:53 ve139 dracut: *** Including module: plymouth ***
Apr  8 17:27:53 ve139 dracut: *** Including module: dm ***
Apr  8 17:27:53 ve139 dracut: Skipping udev rule: 64-device-mapper.rules
Apr  8 17:27:53 ve139 dracut: Skipping udev rule: 60-persistent-storage-dm.rules
Apr  8 17:27:53 ve139 dracut: Skipping udev rule: 55-dm.rules
Apr  8 17:27:53 ve139 dracut: *** Including module: kernel-modules ***
Apr  8 17:27:55 ve139 dracut: *** Including module: lvm ***
Apr  8 17:27:55 ve139 dracut: Skipping udev rule: 64-device-mapper.rules
Apr  8 17:27:55 ve139 dracut: Skipping udev rule: 56-lvm.rules
Apr  8 17:27:55 ve139 dracut: Skipping udev rule: 60-persistent-storage-lvm.rules
Apr  8 17:27:55 ve139 dracut: *** Including module: rootfs-block ***
Apr  8 17:27:55 ve139 dracut: *** Including module: terminfo ***
Apr  8 17:27:55 ve139 dracut: *** Including module: udev-rules ***
Apr  8 17:27:55 ve139 dracut: Skipping udev rule: 40-redhat-cpu-hotplug.rules
Apr  8 17:27:56 ve139 dracut: Skipping udev rule: 91-permissions.rules
Apr  8 17:27:56 ve139 dracut: *** Including module: systemd ***
Apr  8 17:27:56 ve139 dracut: *** Including module: usrmount ***
Apr  8 17:27:56 ve139 dracut: *** Including module: base ***
Apr  8 17:27:56 ve139 dracut: *** Including module: fs-lib ***
Apr  8 17:27:56 ve139 dracut: *** Including module: shutdown ***
Apr  8 17:27:56 ve139 dracut: *** Including modules done ***
Apr  8 17:27:56 ve139 dracut: *** Installing kernel module dependencies and firmware ***
Apr  8 17:27:57 ve139 dracut: *** Installing kernel module dependencies and firmware done ***
Apr  8 17:27:57 ve139 dracut: *** Resolving executable dependencies ***
Apr  8 17:27:57 ve139 ipmievd: Slot / Connector sensor NIC2-2 Link Down - Slot is Disabled Asserted
Apr  8 17:27:57 ve139 ipmievd: Slot / Connector sensor NIC2-1 Link Down - Slot is Disabled Asserted
Apr  8 17:27:58 ve139 dracut: *** Resolving executable dependencies done***
Apr  8 17:27:58 ve139 dracut: *** Hardlinking files ***
Apr  8 17:27:58 ve139 dracut: *** Hardlinking files done ***
Apr  8 17:27:58 ve139 dracut: *** Stripping files ***
Apr  8 17:27:58 ve139 dracut: *** Stripping files done ***
Apr  8 17:27:58 ve139 dracut: *** Store current command line parameters ***
Apr  8 17:27:58 ve139 dracut: *** Creating image file ***
Apr  8 17:28:01 ve139 systemd: Created slice User Slice of pcp.
Apr  8 17:28:01 ve139 systemd: Started Session 69 of user pcp.
Apr  8 17:28:01 ve139 systemd: Started Session 71 of user omm.
Apr  8 17:28:01 ve139 systemd: Started Session 67 of user omm.
Apr  8 17:28:01 ve139 systemd: Started Session 68 of user omm.
Apr  8 17:28:01 ve139 systemd: Started Session 70 of user omm.
Apr  8 17:28:01 ve139 systemd: Removed slice User Slice of pcp.
Apr  8 17:28:07 ve139 dracut: *** Creating image file done ***
Apr  8 17:28:11 ve139 dracut: *** Creating initramfs image file '/boot/initramfs-4.14.0-115.el7a.0.1.aarch64.img' done ***

**Additional context**
abnormal os message log as bellow(after log the /sbin/dracut --force ,then no any other dracut related logs output):

Apr  8 17:19:39 ve234 dracut: Executing: /sbin/dracut --force

**Comment by johannbg** [comment]
Sorry this is a release from the year 2013 and we try to limit looking into issues older than the two most recently releases here upstream so you will need to either consult your downstream distribution maintainer to track this down or rebuild the latest dracut for your distribution, re-test it with it and report back if it's still an issue.

**Comment by sunnyccr** [comment]
How can I query the version of dracut?thanks
@johannbg

**Comment by haraldh** [comment]
```
$ rpm -q dracut
```
