### ISSUE TITLE
fcoe module always included in hostonly initramfs for UEFI system, even if no FCoE mounts

### ISSUE THREAD

**Issue by AdamWill** [dracutdevs/dracut#139]
I ran across this while debugging https://bugzilla.redhat.com/show_bug.cgi?id=1347436 . Pasting from there:

each dracut module has a `check()` function which is used to indicate whether the module can and/or should be included in the initramfs being built. the `check()` function for the `fcoe` module does this:

    check() {
        [[ $hostonly ]] || [[ $mount_needs ]] && {
            for c in /sys/bus/fcoe/devices/ctlr_* ; do
                [ -L $c ] || continue
                fcoe_ctlr=$c
            done
            [ -z "$fcoe_ctlr" ] && return 255
        }

        require_binaries dcbtool fipvlan lldpad ip readlink fcoemon fcoeadm || return 1
        return 0
    }

So I think the first part there is basically a 'is this module needed' check: if we're in hostonly mode (or 'mount_needs', dunno what that is), let's check and see if there are actually any FCoE devices, and if not, return `255`, indicating 'module isn't needed'.

The second part means 'make sure we can include these binaries in the initramfs, otherwise return `1` indicating the module should be included, but cannot be because some required binaries are missing'.

However, we have this `95fcoe-uefi` module, too. How does `setup()` for that module look?

    check() {
        [[ $hostonly ]] || [[ $mount_needs ]] && {
            [ -d /sys/firmware/efi ] || return 255
        }
        require_binaries dcbtool fipvlan lldpad ip readlink || return 1
        return 0
    }

note it doesn't, AFAICS, include the check from the `fcoe` module. It just checks whether this is a UEFI boot, and wants to be enabled if it is. It also has this:

    depends() {
        echo fcoe uefi-lib
        return 0
    }

which obviously indicates a requirement for the 'fcoe' module. So I think what happens when you build a 'hostonly' initramfs on UEFI is that the `fcoe` module `check()` returns `255` (meaning 'nope, I don't need to be included'), but the `fcoe-uefi` module `check()` returns `0` (meaning 'yes, I do want to be included!') and drags `fcoe` along via dependencies (presumably a dependency beats out a `255` `check()` return code).

So you wind up with the fcoe module *always* included in initramfs'es built on UEFI systems, even though there are no FCoE mounts.

I dunno what the right way to fix this is - just duplicate the `fcoe` module's 'are there any FCoE mounts?' check into `fcoe-uefi`, or if there's a better way.

**Comment by haraldh** [comment]
should be fixed with https://github.com/dracutdevs/dracut/commit/5a3773dbe6b48a872295d6a10f87e5329f0113a1
