### ISSUE TITLE
add option to make network-legacy be the default (?)

### ISSUE THREAD

**Issue by mikhailnov** [dracutdevs/dracut#1404]
Currently the logics of including a network module is the following on a typical Linux desktop without wicked:

- try network-manager, if ok, put it into the initrd
- try systemd-networkd, if ok, put it into the initrd
- use network-legacy otherwize

So, NetworkManager is chosen in most cases on Linux desktops and even servers. The problems that I see are the following:

- big size of initrd, longer compression time (not a very big problem)
- if NetworkManager and dbus are updated, initrd should be regenerated to ensure smooth transition of network setup state from initrd to the main system

I do not see any big advantages that NM gives so that rebuilding initrd would be worth spending time and resources. To my mind, may be I am missing something, configuring network in initrd is not required in by far the vast majority of cases, and, when it is needed, a simple dhclient from network-legacy fits most of the needs. A typical desktop or server system does not require network in initrd; when it is necessary if, for example, a PXE boot: anaconda-dracut downloads a kickstart file, a rootfs image etc. In this case, I think, it is not so important to transfer state of the network setup from initrd to the main system.

Are there usecases when NM+dbus is a really great solution? Are those cases ot rare so that it makes sense to make NM be the default choice?

I do not like a so much overcomplicated initrd by default and I am thinking of making network-legacy ot systemd-networkd the default choice in the distro (ROSA 2019.1+). I can explicitly list the needed module in the default config like this:
`add_modules+=" network-legacy "`
but how should a user who want another network module overwrite this default by a config in /etc/dracut without touching the default config in /usr/lb/dracut? Probably there is no way to do it cleanly, so I am thinking about adding a special option like:
`preferred_network_module=network-legacy`
or something else like that.

Here are my thoughts. I would be happy to hear arguements for and against NetworkManager as the default choice and thoughts about such option.

**Comment by johannbg** [comment]
It's up to distributions/vendors/users to decide what they considered default and configure it as such. 
The network module is only a meta module which serves as the role for other modules that require networking to depend upon.

If there ever would be a default it would end up being systemd networkd since the legacy network stack should be considered obsolete at this point and replaced with more modern solutions iwd,networkd,NM, Wicked etc.

So if we decide to correct the "picking" order in the network meta module or default to some network management solution, it will always be networkd ( which is available in all systemd distribution which are majority of them + embedded IVI's and such ) --> iwd ( which provides the wifi stack + standalone network management solution thus serves two roles in the network stack and covers the embedded space and up ) --> NM ( or Wicked ) --> Wicked ( or NM ).

**Comment by mikhailnov** [comment]
networkd looks a good default choice bcause it is both quite simple and modern and will even probably allow to pass state of network from initrd into the main system, but why is NM the current default?

**Comment by johannbg** [comment]
Sorry I dont follow what you mean by default. The network meta module just picks what's installed on the system so if a distributions decides to offer multiple Network Management solutions just uninstall the one that you dont want for your system and the network module will pick that one.

**Comment by mikhailnov** [comment]
Most distros have NetworkManager by default and have systemd-networkd also (at least in ROSA and, if I remmeber correctly, in Ubuntu, it is not splitted into a separate package or at least it is installed by default). ROSA also uses dhclient in NetworkManager instead of the built-in dhcp client because dhclient works better. So in case of desktop distros 3 network configuration slutions are available: NetworkManager, systemd-networkd, dhclient.

The code is the following:

```
depends() {
    is_qemu_virtualized && echo -n "qemu-net "

    for module in network-wicked network-manager network-legacy systemd-networkd; do
        if dracut_module_included "$module"; then
            network_handler="$module"
            break
        fi
    done

    if [ -z "$network_handler" ]; then
        if find_binary wicked &> /dev/null; then
            network_handler="network-wicked"
        elif [[ -x $dracutsysrootdir/usr/libexec/nm-initrd-generator ]]; then
            network_handler="network-manager"
        elif [[ -x $dracutsysrootdir$systemdutildir/systemd-networkd ]]; then
            network_handler="systemd-networkd"
        else
            network_handler="network-legacy"
        fi
    fi
    echo "kernel-network-modules $network_handler"
    return 0
}
```

and NM is the preffered/default choice there

**Comment by mikhailnov** [comment]
hm, in the first block of code network-legacy has priority over systemd-networkd and in the second block of code - networkd has priority, is it intentional?

**Comment by johannbg** [comment]
Nope since it's irrelevant. 
Downstream always either has to install or not install the component they intent to use or not use for meta modules or add/omit modules they intent to use or not use which makes the order we provide irrelevant in other words there is no "default"

**Comment by johannbg** [comment]
We as an upstream cannot dictate or decide how downstream distribution/users/vendors decided to build their OS stack or predict how they intent to do so by setting some arbitrary default. 

For example in the case of the network module networkd can be used in conjunction with both iwd and nm and iwd can be used in conjunction with both networkd and nm and nm can be used with both networkd and iwd so no matter which order we would set as a default we would be breaking it for someone else if they decide to use any more than anyone of these at the same time.

**Comment by mikhailnov** [comment]
Thanks for all comments, I have proposed a solution in https://github.com/dracutdevs/dracut/pull/1421
