### ISSUE TITLE
DefaultDependencies=no missing in two unit files

### ISSUE THREAD

**Issue by poettering** [dracutdevs/dracut#151]
Two of the dracut unit files should really set DefaultDependencies=no, but currently do not. All early-boot stuff should really set this. Specifically, these are the pre-pivot and mount service files. But there might be more, I didn't look into this in all detail.

(and while we are at it, some of the dracut unit files reference systemd.special(7) as documentation, and really shouldn't, since that man page doesn't cover dracut units...)

**Comment by poettering** [comment]
Note that fixing this would probably be a pre-requisite for the ideas suggested in https://github.com/systemd/systemd/issues/3436

**Comment by haraldh** [comment]
Already fixed in git master
