### ISSUE TITLE
prelink missing libelf.so.1

### ISSUE THREAD

**Issue by gagern** [dracutdevs/dracut#152]
As reported in [Gentoo bug 585106](https://bugs.gentoo.org/show_bug.cgi?id=585106), dracut 044 has problems on Gentoo when prelinking:

```
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done***
dracut: *** Pre-linking files ***
/usr/sbin/prelink: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory
dracut: *** Pre-linking files done ***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
```

The [corresponding dracut code](https://github.com/dracutdevs/dracut/blob/044/dracut.sh#L1559-L1564) reads thus:

``` sh
        dinfo "*** Pre-linking files ***"
        inst_multiple -o prelink /etc/prelink.conf /etc/prelink.conf.d/*.conf
        chroot "$initdir" "$PRELINK_BIN" -a
        rm -f -- "$initdir/$PRELINK_BIN"
        rm -fr -- "$initdir"/etc/prelink.*
        dinfo "*** Pre-linking files done ***"
```

So apparently it lists the files `prelink` will probably need, does the prelink step, then uninstalls said files again. But it misses the `libelf` reported by `ldd`:

```
# ldd /usr/sbin/prelink 
    linux-vdso.so.1 (…)
    libelf.so.1 => /usr/lib64/libelf.so.1 (…)
    libc.so.6 => /lib64/libc.so.6 (…)
    libz.so.1 => /lib64/libz.so.1 (…)
    /lib64/ld-linux-x86-64.so.2 (…)
```

I think `dracut-install --ldd` (or some shell function invoking this, e.g. `DRACUT_RESOLVE_DEPS=1 inst_multiple`) should be able to install the `prelink` binary with all accompanying files. But cleaning that up again might be tricky.

**Comment by tpgxyz** [comment]
Interesting why prelink support is still available in dracut, as it has been proven that prelink does more bad than good. (https://pagure.io/fesco/issue/1183)

Btw, here is the patch that fixes that prelink
https://github.com/OpenMandrivaAssociation/dracut/blob/master/dracut-034-fix-prelink.patch

**Comment by haraldh** [comment]
@tpgxyz care to create a pull request with that patch?

**Comment by tpgxyz** [comment]
@haraldh done, please merge. Thanks

**Comment by Massimo-B** [comment]
Any news here?

**Comment by haraldh** [comment]
Hmm, thinking more about this. If ```ldd prelink``` reports libelf, the bug would be in dracut-install not installing the corresponding libelf.so.

Is this still an issue with dracut-046 ???
If yes, could you please point me to the stderr output of dracut started with ```--debug```

**Comment by haraldh** [comment]
Those who can read have an advantage.

> I think dracut-install --ldd (or some shell function invoking this, e.g. DRACUT_RESOLVE_DEPS=1 inst_multiple) should be able to install the prelink binary with all accompanying files. But cleaning that up again might be tricky.
