### ISSUE TITLE
Build an initramfs image in a docker container

### ISSUE THREAD

**Issue by 1Jo1** [dracutdevs/dracut#1527]
my idea is to use 1jo1/fedora-netty-build as my docker image to build a kernel image and create an initramfs image

setup:
- [docker custom docker image](https://hub.docker.com/repository/docker/1jo1/fedora-netty-build) here my [Dockerfile](https://gist.github.com/1Jo1/908dfa3803dfc0beb745a7a219159db3)
- kernel 5.12.9 compile image and install the modules(/usr/lib/modules) in a container
- dracut version: 054-12.git20210521.fc34
- docker version 20.10.6

when I run dracut in a docker container
`dracut /linux-5.12.9/initramfs-5.12.img 5.12.9`
```
dracut: WARNING: running in hostonly mode in a container!!
findmnt: can't read (null): No such file or directory
```

I'm just wondering the initramfs image is only 42MB, compare to 700 MB when I build it on the host machine

is there a way to create an initramfs in docker container?

**Comment by simonfxr** [comment]
I'm doing something similar, building a initramfs using dracut in a rootless podman container based on ubuntu focal. I'm using `dracut -N --no-hostonly-cmdline` and I can succesfully boot it in qemu or on bare metal afterwards.

**Comment by haraldh** [comment]
Yes, build with ` -N --no-hostonly-cmdline`
