### ISSUE TITLE
printf not installed

### ISSUE THREAD

**Issue by jpalus** [dracutdevs/dracut#1530]
**Describe the bug**
Multiple errors about missing printf are logged during boot when `/bin/sh` points to `mksh`

**Distribution used**
PLD

**Dracut version**
055

**Init system**
systemd

**To Reproduce**
Generate image with `/bin/sh -> mksh`

**Expected behavior**
All messages are logged correctly.

**Additional context**
`printf` is not a builtin in `mksh` (at least does not seem to be by default) and `printf` binary is not installed.

**Comment by jpalus** [comment]
Perhaps a sanity check could be added like:
```sh
PATH= ./bin/sh -c 'printf test' > /dev/null 2> /dev/null || inst printf
```

**Comment by tpgxyz** [comment]
Good catch. Looks like mksh by default disables use of builtin printf
`USE_PRINTF_BUILTIN?=	0`
https://github.com/MirBSD/mksh/blob/4a59132d5fa2193f59345855d89aae72f062f100/Makefile#L73

**Comment by jpalus** [comment]
Note that #1534 does not fix this issue as mentioned in PR's discussion.
