### ISSUE TITLE
dracut-initramfs-restore / dracut-shutdown.service not creating .need_shutdown

### ISSUE THREAD

**Issue by xogium** [dracutdevs/dracut#1536]
Hi,
I've been trying to use dracut for a while today with my archlinux vm, for testing purpose.

Everything works great, till shutdown.

The dracut-initramfs-restore script.... Simply doesn't work.

When I manually ran it with bash -x, I got the following:

```
+ set -e
+ '[' -e /run/initramfs/bin/sh ']'
+ '[' -e /run/initramfs/.need_shutdown ']'
+ exit 0
```

However, /run/initramfs is empty, aside from the also empty logs directory. I don't have the need_shutdown, nor the sh shell in there, at all. I also tried the very latest script from your 055 tag, and I get the same behavior. I think this script is broken, somehow. Or possibly, my system is in some way I can't figure out.

Any help is appreciated.

**Comment by xogium** [comment]
So, after investigating deeper, it turns out there is one very annoying thing.

My screen reader and text to speech program do not say dot at the start of file names. So all this time, I was using need_shutdown not .need_shutdown -- yes, I do want to kill that software now ;)

But anyway moving on... It looks like the default dracut-shutdown.service is broken though, as the file doesn't touch the .need_shutdown that is required, and this also explains why it did not work when systemd tried to run it.

Is this intended ? Are distros supposed to place that file themselves with another servicee ?

**Comment by Jookia** [comment]
It looks like (I haven't confirmed yet) that modules need to run a need_shutdown flag (thanks MartinR) https://forums.centos.org/viewtopic.php?t=57351#p241998 The manual as of writing doesn't mention need_shutdown in any capacity aside from debugging dracut on shutdown.

**Comment by Jookia** [comment]
The other thing that isn't documented is where the initramfs is supposed to be.
