### ISSUE TITLE
'root=' doesn't accept labels when using rd.luks.name=uuid=name

### ISSUE THREAD

**Issue by LynHyper** [dracutdevs/dracut#1543]
I saw the post about systemd-cryptsetup before and decided to do some testing, turns out cryptsetup is working for me (save for https://github.com/dracutdevs/dracut/pull/1526), but, I noticed that if you point root to something like "root=LABEL=root" ('root' being the label of a filesystem within a crypt volume) within the kernel_cmdline entry of dracut.conf then rebooting would lead to errors.

Putting root=/dev/mapper/root works completely fine, and installs that aren't within a crypt volume can use root=LABEL=root successfully.

Arch Linux
Dracut 055-1
Systemd

To Reproduce:
Setup a luks-crypt volume of name "name" and a filesystem within it labelled "root".
Put kernel_cmdline as "rd.luks.name=crypt-uuid=name root=LABEL=root".
Run Dracut
Reboot
Get kicked into emergency shell, run journalctl, and see errors about not being able to find a root of label "root".

**Comment by haraldh** [comment]
what is the output of:

```
# dracut --print-cmdline
```
???

**Comment by LynHyper** [comment]
Just tried recreating the same conf file using root=LABEL=root with my laptop as I did when I first installed it, I couldn't recreate the problem and everything booted fine, I suspect other parameters caused the issue during the install. Apologize for the false report.
