### ISSUE TITLE
`--omit` command line option no longer overrides config file in version 054 and later

### ISSUE THREAD

**Issue by lapseofreason** [dracutdevs/dracut#1551]
**Describe the bug**
In version 053, the command line option `--omit` used to override the options from the config file, whereas in version 054 and later it adds to it instead. This behaviour breaks existing scripts using the `--omit` flag.

**Distribution used**
Fedora 33

**Dracut version**
dracut 055-2.fc33

**Init system**
systemd

**To Reproduce**
1. Create a config file in `/etc/dracut.conf.d/` with the line `omit_dracutmodules+=" systemd "`.
2. Create an initrd with dracut from the command line with the `--omit` option (e.g. `--omit resume`).
3. Check that the resulting initrd does not include systemd.

**Expected behavior**

The option `--omit` should override the options from the config file just as the manpage for `dracut.conf` states:

> Command line parameter will override any values set here.

**Additional context**
While the behaviour between `--add` and `--omit` is more consistent in version 054 than in version 053 (both add to the config options instead of replacing it), there is now no more way to override those options from command line.

Probably introduced in commit 96c313333.

My goal is actually to omit systemd and add crypt-gpg by default (i.e. in a config file), but then override this via command line.

**Comment by johannbg** [comment]
@lapseofreason the old behavior was wrong,the fix that you refer to is the correct one. Adding and omitting module should act in the exact same manner. Your usecase is currently unsupported as in if we intend to support it we need to do so via new command line option.

**Comment by haraldh** [comment]
As a workaround: with `--confdir` you could negate all config settings.

**Comment by lapseofreason** [comment]
@johannbg You are right, this does make it more consistent. Maybe `man dracut.conf` should be changed to make it more clear that not all command line options override the configuration, but some merely add to them.

@haraldh Thanks for the workaround, this works perfectly for my usecase.
