### ISSUE TITLE
NetworkManager configure the network after luks disk unlocking since 054 or 055

### ISSUE THREAD

**Issue by champtar** [dracutdevs/dracut#1554]
**Describe the bug**
I'm using https://github.com/gsauthof/dracut-sshd to ssh into the initramfs and type the password to unlock my rootfs
upgrading from 053 to 055, NetworkManager request an IP via DHCP only after my rootfs is unlocked, preventing me from using ssh.

**Distribution used**
Fedora 34

**Dracut version**
Broken: dracut-055-2.fc34.x86_64
Working: dracut-053-4.fc34.x86_64

**Init system**
systemd

**To Reproduce**
Have a systemd with encrypted rootfs
Add `rd.neednet=1 ip=dhcp` on the kernel command line

**Expected behavior**
While displaying the password prompt, NetworkManager gets an IP via DHCP and you can ping this IP form another computer before unlocking

**Additional context**
NetworkManager does start before the disk password prompt, but it does nothing
quickly trying to debug with `rd.debug=pre-mount`, I'm still asked for luks password before having the shell, and if I type the password, in the shell I see that NetworkManager does get the IP.

The problem might be that luks password is asked too early (before mount phase)

**Comment by ajkerzner** [comment]
Might be related to https://bugzilla.redhat.com/show_bug.cgi?id=1976641 .

**Comment by Komic** [comment]
Exact same problem, I wasn't even able to manually use console_auth or unlock.

**Comment by champtar** [comment]
Thanks @ajkerzner 
With `dbus-broker-29-2.fc34.x86_64` (and `dracut-055-3.fc34.x86_64`) now everything works fine
