### ISSUE TITLE
CI: Debian Boot test / test/container/Dockerfile-Debian

### ISSUE THREAD

**Issue by woa7** [dracutdevs/dracut#1572]
**Describe the enhancement**
add a Debian Boot CI test via qemu like https://github.com/dracutdevs/dracut/blob/master/test/container/Dockerfile-Arch

needed subtasks:
* - [ ] create  test/container/Dockerfile-Debian
* - [ ] add to .github/workflows/container.yml
* - [ ] add to .github/workflows/integration.yml
* - [ ] Update documentation ( HACKING.md ) on how to use it for testing.

**Comment by johannbg** [comment]
CI for Debian has been implemented hence closing
