### ISSUE TITLE
CI: Alpine Boot test / test/container/Dockerfile-Alpine

### ISSUE THREAD

**Issue by woa7** [dracutdevs/dracut#1573]
**Describe the enhancement**
add a Alpine linux Boot CI test via qemu like https://github.com/dracutdevs/dracut/blob/master/test/container/Dockerfile-Arch

needed subtasks:
* - [ ] create  test/container/Dockerfile-Alpine
* - [ ] add to .github/workflows/container.yml
* - [ ] add to .github/workflows/integration.yml
* - [ ] Update documentation ( HACKING.md ) on how to use it for testing.

**Comment by LaszloGombos** [comment]
dracut*.sh functions expect blkid arguments to work (such us blkid -o, blkid -u). As far as I can tell these do not work on the Alpine supplied blkid binary. There might be other dependencies as well that needs to be resolved first before dracut test would run on Alpine linux.

**Comment by johannbg** [comment]
That's a nack our CI will only ever contain the primaries ( Arch,Debian,Fedora,Gentoo, OpenSuse ) otherwise we open the pandora's box of having to add all what close to 500 distro's or so
