### ISSUE TITLE
pxe booting a initramfs from dracut fails with "losetup: unexpected arguments"

### ISSUE THREAD

**Issue by marvinbernhardt** [dracutdevs/dracut#1576]
**Describe the bug**
See title

**Distribution used**
Fedora 33

**Dracut version**
dracut 055-3.fc33

**Init system**
Not sure about terminology. PXE?

**To Reproduce**
`dracut --force --no-hostonly --add 'livenet network base' /cluster/nodeimages/initramfs-dracut.img $(uname -r)`
Then use this in a PXE network boot setup.

**Expected behavior**
System boots in ram.

**Additional context**
Here is the problematic line https://github.com/dracutdevs/dracut/commit/94b0d89f173fef07bf7ab319d0d9c50e337871c6#r54513596
It should not have quotes there.

**Comment by haraldh** [comment]
Please test, if https://github.com/dracutdevs/dracut/pull/1577 fixes your issue.

**Comment by marvinbernhardt** [comment]
Sorry, I don't have time to do that. I have never compiled dracut manually. For now I am just using a version 050 rpm. But I understand the changes and I am pretty sure that fixes the issue.

**Comment by berlin4apk** [comment]
Can we please add a CI test for PXE boot?
