### ISSUE TITLE
USB boot/squashfs mount issue/Question

### ISSUE THREAD

**Issue by treedavies** [dracutdevs/dracut#1587]
Hi dracutdevs,

I am attempting to boot from a USB drive using kernel 5.4.41 with a initramfs built
with Dracut 0.50 from syslinux/isolinux. This is done on a LFS system. 
I specifically include the dmsquash-live module in my /etc/dracut.conf

My menu config looks like:
  linux /LiveOS/vmlinuz.x86_64 root=live:CDLABEL=Physix-Project rd.live.image
  APPEND initrd=/LiveOS/initramfs-img.x86_64 

At boot, the system halts soon after the following message.
dracut: FATAL: Don't know how to handle 'root=live:Physix-Project

I see the `root=live:CDLABLE=<label>` used by several other distro's live images.
If I use an initrd/initramfs from those distros, it works.

So my question is: What is needed, and missing,  from my initramfs to recognize this option? 

best regards,
Tree

**Comment by LaszloGombos** [comment]
@treedavies you might need the iso-scan/filename=PATH_TO_ISO argument as well and your .iso file should be labeled Physix-Project.
