### ISSUE TITLE
CI: build Docker Fedora:rawhide failed always if run via GH action

### ISSUE THREAD

**Issue by berlin4apk** [dracutdevs/dracut#1590]
**Describe the bug**
CI: build Docker Fedora:rawhide failed always if run via GH action
See logs https://github.com/dracutdevs/dracut/runs/3410519098?check_suite_focus=true

**Distribution used**
GH action

**Dracut version**
Master

**To Reproduce**
See https://github.com/dracutdevs/dracut/blob/655c65e6ced00e7a80c41e96c5f6fe108da07839/.github/workflows/container.yml#L33

**Expected behavior**
Build of the Docker container without errors

**Comment by berlin4apk** [comment]
https://github.com/dracutdevs/dracut/runs/3410519098?check_suite_focus=true#step:5:261
rs ago in 29s
3s
1s
16s
0s
8s
#1 1.751  * [new tag]           033        -> 033
#1 1.751  * [new tag]           034        -> 034
#1 1.751  * [new tag]           035        -> 035
#1 1.751  * [new tag]           036        -> 036
#1 1.752  * [new tag]           037        -> 037
#1 1.752  * [new tag]           038        -> 038
#1 1.752  * [new tag]           039        -> 039
#1 1.752  * [new tag]           040        -> 040
#1 1.752  * [new tag]           041        -> 041
#1 1.752  * [new tag]           042        -> 042
#1 1.752  * [new tag]           043        -> 043
#1 1.753  * [new tag]           044        -> 044
#1 1.753  * [new tag]           045        -> 045
#1 1.753  * [new tag]           046        -> 046
#1 1.753  * [new tag]           047        -> 047
#1 1.753  * [new tag]           048        -> 048
#1 1.753  * [new tag]           049        -> 049
#1 1.754  * [new tag]           050        -> 050
#1 1.754  * [new tag]           051        -> 051
#1 1.754  * [new tag]           052        -> 052
#1 1.754  * [new tag]           053        -> 053
#1 1.755  * [new tag]           054        -> 054
#1 1.755  * [new tag]           055        -> 055
#1 DONE 1.9s

#2 [internal] load metadata for registry.fedoraproject.org/fedora:rawhide
#2 DONE 0.3s

#3 [1/3] FROM registry.fedoraproject.org/fedora:rawhide@sha256:8f8b7cec3366a3b8eec2985145c88642456adff5d08b8bf94043d01ae675f59b
#3 resolve registry.fedoraproject.org/fedora:rawhide@sha256:8f8b7cec3366a3b8eec2985145c88642456adff5d08b8bf94043d01ae675f59b done
#3 sha256:36df31986e2db5c6574c46349cc88d27ecf29f1e228fa40eccce7f84fd9d40fd 19.92MB / 64.27MB 0.2s
#3 sha256:36df31986e2db5c6574c46349cc88d27ecf29f1e228fa40eccce7f84fd9d40fd 48.23MB / 64.27MB 0.3s
#3 sha256:36df31986e2db5c6574c46349cc88d27ecf29f1e228fa40eccce7f84fd9d40fd 64.27MB / 64.27MB 0.5s
#3 sha256:36df31986e2db5c6574c46349cc88d27ecf29f1e228fa40eccce7f84fd9d40fd 64.27MB / 64.27MB 0.7s done
#3 extracting sha256:36df31986e2db5c6574c46349cc88d27ecf29f1e228fa40eccce7f84fd9d40fd
#3 extracting sha256:36df31986e2db5c6574c46349cc88d27ecf29f1e228fa40eccce7f84fd9d40fd 2.2s done
#3 DONE 2.9s

#4 [2/3] RUN echo 'export DRACUT_NO_XATTR=1 KVERSION=$(cd /lib/modules; ls -1 | tail -1)' > /etc/profile.d/dracut-test.sh
#4 DONE 1.0s

#5 [3/3] RUN dnf -y install --setopt=install_weak_deps=False     dash     pigz     asciidoc     mdadm     lvm2     dmraid     cryptsetup     nfs-utils     nbd     dhcp-server     scsi-target-utils     iscsi-initiator-utils     strace     btrfs-progs     kmod-devel     gcc     bzip2     xz     tar     wget     rpm-build     make     git     bash-completion     sudo     kernel     dhcp-client     /usr/bin/qemu-kvm     /usr/bin/qemu-system-$(uname -i)     e2fsprogs     tcpdump     iproute     iputils     dbus-daemon     kbd     NetworkManager     python3-imgcreate     which     ShellCheck     shfmt     && dnf -y update && dnf clean all
#5 0.259 Fedora rawhide openh264 (From Cisco) - x86_64   0.0  B/s |   0  B     00:00    
#5 0.259 Errors during downloading metadata for repository 'fedora-cisco-openh264':
#5 0.259   - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-rawhide&arch=x86_64 [getaddrinfo() thread failed to start]
#5 0.260 Error: Failed to download metadata for repo 'fedora-cisco-openh264': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-rawhide&arch=x86_64 [getaddrinfo() thread failed to start]
#5 0.264 Fedora - Rawhide - Developmental packages for t 0.0  B/s |   0  B     00:00    
#5 0.264 Errors during downloading metadata for repository 'rawhide':
#5 0.264   - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64 [getaddrinfo() thread failed to start]
#5 0.266 Error: Failed to download metadata for repo 'rawhide': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64 [getaddrinfo() thread failed to start]

**Comment by haraldh** [comment]
That's a bug in github docker blocking libc thread creation with a new syscall.

**Comment by LaszloGombos** [comment]
It seems this is resolved now, I suggest to close this issue.

Here is a recent successful GH action run - https://github.com/dracutdevs/dracut/runs/5405122272?check_suite_focus=true
