### ISSUE TITLE
Security concerns with unconditionally adding all systemd-networkd configuration files

### ISSUE THREAD

**Issue by LaserEyess** [dracutdevs/dracut#1603]
**Describe the bug**
When using the `systemd-networkd` module, all files in `/etc/systemd/network/` are included in the image. This is the current intended behavior, but can be detrimental to security if you use a wireguard interface created by `systemd-networkd`. In particular, having this file unencrypted in the initrd exposes it to malicious actors in a system that, otherwise, would have the keys protected by FDE.

**Distribution used**
Arch Linux

**Dracut version**
055, but has been present since 054

**Init system**
systemd

**To Reproduce**
Use the `systemd-networkd` module.

**Expected behavior**
My private keys are not exposed in an unencrypted file. Either by conditionally removing some files from the initrd or by not including all of the files to begin with.

**Additional context**
In certain cases, I do not believe it is a good idea for the network in the initrd to be the same as the network as in a booted system. This is especially true with VPN interfaces but it may also be true with other ethernet or wireless devices.

Dracut does not have the ability to exclude or omit files from being unconditionally included when copied over in the module. So as far as I can tell, there are no workarounds to avoid this.

**Comment by johannbg** [comment]
If you dont want the wireguards keyfiles to be included, place your keys to what you consider secure location on your filesystem and adjust the *KeyFile= paths in wireguards .netdev to point to that location.
