### ISSUE TITLE
nm-run.sh: /sys/class/net/bonding_masters/ifindex: Not a directory

### ISSUE THREAD

**Issue by glennmorris** [dracutdevs/dracut#1604]
Hi,

When trying to set up a network bond using dracut in RHEL8.4, I see the (harmless) error:

> dracut-initqueue: cat: /sys/class/net/bonding_masters/ifindex: Not a directory

By inspection, it looks like this will still happen with the latest version of dracut.
I think the following change would improve this:

```
--- a/modules.d/35network-manager/nm-run.sh
+++ b/modules.d/35network-manager/nm-run.sh
@@ -60,6 +60,7 @@ dhcpopts_create() {
 }
 
 for _i in /sys/class/net/*; do
+    [ -d "$_i" ] || continue
     state="/run/NetworkManager/devices/$(cat "$_i"/ifindex)"
     grep -q '^connection-uuid=' "$state" 2> /dev/null || continue
     ifname="${_i##*/}"
```

Thanks!

**Comment by sandrobonazzola** [comment]
Saw this on CentOS Stream 9 too

**Comment by johannbg** [comment]
@glennmorris can you make a PR with your suggested change?
