### ISSUE TITLE
rngd not included in OpenRC systems

### ISSUE THREAD

**Issue by peterlobster** [dracutdevs/dracut#1610]
**Describe the bug**
`rngd` is not included in the images generated by `dracut` when system is using OpenRC. `rngd` is required to solve the `random: init crng done` issue. (https://forums.gentoo.org/viewtopic-t-1081710-start-0.html).

**Distribution used**
Gentoo

**Dracut version**
053-r1

**Init system**
OpenRC

**To Reproduce**
- Install Gentoo with OpenRC
- Install `sys-apps/rng-tools` and `sys-kernel/dracut`
- Generate image with `$ dracut --host-only`

**Expected behavior**
Solve the `random: init crng done` issue

**Comment by LaszloGombos** [comment]
@peterlobster Would you be able to confirm the following is a workaround ?

`$ dracut --host-only --install /usr/sbin/rngd`

**Comment by peterlobster** [comment]
> Would you be able to confirm the following is a workaround ?

@LaszloGombos Sorry for the long absence in my response. Yes, that does seem like it would be a valid workaround.
