### ISSUE TITLE
dracut-initramfs-restore fails if kernel+initrd are located in /boot/Default instead of /boot/${MACHINE_ID}

### ISSUE THREAD

**Issue by steffenweber** [dracutdevs/dracut#1628]
**Describe the bug**
During shutdown, the following error is logged: `dracut-initramfs-restore[1234]: No initramfs image found to restore!`

**Distribution used**
Gentoo Linux

**Dracut version**
dracut 055

**Init system**
systemd 249

**To Reproduce**
The systemd script [kernel-install](https://github.com/systemd/systemd/blob/v249/src/kernel-install/kernel-install) prefers the directory `/boot/Default` (if it exists) over `/boot/${MACHINE_ID}`. The script [dracut-initramfs-restore.sh](https://github.com/dracutdevs/dracut/blob/master/dracut-initramfs-restore.sh) doesn't seem to know about this location and therefore fails to find the initrd file during shutdown.

**Expected behavior**
The script should find the initrd location and the error message should go away.

**Additional context**
See https://github.com/systemd/systemd/pull/16777 for details on the `/boot/Default` directory.

**Comment by johannbg** [comment]
@steffenweber could you confirm or deny that PR #1634 fixes things for you?

**Comment by steffenweber** [comment]
I can confirm that the patch fixes the issue. Thank you!
