### ISSUE TITLE
emergency mode by raid1(mdadm) mount failed

### ISSUE THREAD

**Issue by maurelreyes** [dracutdevs/dracut#1639]
**Describe the bug**
show dracut-initqueue timeout, still waiting for following initqueue hook 

**Distribution used**
Opensuse Tumbleweed

**Dracut version**
055+suse.110.gbe35f166-1.

**Additional context**

![20211111_112643](https://user-images.githubusercontent.com/17351630/141344661-756af86d-ad44-435c-a612-b75816159697.jpg)

**Comment by aafeijoo-suse** [comment]
This bug was reported [downstream](https://bugzilla.suse.com/show_bug.cgi?id=1192665) and also fixed [upstream](https://github.com/dracutdevs/dracut/pull/1633), so this issue can be closed.
