### ISSUE TITLE
systemd-resolve user missing

### ISSUE THREAD

**Issue by Cornelicorn** [dracutdevs/dracut#1656]
**Describe the bug**
When adding the `systemd-resolved` module, the service will not start correctly as the `systemd-resolve` user is missing. This user is used by the service since [v235](https://github.com/systemd/systemd/commit/635f3df5dc540892cca0b9d4ba42ab7215277f7c).

**Distribution used**
Arch rolling

**Dracut version**
dracut 055

**Init system**
systemd 249.7-1-arch

**To Reproduce**
Call dracut with `--add systemd-resolved` and reboot

**Expected behavior**
The service should start

**Additional context**

**Comment by johannbg** [comment]
This is due to https://github.com/systemd/systemd/pull/20056

**Comment by Cornelicorn** [comment]
> This is due to [systemd/systemd#20056](https://github.com/systemd/systemd/pull/20056)

This has not been released yet, as far as I can tell.

I think I found the culprit, `systemd-sysusers.service` contains `ConditionNeedsUpdate=/etc`. This will cause the unit to not start, seemingly since it cannot find `/etc/.updated`. [The docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionNeedsUpdate=) for that condition give a kernel commandline parameter to override this Condition Check. If I add `systemd.condition-needs-update=true`, `systemd-sysusers.service` runs and `systemd-resolved` starts without a problem.

I also found [a news entry](https://github.com/systemd/systemd/blob/main/NEWS#L1066#L1067) from systemd mentioning that this Condition will cause units not to be executed in initrd's anymore.

So this seems like a larger issue of `systemd-sysusers` not running anymore.

**Comment by Cornelicorn** [comment]
[The corresponding check](https://github.com/systemd/systemd/blob/a4e27f051a0d8e47a9927421d8e6a5234fef924d/src/shared/condition.c#L733#L736).

**Comment by johannbg** [comment]
That's an interesting [PR](https://github.com/systemd/systemd/commit/294eace024b0e6c34cb64e3bb4f8958bb98ee00b) which is seemingly based on misconception or total disregard for some of the usecases initrd are used for and basically means we need to start shipping our own type units for the initrd for systemd upstream units ( or overide snippets for them ).

**Comment by Cornelicorn** [comment]
For the override snippet, it would be enough to install
```
[Unit]
ConditionNeedsUpdate=
```
to `$systemdsystemunitdir/systemd-sysusers.service.d/sysusers-initrd.conf` from `modules.d/01systemd-resolved/module-setup.sh`.

I successfully tested this locally.

I can open a PR for this change if you want.

**Comment by johannbg** [comment]
Yeah sure and it's probably better to have dracut in the unit file name to make it clear that this unit came from dracut ( as opposed to initrd since there are multiple initrd solutions in the wild ) but in the end of the day I dont think we can avoid having to start shipping a full blown systemd units for modules since there are limitation what can be overridden using snippets. + we need to file a upstream bug about this.
