### ISSUE TITLE
Dracut stuck in loop for minutes

### ISSUE THREAD

**Issue by lehitoskin** [dracutdevs/dracut#167]
I have dracut set up to unlock a LUKS root drive by passphrase on boot - which it does just fine. Immediately after unlocking the root drive, it appears to hang for a few minutes before deciding it wants to get on with the rest of the boot process. I dropped into a shell and checked out the debugging information (pasted here: https://gist.github.com/749adbf0e908645bc6771cc41148bc5e) and it appears that `check_finished` (from `dracut-lib.sh`) is being run many, many times and doing the exact same operation.

I can't make heads or tails of this problem myself. Is it a problem with `dracut-lib.sh` or something? My cmdline is pretty sparse, I don't know what else I could do.

**Comment by haraldh** [comment]
try to remove "resume=/dev/mapper/swap" from the kernel command line

**Comment by lehitoskin** [comment]
Ah, that worked, thanks! Makes sense it wouldn't do well when /dev/mapper/swap hasn't been created yet.
