### ISSUE TITLE
dracut-cpio extracts device maj/min incorrectly

### ISSUE THREAD

**Issue by ethanwu10** [dracutdevs/dracut#1695]
**Describe the bug**
`dracut-cpio`'s code to extract `major` and `minor` from a `dev_t` (obtained from `std::os::unix::fs::MetadataExt.rdev()`) is incorrect:
https://github.com/dracutdevs/dracut/blob/fe8df0240a24b9d2d60a5b0b998f82b251ede849/src/dracut-cpio/src/main.rs#L365-L366

The correct structure is:
https://github.com/bminor/glibc/blob/5b8e7980c5dabd9aaefeba4f0208baa8cf7653ee/bits/sysmacros.h#L26-L34
https://github.com/nix-rust/nix/blob/5cd01a1fd7417ee6e16636443965c0a197ff2843/src/sys/stat.rs#L72-L93

**Comment by aafeijoo-suse** [comment]
ICYMI @ddiss

**Comment by ddiss** [comment]
Thanks for the report. I'll take a look and add some extra unit test coverage for this.
