### ISSUE TITLE
where should nfsroot_to_var() be defined?

### ISSUE THREAD

**Issue by jcflack** [dracutdevs/dracut#17]
It is defined in dracut-lib.sh and in 95nfs/nfs-lib.sh. The definitions are identical.

It's _used_ in 95nfs/nfs-lib.sh and in 95nfs/parse-nfsroot.sh, but the latter only sources dracut-lib, not nfs-lib.

Commit 9fcfa04c updated 95nfs/nfsroot.sh to source and use nfs-lib.sh, but it doesn't seem that was ever done to 95nfs/parse-nfsroot.sh. Was it supposed to be? That would allow the copy of nfsroot_to_var() in dracut-lib to be removed, I assume, in favor of the one in nfs-lib where it seems most at home.

**Comment by danimo** [comment]
@jcflack I guess you are not pursuing this anymore? I created a proposed fix.
