### ISSUE TITLE
tpm2-tss does not create tss user and group

### ISSUE THREAD

**Issue by Tatsh** [dracutdevs/dracut#1700]
**Describe the bug**
On boot before switching to real root, errors (`journalctl -p3`) regarding the tss user normally in `/etc/passwd` are reported:

```
systemd-tmpfiles[421]: /usr/lib/tmpfiles.d/tpm2-tss-fapi.conf:2: Failed to resolve user 'tss': No such process
systemd-tmpfiles[421]: Failed to parse ACL "default:group:tss:rwx": Invalid argument. Ignoring
systemd-tmpfiles[421]: /usr/lib/tmpfiles.d/tpm2-tss-fapi.conf:4: Failed to resolve user 'tss': No such process
systemd-tmpfiles[421]: Failed to parse ACL "default:group:tss:rwx": Invalid argument. Ignoring
systemd-udevd[489]: /lib/udev/rules.d/60-tpm-udev.rules:3 Unknown user 'tss', ignoring
systemd-udevd[489]: /lib/udev/rules.d/60-tpm-udev.rules:4 Unknown user 'tss', ignoring
systemd-udevd[489]: /lib/udev/rules.d/60-tpm-udev.rules:4 Unknown group 'tss', ignoring
```

**Distribution used**
Gentoo

**Dracut version**
055

**Init system**
systemd

**To Reproduce**
1. Install tpm2-tools
2. Enable kernel support for TPM 2
2. `dracut -a 'systemd tpm2-tss' --force`

**Expected behavior**
Should not have this error. The `tss` user maybe should be in the initrd (easiest way to solve this).

**Additional context**
`/etc/passwd` and `/etc/group` in the initrd do not list the `tss` user/group.

```
 $ cat $EXTPATH/etc/passwd
adm:x:3:4:adm:/var/adm:/bin/false
systemd-network:x:111:116:System user; systemd-network:/dev/null:/sbin/nologin
root:x:0:0::/root:/bin/sh
nobody:x:65534:65534:System user; nobody:/var/empty:/sbin/nologin
 $ cat $EXTPATH/etc/group
systemd-journal:x:121:
wheel:x:10:tatsh
adm:x:4:adm,daemon
utmp:x:406:
root:x:0:
systemd-network:x:116:
tty:x:5:tatsh
dialout:x:998:
kmem:x:9:
input:x:249:tatsh
video:x:27:tatsh,sddm
render:x:985:
sgx:x:405:
audio:x:18:tatsh
lp:x:7:lp,tatsh
disk:x:6:adm
cdrom:x:991:tatsh
tape:x:26:
kvm:x:78:
floppy:x:11:
```

**Comment by johannbg** [comment]
The fix for this has already been merged hence closing

**Comment by victor-timofei** [comment]
It seems this is not fixed, I am still getting this error on gentoo in version 059

**Comment by victor-timofei** [comment]
The way I understand this, is that users/groups are supposed to be created with `systemd-sysusers`.
While the `tmp2-tss` module depends on the `systemd-sysusers` module, I couldn't find any configuration `SYSUSERS.D(5)` being installed by any module.

I did inspect the initramfs contents with `lsinitrd` and couldn't find any configuration files:
 - `/etc/sysusers.d/*.conf`
 - `/run/sysusers.d/*.conf`
 - `/usr/lib/sysusers.d/*.conf`

Am I missing something?

My dracut config is:
```
add_dracutmodules+=" systemd systemd-sysusers crypt dm rootfs-block btrfs tpm2-tss clevis-pin-sss clevis-pin-tpm2 clevis "
```

Should I just create a custom modules that loads a `SYSUSERS.D(5)` configuration for tss user/group?

**Comment by Tatsh** [comment]
@victor-timofei From what I can tell the issue is that `acct-user/tss` does *not* create the file expected which is `/usr/lib/sysusers.d/tpm2-tss.conf`. OpenSuse installs this file thought it does not use the distributed file from tpm2-tss. It seems on there the file has both the `u` and the `g` line.

On Gentoo, the files are `/usr/lib/sysusers.d/acct-user-tss.conf` and `/usr/lib/sysusers.d/acct-group-tss.conf`.

**Comment by Tatsh** [comment]
@victor-timofei please follow here: https://bugs.gentoo.org/925524
