### ISSUE TITLE
What invokes /sbin/netroot when using systemd-networkd?

### ISSUE THREAD

**Issue by BtbN** [dracutdevs/dracut#1706]
I'm maintaining a custom netroot module, and after a recent distro-update of dracut, it broke.
After some investigation, I concluded that it was broken by network-legacy no longer being pulled in by default, but systemd-networkd instead.
And indeed, adding network-legacy to the dracut modules manually fixes it, and makes stuff work as expected again.

What happens is that systemd-networkd successfully gets an IP via DHCP, but never calls /sbin/netroot, which is what'd call /sbin/${handler}root in turn.
So it just sits there, infinitely waiting for the rootfs to be mounted, until the initqueue eventually times out.

I've modeled my module after the cifs/nfs/nbd modules, which all also seem to rely on /sbin/${handler}root being called by /sbin/netroot.
But I don't see what calls /sbin/netroot when systemd-networkd is being used, and given my initqueue gets stuck, it seems like nothing actually does.

I don't have a setup to test if the other netroot modules would work, but I suspect they'd suffer from the same issue?
Or am I missing something in my module, to ensure it actually kicks into action with networkd?

**Comment by BtbN** [comment]
The issue/question very much still stands.

**Comment by TheJJ** [comment]
no bot, i'm sorry

**Comment by BtbN** [comment]
Still not, nope.

**Comment by BtbN** [comment]
Nope

**Comment by BtbN** [comment]
Well, the question and issue very much still stands.
