### ISSUE TITLE
systemd-cryptsetup-generator does not work correctly with /etc/cmdline.d/01-default.conf (dracut-initqueue[479]: failed to start systemd-cryptsetup@luks-a4465013-c35b-4378-ae5f-c2bb7712b89e.service: Unit systemd-cryptsetup@luks-a4465013-c35b-4378-ae5f-c2bb7712b89e.service not found.)

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [dracutdevs/dracut#1754]
**Describe the bug**
On a bios system (VM): i get
```
dracut-initqueue[479]: failed to start systemd-cryptsetup@luks-a4465013-c35b-4378-ae5f-c2bb7712b89e.service: Unit systemd-cryptsetup@luks-a4465013-c35b-4378-ae5f-c2bb7712b89e.service not found.
```
In the maintenance shell I can just call
```
/lib/systemd/systemd-decrypt attach a /dev/disk/by-uuid/4e56edf6-3e8a-4ef3-a084-09b40468bd89
```
and exit the shell - the boot continues

**Distribution used**
Archlinux

**Dracut version**
```
dracut --version
dracut 056
```

**Init system**
Which init system is being used?

**To Reproduce**
The dracut confs commandline
```
lsinitrd /boot/initramfs-linux.img -f etc/cmdline.d/01-default.conf
rw rd.info rd.shell rd.luks.timeout=30 rd.luks.crypttab=no rd.luks.uuid=4e56edf6-3e8a-4ef3-a084-09b40468bd89 root=UUID=a4465013-c35b-4378-ae5f-c2bb7712b89e rootflags=subvol=/@/0/snapshot zswap.enabled=1 zswap.compressor=zstd zswap.zpool=z3fold rd.md=0 rd.lvm=0 rd.multipath=0 rd.fcoe=0 rd.neednet=1 ip=dhcp resume=UUID=a4465013-c35b-4378-ae5f-c2bb7712b89e resume_offset=1268624
```

**Expected behavior**
When I switch to UEFI (`uefi=yes` and `uefi_stub=...`) it works - the password is asked, no timeout happens

**Additional context**
Add any other context you like about the problem here.

**Comment by T35R6braPwgDJKq** [comment]
does anybody know how to tackle this? Booting takes 5 minutes that way

**Comment by tacerus** [comment]
The `cryptsetup@` systemd unit should be started in the format `cryptsetup@<mapper name>` - or is `luks-xxxxxxx` what you use as a LUKS volume mapper name?

Did you try rebuilding the initramfs (using the `dracut` tool)? The crypt module should populate the cmdline with the correct UUIDs for mounted LUKS volumes.

**Comment by T35R6braPwgDJKq** [comment]
my luks mapper name is `root`
yes i did (`dracut -f /boot/linux-initramfs.img`) - the UUIDs were and are correct (in `dracut.conf` as well as in dracut output) - the UUID being searched for is correct as well. Its like dracut wouldnt know that the root uuid is only available after decryption hence ignoring `rd.luks.uuid` altogether

the question is not related to the problem but there are still systems without EFI... I built the image obviously in an non-UEFI environment. Just for testing purposes I switched the VM to EFI and rebuilt the image.

**Comment by tacerus** [comment]
> `--no-hostonly-cmdline` nor `--no-hostonly` nor `--no-hostonly-cmdline --no-hostonly` work either

`hostonly` is a requirement for the module to build `/etc/crypttab`.

`rd.luks.uuid=` should be appended automatically.

**Comment by T35R6braPwgDJKq** [comment]
well the crypttab should be empty - only the root device is mentioned but as kernel parameter, but it doesnt really matter since I also tried an image without those arguments.

`rd.luks.uuid` is appended to `/etc/cmdline.d/01-default.conf` - but from there it is ignored.

It should NOT be added to the bootloader automatically. That is just my ugly workaround.

**Comment by dtardon** [comment]
> **Describe the bug** On a bios system (VM): i get
> 
> ```
> dracut-initqueue[479]: failed to start systemd-cryptsetup@luks-a4465013-c35b-4378-ae5f-c2bb7712b89e.service: Unit systemd-cryptsetup@luks-a4465013-c35b-4378-ae5f-c2bb7712b89e.service not found.
>```

This unit is supposed to be generated (from `/etc/crypttab`) by `systemd-cryptsetup-generator`. The problem is that the generator only generates units if it sees `luks` or--in our case--`rd.luks` on the kernel command line and systemd only reads `/proc/cmdline`. IOW, there's nothing dracut can do here; your best bet is to open an issue at  https://github.com/systemd/systemd, asking for systemd to look at `/etc/cmdline` and `/etc/cmdline.d/*.conf` too.

**Comment by T35R6braPwgDJKq** [comment]
thank you very much. that makes sense

**Comment by bbaserdem** [comment]
> The problem is that the generator only generates units if it sees `luks` or--in our case--`rd.luks` on the kernel command line and systemd only reads `/proc/cmdline`. IOW, there's nothing dracut can do here

In the discussion;  `/etc/kernel/cmdline` is read as well; so the correct thing on dracut when it's using systemd for init would be to put commandline arguments there.
