### ISSUE TITLE
/usr/bin/dracut: line 1030: dfatal: command not found

### ISSUE THREAD

**Issue by mangoducksparkles** [dracutdevs/dracut#1758]
**Describe the bug**
When using dracut to create a signed UEFI image without `sbsign` installed, it fails with an unhelpful message: `/usr/bin/dracut: line 1030: dfatal: command not found`

**Distribution used**
Arch Linux

**Dracut version**
056-1

**Init system**
unsure

**To Reproduce**
On a fresh install with `sbctl`, but _not_ `sbsign`:
```
# sbctl create-keys
# imgs=($(sbctl verify | gawk '/^\W+efi/{print $2}'))
# for img in $imgs
# do
# sbctl sign -s $img
# done
# tee /etc/dracut.conf.d/secureboot.conf <<- eof
uefi_secureboot_cert="/usr/share/secureboot/keys/db/db.pem"
uefi_secureboot_key="/usr/share/secureboot/keys/db/db.key"
eof
# dracut -f --uefi --regenerate-all --early-microcode
```

**Expected behavior**
`dracut` should exit with a helpful message, such as the one found on line `1030`: "Need 'sbsign' to create a signed UEFI executable"

**Additional context**
On line `1030`, as well as at various other points in `/usr/bin/dracut`, there is a call to `dfatal` followed by a helpful error message. I do not know what `dfatal` is, and could not find any references to it online. Perhaps it is a typo? Or a dependency that isn't automatically installed with the `dracut` package?

**Comment by tacerus** [comment]
It's an internal logging function, not an external binary.
With a packaged installation it should be defined in `/usr/lib/dracut/dracut-logger.sh`. Does setting a loglevel using `-L` change anything?

**Comment by mangoducksparkles** [comment]
Nope. I tried each of `-L 0` through `-L 6` and got the same result each time.
Also, I checked `/usr/lib/dracut/dracut-logger.sh` and grep says `dfatal` is in there.

**Comment by tacerus** [comment]
It might be an issue with your distribution package as I cannot reproduce it. Maybe consider opening a bug there?

**Comment by mangoducksparkles** [comment]
Thanks, will do.

**Comment by deimosian** [comment]
Just in case anyone else runs unto this exact error but is otherwise stumped when googling, I experienced it and the underlying issue throwing the error which was trying to call `dfatal` was that the sbsigntools package was not installed to provide `sbsign`.
