### ISSUE TITLE
/usr/lib/dracut/dracut-functions.sh: line 1588: 3w_9xxx: value too great for base

### ISSUE THREAD

**Issue by gonzzor** [dracutdevs/dracut#179]
Trying to run master (be27ef2cbc9c810de3d0c338924ec7a0eccc45fe) branch on a Fedora 23 machine.

```
$ sudo ./dracut.sh -M --kver 4.7.10-100.fc23.x86_64 --force 
bash
systemd
systemd-initrd
nss-softokn
i18n
network
ifcfg
drm
plymouth
btrfs
crypt
dm
kernel-modules
/usr/lib/dracut/dracut-functions.sh: line 1588: 3w_9xxx: value too great for base (error token is "3w_9xxx")
kernel-network-modules
/usr/lib/dracut/dracut-functions.sh: line 1588: 3c589_cs: value too great for base (error token is "3c589_cs")
/usr/lib/dracut/dracut-functions.sh: line 1588: 8021q: value too great for base (error token is "8021q")
installkernel failed in module kernel-network-modules
```

Bisected this issue to commit 3f60444ec1bff8a57a2cf4ada238e782928890eb (removed obsolete kernel module functions and host_modules variable).

I haven't looked into this more than that. I'll just stick with the revision that works for the moment and will upgrade the machine soon anyway.

**Comment by haraldh** [comment]
If you want to run a local version in ./ you have to add the "--local" option:

$ sudo ./dracut.sh --local -M --kver 4.7.10-100.fc23.x86_64 --force

**Comment by haraldh** [comment]
-l, --local           Local mode. Use modules from the current working
                         directory instead of the system-wide installed in
                         /usr/lib/dracut/modules.d.

**Comment by gonzzor** [comment]
So simple, thanks. It works.
