### ISSUE TITLE
Darcut found a fuzzy match when using the parameter --omit-drivers

### ISSUE THREAD

**Issue by zhrf2020** [dracutdevs/dracut#1793]
**Describe the bug**
darcut found a fuzzy match when using the parameter --omit-drivers

**Distribution used**
darcut  --omit-drivers " aaxx "    
At this point, there is a module (ko) on the system: aaxxwwcc.ko , this module will also be removed synchronously, because **aaxxwwcc** contains the characters **aaxx**

**Dracut version**
latest version

**Init system**
linux OS , eg: centos

**To Reproduce**
none

**Expected behavior**
Run: darcut  --omit-drivers " aaxx "   
At this point there is a module (ko) on the system: aaxxwwcc.ko , this module( aaxxwwcc.ko) will not be removed synchronously, only aaxx.ko will be removed

**Additional context**
I suspect that similar regular matching is done in the code, such as a wildcard: *aaxx* operation, I have not found the abnormal code so far, I will continue to work hard to analyze ......
At the same time, I hope the master can give guidance,thanks very much.

**Comment by cheese** [comment]
This is an annoying regression. `omit-drivers` option is expected to be names of modules. And it works as expected on CentOS 7 (dracut-033-554.el7.x86_64).

But on CentOS 9 (dracut-055-30.git20220216.el9.x86_64), `omit-drivers` is found actually interpreted as regexp. Dracut may omit more than one module when given only one `omit-drivers` option.

**To Reproduce**

0. Run a CentOS 9 system with an `ext4` `/boot`
1. Install a kernel with `ext4`, `mbache` and `bache` built as modules. (`ext4` depends on `mbcache`.)
2. `dracut --omit-drivers bcache /tmp/initramfs`
3. Check `ext4` in initramfs: `lsinitrd /tmp/initramfs |grep ext4`
4. Check both `mbcache` and `bcache` not in initramfs: `lsinitrd /tmp/initramfs |grep bcache`
	* Expected `mbcache` is in initramfs and `bcache` is not

**Comment by LaszloGombos** [comment]
Commit introducing this functionality in dracut-install (in 2015)

https://github.com/dracutdevs/dracut/commit/794b2d2c753489635b922457a5ccb06669f37268

**Comment by LaszloGombos** [comment]
@champtar @cheese @zhrf2020 - would you be able to test the following one line change locally to verify if this works in your environment ? 

https://github.com/dracutdevs/dracut/pull/1947/commits/ceae1339064adf55be3074c117706ebb60f75aab#diff-99bfb8fe311d6a59318f685a5e3401b59293b577968aa08cc4ff7320a163bb28L1348

**Comment by champtar** [comment]
I think `^(a|b)$` is equivalent to `^a$|^b$`, but your change works (tm).
Side note when using configuration file, we don't have the '-' to '_' substitution, so some kmods are not excluded, don't know if you want to fix it in this PR.
