### ISSUE TITLE
Module 'resume' not found but installed

### ISSUE THREAD

**Issue by AVAtarMod** [dracutdevs/dracut#1802]
**Describe the bug**
I forced dracut to add module 'resume' (by `add_dracutmodules+=" resume "` in /etc/dracut.conf.d/99-confname.conf), but it cannot build any initrd at all with message `dracut: dracut module 'resume' cannot be found or installed.`
But dracut module is exist:
```
$ ls -l /usr/lib/dracut/modules.d/95resume
total 12
-rwxr-xr-x 1 root root 3208 Apr 12 13:43 module-setup.sh
-rwxr-xr-x 1 root root 3413 Apr 12 13:43 parse-resume.sh
-rwxr-xr-x 1 root root  434 Apr 12 13:43 resume.sh
```
This is very strange, and because of this hibernation stopped work.

**Distribution used**
OpenSUSE Tumbleweed

**Dracut version**
dracut 056+suse.268.g0b2bd662-1.1

**Init system**
systemd 250 (250.4+suse.54.g736db5a59f)

**To Reproduce**
```

1. echo 'add_dracutmodules+=" resume "' | sudo tee /etc/dracut.conf.d/99-confname.conf
2. sudo dracut --regenerate-all --force
3. echo $? (prints 2)

```

**Expected behavior**
Dracut include module 'resume' in initrd.

**Comment by dtardon** [comment]
> I forced dracut to add module 'resume' (by `add_dracutmodules+=" resume "` in /etc/dracut.conf.d/99-confname.conf), but it cannot build any initrd at all with message `dracut: dracut module 'resume' cannot be found or installed.`
But dracut module is exist:

Which means that the "or installed" part of the message applies. Most likely the module is missing a dependency; passing `-v` to `dracut` should tell you more. In any case, I doubt this is an actual bug in dracut.

**Comment by AVAtarMod** [comment]
> Which means that the "or installed" part 
of the message applies. Most likely the module is missing a dependency; passing `-v` to `dracut` should tell you more.

Thanks for the attention to this issue!
I run `sudo dracut --regenerate-all --force --force-add resume --verbose --debug > dracut.log 2>&1` 
I attached log below, looks like dracut can't find my encrypted swap device (which mounted at boot):
```
NAME      TYPE      SIZE USED PRIO
/dev/dm-0 partition  10G 2.8M   -2
```
Useful information start at 8471 line. At 8506 module is doing return with error, because of there is no a swap devices.
[dracut.log](https://github.com/dracutdevs/dracut/files/8602441/dracut.log)

**Comment by AVAtarMod** [comment]
Why is dracut can't find out any swap device? About two weeks ago dracut worked as expected.

**Comment by johannbg** [comment]
We have not made any release for a long time, too long time actually
@aafeijoo-suse any changes you have made in OpenSuse for the past ca 2 weeks that might have broken this for him?

**Comment by aafeijoo-suse** [comment]
Yes, this was an openSUSE Tumbleweed specific issue, which should be solved in dracut-056+suse.275.g4ce7a6a7, so please, @AVAtarMod update your system. Next time you find a bug, report it first in https://bugzilla.opensuse.org, to avoid unnecessary noise here. Thanks!

**Comment by AVAtarMod** [comment]
Thanks for good news!
