### ISSUE TITLE
CI on debian is not yet passing

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#1805]
Running GitHub Action tests on Debian does not yet succeed.  

This is likely an issue with the CI setup and not with the dracut application itself. The intent of this bug report is to acknowledge the CI failure and collaborate on the solution (and not to suggest that dracut itself has some issues).

The error message:

> [  OK  ] Reached target Switch Root.
>          Starting Switch Root...
> [FAILED] Failed to start Switch Root.

Link to a recent run: https://github.com/dracutdevs/dracut/runs/6281914684

**Comment by johannbg** [comment]
"Can't install systemd base" comes from [TEST-04-FULL-SYSTEMD/test.sh](https://github.com/dracutdevs/dracut/blob/79170aafba9ba1a852ffb2fdcc8277d216056671/test/TEST-04-FULL-SYSTEMD/test.sh) we probably needs some elif statements involving dpkg there ( L83 ) we have one for rpm and packman but not dpkg?

**Comment by johannbg** [comment]
There can be dragons in other test cases as well which we will need to adjust for Debian.

**Comment by LaszloGombos** [comment]
Thanks @johannbg for the great hint. PR https://github.com/dracutdevs/dracut/pull/1806 .

**Comment by johannbg** [comment]
Merged hence closing
