### ISSUE TITLE
Add `uefi="yes"` to `dracut.conf` man page

### ISSUE THREAD

**Issue by Winterhuman** [dracutdevs/dracut#1818]
It'd be nice to be able to set `uefi="yes"` so that running `dracut` always defaults to `--uefi`.

**Comment by aafeijoo-suse** [comment]
This already works.

**Comment by Winterhuman** [comment]
It does? I don't see any mention of a `uefi` option in the man pages for `dracut.conf`, I might need to change the issue to adding mentions of it in the docs if this is the case already

**Comment by aafeijoo-suse** [comment]
> It isn't mentioned in the `dracut.conf` man page though

Recently added in #1815

**Comment by Winterhuman** [comment]
Ah, hadn't thought to check pull requests. Thanks! Closing issue
