### ISSUE TITLE
command line in --uefi mode prefixed by whitespace?

### ISSUE THREAD

**Issue by poettering** [dracutdevs/dracut#189]
I noticed that "dracut --uefi --kernel-cmdline …" will always result in a kernel command line embedded in the resulting image prefixed by a single space character. This doesn't break anything, but is a tiny bit ugly...

```
# rpm -qf /usr/bin/dracut
dracut-044-78.fc25.x86_64
```

**Comment by haraldh** [comment]
There was a bug in the uefi loader, which required this quirk
