### ISSUE TITLE
70-uaccess.rules seems to require /lib64/elogind/elogind-uaccess-command

### ISSUE THREAD

**Issue by amano-kenji** [dracutdevs/dracut#1909]
**Describe the bug**

initramfs tries to execute /lib64/elogind/elogind-uaccess-command multiple times.
It seems 70-uaccess.rules requires /lib64/elogind/elogind-uaccess-command

Adding
```
install_items+=" /lib64/elogind/elogind-uaccess-command "
```
to /etc/dracut.conf works around the issue.

**Distribution used**

Gentoo Linux

**Dracut version**

057

**Init system**

OpenRC

**Comment by pvalena** [comment]
Can you post a log / reproducer?

**Comment by amano-kenji** [comment]
How can I do that?

**Comment by amano-kenji** [comment]
[70-uaccess.rules.txt](https://github.com/dracutdevs/dracut/files/10123209/70-uaccess.rules.txt)

Here.

**Comment by LaszloGombos** [comment]
> It seems 70-uaccess.rules requires /lib64/elogind/elogind-uaccess-command

@amano-kenji  Thanks for the file, but this file does not seem to have "elogin" mentioned in it.

**Comment by amano-kenji** [comment]
Yet, reality slapped me with the error message that /lib64/elogind/elogind-uaccess-command didn't exist in initramfs.

**Comment by johannbg** [comment]
Looks like a downstream issue hence closing

**Comment by amano-kenji** [comment]
I think 70-uaccess.rules is designed to trigger execution of /lib64/elogind/elogind-uaccess-command. This isn't an issue, but a design decision by logind.
