### ISSUE TITLE
Don't always use hard-coded ``/efi/EFI/Linux/`` directory for EFISTUB

### ISSUE THREAD

**Issue by conrad-heimbold** [dracutdevs/dracut#1926]
I'm using dracut and refind on Fedora and using the unified, signed EFI STUB generation. 
And Fedora already has / already created the directory ``/efi/EFI/Fedora`` on my EFI System Partition. 
So it would be nice if dracut could put the EFISTUB files into ``/efi/EFI/Fedora`` on Fedora and not into ``/efi/EFI/Linux``. 

[The lines 1125 and 1126 in dracut.sh](
https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1125): 
```
mkdir -p "$dracutsysrootdir$efidir/Linux"
outfile="$dracutsysrootdir$efidir/Linux/linux-$kernel${MACHINE_ID:+-${MACHINE_ID}}${BUILD_ID:+-${BUILD_ID}}.efi" 
```
... would have to be changed for that. 

dracut could just use the ``ID`` parameter in ``/etc/os-release`` (which is ``Fedora`` for Fedora and ``Arch`` for Arch Linux): 
```
source /etc/os-release 
distro=$ID
```

and check if the directory ``/efi/EFI/$distro/`` (``$dracutsysrootdir$efidir/$distro``) exists. 
If that directory exists, then don't use ``/efi/EFI/Linux`` (``$dracutsysrootdir$efidir/Linux``), 
but ``/efi/EFI/Fedora`` instead (``"$dracutsysrootdir$efidir/$distro``).

**Comment by conrad-heimbold** [comment]
Or even better: Allow the user to specify where the generated UEFI files will be placed, with an option in ``dracut.conf``. 
Like for example ``uefi_esp_outdir=/efi/EFI/Fedora``

**Comment by johannbg** [comment]
The spec is quite clear about the setup which is what we are supporting ( afaikt ) 
Downstream that wants to violate the spec file will need carry support for that violation themselves and or make changes to the spec itself hence closing.
