### ISSUE TITLE
--hostonly-i18n doesn't work as described in dracut(8)

### ISSUE THREAD

**Issue by jesa7955** [dracutdevs/dracut#195]
dracut(8) describes --hostonly-i18n and --no-hostonly-i18n as below, which I take as --hostonly-i18n is the default behavior of dracut when handling i18n files. But actually dracut installs all keyboard and font files when neither of these two options is specified (e.g. dracut foo.img).
> --hostonly-i18n: Install only needed keyboard and font files according to the host configuration (default).
>--no-hostonly-i18n: Install all keyboard and font files available.

**Comment by haraldh** [comment]
Yeah, it's the default, because people couldn't enter their password, if the keyboard layout is not included.
So, they at least have the chance to set the keyboard on the kernel command line.
It's a better safe than sorry approach.

**Comment by jesa7955** [comment]
So maybe we should change the wrong description in dracut(8), moving the "default" word to --no-hostonly-i18n.

**Comment by haraldh** [comment]
Well, the default (which is what the man page describes) is changed by the distribution specific configuration (at least in fedora)
$ fgrep i18n_install_all -r /usr/lib/dracut/dracut.conf.d/
/usr/lib/dracut/dracut.conf.d/01-dist.conf:i18n_install_all="yes"

**Comment by haraldh** [comment]
The manpage would have to be patched for the distribution changing the default (which I don't do right now in Fedora).
Maybe I should.
