### ISSUE TITLE
Drop .kateconfig from subdirectories

### ISSUE THREAD

**Issue by marcosfrm** [dracutdevs/dracut#1958]
https://docs.kde.org/trunk5/en/kate/katepart/config-variables.html

> Additionally, document variables can be placed in a file called .kateconfig in any directory, and the configured settings will be applied as if the modelines were entered on every file in the directory and its subdirectories.

Hence only the toplevel `.kateconfig` is required. `src/install/.kateconfig` and `src/skipcpio/.kateconfig` can go away.

**Comment by marcosfrm** [comment]
Hmm, config is different:

https://github.com/dracutdevs/dracut/blob/master/.kateconfig (tab-width 4; indent-width 4)
https://github.com/dracutdevs/dracut/blob/master/src/install/.kateconfig (tab-width 8; indent-width 8)
https://github.com/dracutdevs/dracut/blob/master/src/skipcpio/.kateconfig (tab-width 8; indent-width 8)

https://github.com/dracutdevs/dracut/blob/master/src/skipcpio/.dir-locals.el ???

**Comment by pvalena** [comment]
From .vimrc:
```

set tabstop=4
set shiftwidth=4
set expandtab
set makeprg=GCC_COLORS=\ make
set tw=79
au BufRead,BufNewFile *.xml set tw=109 shiftwidth=2 smarttab
au FileType sh set tw=80 shiftwidth=4 smarttab
au FileType c set tw=109 shiftwidth=8 tabstop=8 smarttab expandtab
```

So default 4, 4; but 8, 8 for C? That would actually make sense. Is it documented somewhere ?

**Comment by marcosfrm** [comment]
Not explicitly:
https://github.com/dracutdevs/dracut/blob/master/docs/HACKING.md#code-format

My following commit adjusts Kate config:
https://github.com/dracutdevs/dracut/pull/1959/commits/74169dc706e9310c8dc0378dffbfcb3b79b3b3cc
