### ISSUE TITLE
mount edit initrd.img imgae

### ISSUE THREAD

**Issue by HuckOps** [dracutdevs/dracut#1960]
when i use dracut to make a ramfs and want to edit that image, i should to mount this image and install some software,but i cant mount this image in my system. so, how can i mount and edit this image?

My system enviorment is centos 7.6

**Comment by LaszloGombos** [comment]
@HuckOps Please use discussions for questions not the issue tracker.

To answer your question here is one of the many documentations https://www.thegeekdiary.com/centos-rhel-7-how-to-extract-initramfs-image-and-editview-it/

**Comment by ddiss** [comment]
@HuckOps there's no kernel support for mounting a cpio archive and editing it in place. If you just want to add something to an initramfs image, you can do that by appending a new cpio archive (with the files you want to add) to the existing initramfs image.

Either way, this question isn't really relevant for Dracut, as I don't expect it to support partial initramfs updates.
