### ISSUE TITLE
057 not available from kernel.org

### ISSUE THREAD

**Issue by ffontaine** [dracutdevs/dracut#1981]
Is seems like the release tarball for 057 isn't available on kernel.org, can a tarball for 057 be added there?
I looked here https://mirrors.edge.kernel.org/pub/linux/utils/boot/dracut/, maybe it's available from a different location?

**Comment by marcosfrm** [comment]
See https://github.com/dracutdevs/dracut/issues/1850

**Comment by ffontaine** [comment]
Thanks, then I'm closing this PR.
