### ISSUE TITLE
90crypt shall install cryptsetup as dracut module systemd doesn't

### ISSUE THREAD

**Issue by copyrights** [dracutdevs/dracut#2005]
90crypt module doesn't install cryptsetup as condition on systemd module

https://github.com/dracutdevs/dracut/blob/a3c67d27e75223bb45df19f850d246ced9a09938/modules.d/90crypt/module-setup.sh#L99-L105

But systemd module doesn't install cryptsetup.

Is this an bug or isn't cryptsetup needed with systemd?

**Comment by LaszloGombos** [comment]
@copyrights Do you have systemd-cryptsetup ?

Note this line - https://github.com/dracutdevs/dracut/blob/master/modules.d/90crypt/module-setup.sh#L7

**Comment by copyrights** [comment]
yes, systemd-cryptsetup is installed.

**Comment by copyrights** [comment]
I think I had a wrong expectation (got clarified after I read #1023).  I was expecting to have cryptsetup installed for my usecase, but systemd-cryptsetup doesn't need cryptsetup.
