### ISSUE TITLE
Modsign does not put keys in correct keyring

### ISSUE THREAD

**Issue by webczat** [dracutdevs/dracut#2021]
**Describe the bug**
A clear and concise description of what the error is.
I assume 03modsign module is used to load keys which are to be used to verify loaded modules. I have a case where my MOK table contains a certificate authority, and modules are signed by the end entity certificate signed by that authority, yet I cannot load modules signed with the certificate even when certificate in question has been provided to modsign in /lib/modules/keys.
I have read the code of modsign module. I know module was included in initramfs and the key has been put in place, I do not get any errors in the boot process related to these keys. However the code of modsign, namely the hook which loads modules, contains this line:
```
    keyctl padd asymmetric "" @s < "${x}"
```
This line adds the key to keyring, but "@s" denotes a session keyring. Shouldn't this be changed to add to "%:.secondary_trusted_keys" instead?
Not sure what was the intention and it might be I just don't understand what 03modsign is supposed to do, however modifying this line so that keys are added into a secondary trusted keyring fixed the problem.

**Distribution used**
Which distribution was this behaviour seen in?
fedora37

**Dracut version**
Which dracut version was this behaviour seen in?
057

**Init system**
Which init system is being used?
systemd

**To Reproduce**
Steps or code to reproduce the behavior.
* have a ca certificate build into the kernel or loaded through a MOK table of shim.
* Have a leaf certificate and some modules (like akmods) signed with it, the leaf certificate must be issued by ca.
* Copy certificate to /lib/modules/keys, update initramfs and reboot.
* Try to load module.
* Module fails to load due to missing key

**Expected behavior**
Module should load

**Additional context**
Add any other context you like about the problem here.

**Comment by mikhailnov** [comment]
+1 for this, I tried to follow kernel docs https://www.kernel.org/doc/html/latest/admin-guide/module-signing.html which say about adding keys into `.builtin_trusted_keys`.  Also did not understand what this module tries to do, at least today it seems to make no sense.
