### ISSUE TITLE
Does dracut can support `podman` module easily.

### ISSUE THREAD

**Issue by Rtoax** [dracutdevs/dracut#2023]
I centos stream 9, `/usr/lib/dracut/modules.d/30ignition` dracut support `ignition`, can i write a `podman` module, i wonder that, podman has too many deps to fix.

What should i do for `podman` module?

**Comment by aafeijoo-suse** [comment]
See https://github.com/aaannz/dracut-iguana, they install podman.

**Comment by Rtoax** [comment]
Thanks, i'll learn it.

**Comment by johannbg** [comment]
Seems to be already resolved hence closing
