### ISSUE TITLE
/usr/bin/lsinitrd: line 366: zstd: command not found

### ISSUE THREAD

**Issue by FGrose** [dracutdevs/dracut#2034]
When running the following command with dracut 057-4.fc38 in Fedora-Workstation-Live-x86_64-Rawhide-20221103.n.0.iso
`$ sudo lsinitrd /run/initramfs/live/images/pxeboot/initrd.img -m`
I receive this output:
```
Image: /run/initramfs/live/images/pxeboot/initrd.img: 17M
========================================================================
/usr/bin/lsinitrd: line 366: zstd: command not found
Version: 

dracut modules:
/usr/bin/lsinitrd: line 187: zstd: command not found
========================================================================
```
When I chroot into Fedora 36, with dracut 057-3.fc36,  I receive the expected output:
`# lsinitrd run/initramfs/live/images/pxeboot/initrd.img -m`
```
Image: run/initramfs/live/images/pxeboot/initrd.img: 17M
========================================================================
Version: 

dracut modules:
dash
nss-softokn
i18n
btrfs
dm
dmsquash-live
kernel-modules
kernel-modules-extra
rootfs-block
terminfo
udev-rules
virtiofs
biosdevname
usrmount
base
fs-lib
img-lib
shutdown
========================================================================
```
The initrd.img was built in Fedora 36 with these arguments:
`# lsinitrd run/initramfs/live/images/pxeboot/initrd.img | grep Arguments:`
```
Arguments:  --kver '6.1.0-0.rc3.20221102git8f71a2b3f435.29.fc38.x86_64' --hostonly --nomdadmconf --nolvmconf --zstd --add 'dmsquash-live dash virtiofs' --omit 'plymouth bash network-manager network ifcfg cifs iscsi nfs dracut-systemd systemd systemd-initrd memstrack' --no-early-microcode --force --add-drivers 'f2fs overlay nvme' -M
```
and successfully boots.
(I've modified `../90dmsquash-live/module-setup.sh` to allow hostonly building.)
When building in Fedora 38 Rawhide, I receive this message:
`dracut: cannot execute compression command 'zstd', falling back to default`

**Comment by aafeijoo-suse** [comment]
This is a bug in Fedora, you should report it there. Here we cannot control which packages are included in each distribution that uses dracut.
