### ISSUE TITLE
/run/anaconda/initrd_errors.txt: No such file or directory

### ISSUE THREAD

**Issue by torkilt** [dracutdevs/dracut#2047]
**Describe the bug**
I'm failing to provision some ProLiant SL230s Gen8 systems with RHEL 9. I have a ticket for this with Red Hat support and opened a bugzilla (2138320) for it. 

The error Red Hat investigates is this:

"
[  321.521692] g75 dracut-initqueue[1371]: Warning: ############# Anaconda installer errors begin #############
[  321.521692] g75 dracut-initqueue[1371]: Warning: #                                                         #
[  321.521692] g75 dracut-initqueue[1371]: Warning: It seems that the boot has failed. Possible causes include
[  321.521692] g75 dracut-initqueue[1371]: Warning: missing inst.stage2 or inst.repo boot parameters on the
[  321.521692] g75 dracut-initqueue[1371]: Warning: kernel cmdline. Please verify that you have specified
[  321.521692] g75 dracut-initqueue[1371]: Warning: inst.stage2 or inst.repo.
"

It's not the boot parameters but we seem to be lacking any other real errors to investigate. I was wondering if this bit next could be masking the real error?

dracut-initqueue[1208]: /lib/dracut/hooks/initqueue/timeout/50-anaconda-error-reporting.sh: line 19: /run/anaconda/initrd_errors.txt: No such file or directory

**Distribution used**
RHEL 9

**Dracut version**
dracut-055-45.git20220404.el9_0

**Init system**
Which init system is being used?
Not entirely sure what this means. Provisioning is done with Satellite 6.11, this is the initrd:

initrd=boot/red-hat-enterprise-linux-9-for-x86_64-baseos-kickstart-9-0-254-initrd.img

**To Reproduce**
Run kickstart install 

**Expected behavior**
Installation to succeed

**Additional context**
I have tried this on about 20 identical systems and about half of them fail consistently.
[rdsosreport_debug.txt](https://github.com/dracutdevs/dracut/files/9969735/rdsosreport_debug.txt)

**Comment by LaszloGombos** [comment]
> dracut-initqueue[1208]: /lib/dracut/hooks/initqueue/timeout/50-anaconda-error-reporting.sh: line 19: /run/anaconda/initrd_errors.txt: No such file or directory

I would reach out to https://github.com/rhinstaller/anaconda/blob/master/dracut/anaconda-error-reporting.sh community first, this repo is for dracut itself and not for anaconda installer.

If you believe this is a dracut issue, we would need to be able to reproduce the problem on latest dracut.

**Comment by LaszloGombos** [comment]
CC @VladimirSlavik

**Comment by VladimirSlavik** [comment]
Hi, not an expert, but hopefully my 2c brings something. There is actually a tangle of bugs linked as duplicates and clones, so I'm not sure where exactly to respond. The anaconda reporting dracut hook is set up for timeout, so conceivably it might be executed even for unrelated timeouts. Jirka's [comment](https://bugzilla.redhat.com/show_bug.cgi?id=2107750#c4) that there are two issues seems to go in that direction too.

**Comment by Conan-Kudo** [comment]
Yeah, I'm going to go with it is _at least_ a bug with the Anaconda dracut module for stage 2, and likely not an issue here. I'm going to close this accordingly, and if it is actually a dracut issue, we can reopen it.
