### ISSUE TITLE
please add virtio drivers to --no-host-only mode

### ISSUE THREAD

**Issue by poettering** [dracutdevs/dracut#205]
It appears the virtio kernel drivers are missing from the initrd in no-host-only mode.

See:

https://github.com/systemd/mkosi/issues/56

**Comment by poettering** [comment]
@haraldh any update on this one?

**Comment by haraldh** [comment]
Just add the "qemu" dracut module, when you craft the initramfs.
```
dracut --add qemu
```

I don't think the virtio drivers should be included in a bare metal initramfs.

**Comment by haraldh** [comment]
I mean, you know, that the image might be used in a qemu instance. dracut does not.

**Comment by poettering** [comment]
hmm, i thought the point of "no-host-only" was that the image boots on pretty much all systems for which support is enabled in the kernel. If that's not its usecase, what is it then?

**Comment by haraldh** [comment]
Fixed by commit 21789cbb0a6d103176a2e10c9dd456cdcdcb4b94
