### ISSUE TITLE
test case for aarch64 

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2082]
One motivation is to test device tree support.

Related - https://github.com/dracutdevs/dracut/pull/2075

**Comment by LaszloGombos** [comment]
@athierry1 

Thanks for helping with this. Just to scope this work, I think the initial main goal is not necessary to test your PR, but at least to have one test case for aarch64 and device tree support.

Ideally we create a setup where the Qemu VM would only boot if initramfs is properly computed by dracut and dracut-install. 

>  For instance a Raspberry Pi 3 emulated with QEMU (QEMU has a `raspi3b` machine)
Yes, thinking of qemu-system-aarch64

> * make sure those two drivers are built as modules 

I would hope to avoid building the kernel and just grab it from somewhere. Alpine has 2 kernel configs here - https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/netboot/ .. Would one of them work for this purpose by any chance ?

**Comment by athierry1** [comment]
> Thanks for helping with this. Just to scope this work, I think the initial main goal is not necessary to test your PR, but at least to have one test case for aarch64 and device tree support.
> 
> Ideally we create a setup where the Qemu VM would only boot if initramfs is properly computed by dracut and dracut-install.

We could use a Fedora image (https://download.fedoraproject.org/pub/fedora/linux/releases/37/Server/aarch64/images/Fedora-Server-37-1.7.aarch64.raw.xz). Fedora uses dracut and needs an initramfs to boot with its default kernel config. I gave it a try on QEMU and was able to run it and build an initramfs.

> I would hope to avoid building the kernel and just grab it from somewhere. Alpine has 2 kernel configs here - https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/netboot/ .. Would one of them work for this purpose by any chance ?


I tried Alpine Linux but I'm not sure if it's the best candidate. AIUI by default the whole system runs in a initramfs, so it's not a setup where the initramfs mounts the root filesystem. What do you think?
Also, I was not able to get it to boot on QEMU (I got errors from the mmc driver)

**Comment by bdrung** [comment]
I tried to run the test suite on all Ubuntu architectures (including arm64/aarch64). After applying several patches (see https://github.com/dracutdevs/dracut/pull/2487), it fails with lacking IDE support in QEMU for non-x86: https://github.com/dracutdevs/dracut/issues/2493
