### ISSUE TITLE
BONDBRIDGEVLANIFCFG integration tests are failing 

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2087]
Test 60 and 61.
It seems all OS and all networking options. 
There is no reference env where this would pass.

Some logs
 - https://github.com/dracutdevs/dracut/actions/runs/3543167418/jobs/5949383334
 - https://github.com/dracutdevs/dracut/actions/runs/3543206306/jobs/5949454910

**Comment by bengal** [comment]
Hi, the problem seems to be that interfaces are not renamed to `enx*` on the server, even though the image contains a `/etc/systemd/network/01-server.link` file with `NamePolicy=mac`. Thus, `server-init.sh` times out waiting for interfaces.

**Comment by bengal** [comment]
I got the problem now, we are not removing `01-client.link` from the server filesystem image. Should I add the fix to existing PR #2180 or do you prefer if I open a separate one?

**Comment by bengal** [comment]
See https://github.com/dracutdevs/dracut/pull/2189 for test 60.
