### ISSUE TITLE
misbuild crypttab in iniramfs -> no keyfile decrpytion of 2+ partition possible.

### ISSUE THREAD

**Issue by Cyborgscode** [dracutdevs/dracut#2128]
OS: Fedora 36
https://bugzilla.redhat.com/show_bug.cgi?id=2153623

**Describe the bug**

the system installed /etc/crypttab is not entirely copied into the initramfs.

It's possible, that this is the cause for a malfunction of the initramfs LuksOpen function,
as it does not unlock all encrypted drives with a usb supplied key, but just the one drive,
that gets placed into the initramfs version of crypptab.

In a system, with "/" and "SWAP" partitions encrypted,  2 entries in /etc/crypttab exists:

```
luks-92b93668-3c6b-4b88-9c19-8575292c14ed UUID=92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-id/usb-XXXXXXXXXXXXXXXXXXX-0:0 luks,tries=3,key...
luks-1ba1a9d5-7aef-4ccc-83fe-15b43458d9b9 UUID=1ba1a9d5-7aef-4ccc-83fe-15b43458d9b9 /dev/disk/by-id/usb-XXXXXXXXXXXXXXXXXXX-0:0 luks,tries=3,key....
```

But only the one for "/" , which is the first one in list is created in the resulting iniramfs-crypptab:

`luks-92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-uuid/92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-id/usb-XXXXXXXXXXXXXXXXXXX-0:0 luks,tries=3,key...
`
As you can see here, the 2. col has been altered to an absolute path, so it got processed by something.

The resulting question, which answere I can't find myself is, is it the missing entry which causes the not executed decryption of partition 2 or is it a bug in the decryptor routine, which does not reuse the necessary informations for all parititions OR BOTH.

I have changed the usb-stick-uuid for partition 2, but it did not alter the result, still 1 entry created.

This way it will never be possible to use two different keyfiles for two partitions on the same drive. This is defacto a bug in the component which creates the crypttab file. 

IF the same keyfile is used for both ( or more ) partitions, is IMO ok to just write it to crypttab, as the decryptorroutine should reuse given keyfiles to any none decrypted partition by itself, as it does with the first password entry, which is reused for any found encrypted partition.

Is it possible to test this by creating the initramfs manually step-by-step? Because, including /etc/crypptab via the options did not work.

**Dracut version**

Dracut 057 release 3 of Fedora 36.

**Init system**

systemd

**To Reproduce**

see Bugzilla link for details.

**Expected behavior**

creation of a crypttab containing all encrypted partitions found in systemwide /etc/crypttab that need special handling.

**Additional context**

**Comment by aafeijoo-suse** [comment]
Try adding the `force` option to the missing entry, i.e.: force,luks,tries=3,key...

**Comment by Cyborgscode** [comment]
forcing the second entry solved the issue.. laptop booting without password questions.

Next question: 

Why did it need forcing?

**Comment by aafeijoo-suse** [comment]
Very old stuff added here: https://github.com/dracutdevs/dracut/commit/64ae4e07
Unfortunately, without any explanation.

**Comment by Cyborgscode** [comment]
Next issue:

keyfile-timeout=10  does not work at all. It should set the fallback timer to 10s to ask for a password, but it does not. It waits forever for the usb stick.

**Comment by Cyborgscode** [comment]
> Very old stuff added here: [64ae4e07](https://github.com/dracutdevs/dracut/commit/64ae4e07) Unfortunately, without any explanation.

noone had an encrypted swap at it seems ;) I suggest to change it.

**Comment by aafeijoo-suse** [comment]
> Next issue:
> 
> keyfile-timeout=10 does not work at all. It should set the fallback timer to 10s to ask for a password, but it does not. It waits forever for the usb stick.

This is a systemd issue unrelated to dracut, fixed in v252 (https://github.com/systemd/systemd/commit/7aa0b012)

**Comment by Cyborgscode** [comment]
I informed the Fedora Maintainer and requested a backport for F36/37 .

From my POV, we can close the issue when the swap filter patch is reverted.

**Comment by Cyborgscode** [comment]
> > Next issue:
> > keyfile-timeout=10 does not work at all. It should set the fallback timer to 10s to ask for a password, but it does not. It waits forever for the usb stick.
> 
> This is a systemd issue unrelated to dracut, fixed in v252 ([systemd/systemd@7aa0b012](https://github.com/systemd/systemd/commit/7aa0b012))

we noe have this patch in fedora, but it's not working and even worse, no password can be entered it stick is removed. There must be more than just that commit.

**Comment by aafeijoo-suse** [comment]
@Cyborgscode is this issue still reproducible or can we close it?

**Comment by Cyborgscode** [comment]
Tested Fedora 37 with the same result. If a keyfile is given, no fallback to password is done.

SystemD 251.14-2.fc37 , CryptSetup 2.6.1  and dracut-059-2.fc37 are in use.

**Comment by Cyborgscode** [comment]
Works with F38 systemd 253 .
