### ISSUE TITLE
No such file or directory while recreating the initramfs file using dracut

### ISSUE THREAD

**Issue by Subramanian-ERS** [dracutdevs/dracut#2131]
**Describe the bug**
I am trying to make my CentOS 7 server FIPS compliant by installing dracut. While I run dracut -f command to recreate the initramfs file, I get multiple "No such file or directory for multiple files" errors, even though the said files are present.

**Distribution used**
Output of /etc/os-release:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Dracut version**
033-572.el7

**Init system**
systemd

**To Reproduce**
I followed the instructions in the link - https://docs.logrhythm.com/docs/enterprise/client-console-administrator-guide/deployment-security/federal-information-processing-standards-fips/establishing-ipsec-communications-between-windows-linux-os/linux-centos-ipsec-configuration/put-linux-centos-into-fips-mode. I am getting this error during the "**dracut -f**" step.

**Expected behavior**
I did not expect an error because the files that the script is looking for are present in the server. Example of one error can be found below:

**"/usr/lib/dracut/modules.d/90kernel-modules/module-setup.sh: line 16: /lib/modules/3.10.0-1160.15.2.el7.x86_64///lib/modules/3.10.0-1160.15.2.el7.x86_64/kernel/sound/drivers/vx/snd-vx-lib.ko.xz: No such file or directory"**

The file /lib/modules/3.10.0-1160.15.2.el7.x86_64/kernel/sound/drivers/vx/snd-vx-lib.ko.xz is present in the server, but I am not sure why the script is looking for something else.

**Comment by johannbg** [comment]
We only support the latest version of dracut here upstream ( 057 ) hence closing
If you can recreate this with latest upstream release of dracut feel free to reopen this
