### ISSUE TITLE
Some networking tests regress with systemd-networkd

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2141]
As part of working on CI, I noticed that same networking tests are failing with systemd-networked (on Fedora container).

The failing tests are passing with network-manager and with network-legacy options.

Some of the failing tests:
 - 20 (NFS)
 - 30 (ISCSI)
 - 50 (MULTINIC with NFS)

This blocks enabling systemd-networked on the CI.

I do not use and not familiar with systemd-networkd, I am unable to troubleshoot this further. The logs for the test failures can be found here: - https://github.com/dracutdevs/dracut/actions/runs/3757898019/

**Comment by johannbg** [comment]
We probably are missing a generator that matches our arguments network for sd-networkd
systemd has a generator so it supports some commandline parameters see [1](https://github.com/systemd/systemd/blob/main/src/network/generator/network-generator.c) but we need to match it with what we have.

I think @aafeijoo-suse had gathered the parameters we have and was doing some comparison between networking solution but he can correct me if I'm wrong about that.

**Comment by aafeijoo-suse** [comment]
> I think @aafeijoo-suse had gathered the parameters we have and was doing some comparison between networking solution but he can correct me if I'm wrong about that.

Here: #1876
