### ISSUE TITLE
Choose font-size.

### ISSUE THREAD

**Issue by K1D77A** [dracutdevs/dracut#2176]
Hi, I am unsure if this is already a feature but the font size for an initramfs generated by Dracut is extremely small when using a small (16inch) 4k display. 
Being able to specify font size would be very useful.
Thanks.

**Comment by mikhailnov** [comment]
all dracut does about this is installing /etc/vconsole.conf which is a config of systemd-vconsole-setup(8). As far as I understand from vconsole.conf(5), there are no setting of the font size. The tty subsystem in the Linux kernel is in not a good shape in general. You should probably set console resultion via kernel cmdline.

This bug can be closed as not a bug.

**Comment by K1D77A** [comment]
Thanks for the response :+1:
