### ISSUE TITLE
A hw specific crc32-pclmul or crc32-arm-ce is prefered over crc32_generic

### ISSUE THREAD

**Issue by kwizart** [dracutdevs/dracut#218]
This issue was discovered when trying to boot to a f2fs rootfs on armv7-a
This filesystem requires crc32 in order to mount, so a working crc32 implementation has to be bundled into the initramfs.

In the arm case, there are two candidates: crc32-arm-ce and crc32_generic, (both using crc32 module alias) but only the former is included by default in the initramfs by dracut.
Unfortunately, this module does not load on armv7-a devices given it relies on armv8-a Crypto Extensions. It is only relevant for a 32bit kernel built and executed on a armv8-a (64bit) device.

The same issue apply for crc32-pclmul or crc32c-intel on x86 that cannot always load.

I would suggest to select whatever comes the default as crc32 but also enforces crc32_generic.

I confirm that when both crc32-arm-ce and crc32_generic are available in the initramfs, the appropriate module is loaded.

**Comment by kwizart** [comment]
FYI, I haven't manage to enforce one or the other module, using HostOnly or not.

**Comment by haraldh** [comment]
would you please make a pull request from this?

**Comment by kwizart** [comment]
Well, as I said, this commit a WIP (not working) version, the crc32-arm-ce module is still picked whereas I would have expected to have both...

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by kwizart** [comment]
I'm closing because I'm not reproducing the issue with current dracut releases. But I don't know how it was fixed.
(currently away from arm devices to double check, but will re-open if any reproducer).
