### ISSUE TITLE
iso-scan.sh is racing with udev on newer kernels

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2183]
Redhat bug: https://bugzilla.redhat.com/show_bug.cgi?id=2131852
Void Linux: https://github.com/void-linux/void-mklive/issues/294

Seems there is a lot of value in cross referencing bugs and discussing it upstream.

Issue could be related to a [change in kernel 5.19+ ](https://github.com/torvalds/linux/commit/498ef5c777d9c89693b70cc453b40c392120ea1b) which leads to a udev race to figure out the label of the ISO.

Intermittent. rd.live.debug makes successful boots possible/more reliable.

CC @FGrose @pvalena @pmensik @0x5c @splate07

**Comment by 0x5c** [comment]
(from the void-mklive issue)
> Please try to autoload modules that this use case needs from the bootloader command line arguments - e.g. "rd.driver.pre= loop,cdrom,isofs, squashfs"
> You could also try this patch that debian carries: https://salsa.debian.org/debian/dracut/-/blob/master/debian/patches/udevsettle

Unfortunately, both of these have no effect

**Comment by 0x5c** [comment]
> Kind of wondering if some of the "fallbacks" introduced in https://github.com/dracutdevs/dracut/pull/2130 would inadvertently would help here as well.

Tried that too just now, no change observed

A patch was made from the PR and applied on top of dracut 59.

**Comment by 0x5c** [comment]
I'm still trying to find where in dmsquash (or other module) is the check for the label happening, I want to see if adding settle/trigger right before that point helps.

**Comment by FGrose** [comment]
The isofile is set up as a loop device here:
https://github.com/dracutdevs/dracut/blob/master/modules.d/90dmsquash-live/iso-scan.sh#L24
Try the `udevadm settle` after that.
Since F36 has PTTYPE='dos' and F37 PTTYPE='gpt', you might try
`losetup -f -P "/run/initramfs/isoscan/$isofile"`
to see it that makes a difference.

**Comment by 0x5c** [comment]
I just now tried 3 images with added `udevadm` call after `losetup`, one with `udevadm trigger`, one with `udevadm settle`, and one with both. The image that only settled did not boot, but the two others were successful.

It seems to me like `trigger` is the proper thing to run here. The computer I tested these on is a particularly slow Pentium D machine; I'd expect such a computer to make the race with udev as worse as possible.

```patch
--- a/modules.d/90dmsquash-live/iso-scan.sh
+++ b/modules.d/90dmsquash-live/iso-scan.sh
@@ -22,6 +22,8 @@
         mount -t auto -o ro "$dev" "/run/initramfs/isoscan" || continue
         if [ -f "/run/initramfs/isoscan/$isofile" ]; then
             losetup -f "/run/initramfs/isoscan/$isofile"
+            udevadm trigger
             ln -s "$dev" /run/initramfs/isoscandev
             rm -f -- "$job"
             exit 0
```

**Comment by 0x5c** [comment]
> can you perhaps try this more specific line instead ?

This booted successfully, seems like it might be the best way considering it's present elsewhere

> Are you planning to upload a PR later or ?

I'm definitely open to making that PR

**Comment by 0x5c** [comment]
Made the PR, #2196
