### ISSUE TITLE
ukify + dracut

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2191]
Request for Comments.

[ukify — Combine kernel and initrd into a signed Unified Kernel Image
](https://www.freedesktop.org/software/systemd/man/ukify.html)

I think we should discuss the relationship between dracut and ukify. Few relevant questions I can think of:
 - should dracut use ukify if available ? 
 - Is there a feature/command line in ukify that dracut should consider implementing ? 
 
I noticed (some stats [here](https://github.com/dracutdevs/dracut/graphs/traffic)) that people opening dracut github pages and  looking for information on ukify, so perhaps at least we can have a few lines of documentation around this.

**Comment by johannbg** [comment]
We already support creating unified kernel images so the answer to the first question is no, we can have a look at the second question and see if there is something ukify has and we can implement/improve upon but we should let uki's the self made standard from sd community and the tool they are pushing on everyone along with bake for few years. 
There is a catch 22 with uki's and it's best to just let traditional downstream distro bump their head into that catch 22.

**Comment by JoseskVolpe** [comment]
Sorry to bring this old issue back but i think what may be lacking in dracut is the ability to make PCR signing. It's often used in ukify to auto-unlock LUKS volumes without having to rely on PCRs values to stay. Ukify is not only used to generate UKIs, but also to generate keys that will be used to initrd generators to sign volumes with systemd after predicting PCR values. If this feature is already implemented in dracut i couldn't find a documentation on how to use it. 

Look: https://wiki.archlinux.org/title/Trusted_Platform_Module#PCR_policies
