### ISSUE TITLE
Booting Live squashFS images with a thin overlay emits concerning errors

### ISSUE THREAD

**Issue by rustydb** [dracutdevs/dracut#2198]
**Describe the bug**
A clear and concise description of what the error is.

These (possibly) extraneous messages are printed on every boot:

```
Invalid format on line 1 of table on stdin.
Command failed.
```

These seem to appear when using a squashFS image and a thin overlay, it is unclear whether the errors indicate a problem with the thin overlay or not.

**Distribution used**
Which distribution was this behaviour seen in?

SLES15SP4, SP3, and SP2.

**Dracut version**
Which dracut version was this behaviour seen in?

Currently dracut-055+suse.323.gca0e74f0-150400.3.13.1

**Init system**
Which init system is being used?

**To Reproduce**
Steps or code to reproduce the behavior.

Use these kernel parameters, replacing `rootfs` and `LABEL=ROOTRAID` with your squash image and overlay disk identifier.

```
rd.live.squashimg=rootfs rd.live.overlay=LABEL=ROOTRAID rd.live.overlay.thin=1 rd.live.overlay.overlayfs=1
```

**Expected behavior**

No messages, or a fatal error detailing why/what.

**Additional context**
Add any other context you like about the problem here.

It looks like these messages come from this line https://github.com/dracutdevs/dracut/blob/master/modules.d/90dmsquash-live/dmsquash-live-root.sh#L298

`sz` is undefined, causing the `dmsetup` command to fail.

`sz` is set [here](https://github.com/dracutdevs/dracut/blob/master/modules.d/90dmsquash-live/dmsquash-live-root.sh#L389) before `do_live_overlay` is called, but if [this conditional](https://github.com/dracutdevs/dracut/blob/master/modules.d/90dmsquash-live/dmsquash-live-root.sh#L385) evaluates to true then `sz` is never set.

Maybe this is intentional. Based on how it's written, `sz` is not supposed to be defined if the `FSIMG` is `SQUASHED`. However it then leads me to wonder if thin overlays are not supposed to be used in this case either, because it is unclear why the [`thin_snapshot`](https://github.com/dracutdevs/dracut/blob/master/modules.d/90dmsquash-live/dmsquash-live-root.sh#L278) block is doomed to emit this error.

It seems that using a squashFS + `rd.live.overlay.thin` is either not supposed to be possible, or there's some missing handling around the undefined `sz` parameter.

Here's my output when I use `rd.debug`.

```bash
+ mkdir -m 0755 -p /run/initramfs/live
+ '[' -f /dev/disk/by-label/SQFSRAID ']'
++ blkid -o value -s TYPE /dev/disk/by-label/SQFSRAID
+ livedev_fstype=xfs
+ '[' xfs = squashfs ']'
+ '[' xfs '!=' ntfs ']'
+ mount -n -t auto -o ro /dev/disk/by-label/SQFSRAID /run/initramfs/live
+ '[' -e /run/initramfs/live/1.4.0/rootfs ']'
+ SQUASHED=/run/initramfs/live/1.4.0/rootfs
+ '[' -e /run/initramfs/live/1.4.0/rootfs ']'
+ '[' -n '' ']'
++ losetup -f
+ SQUASHED_LOOPDEV=/dev/loop0
+ losetup -r /dev/loop0 /run/initramfs/live/1.4.0/rootfs
+ mkdir -m 0755 -p /run/initramfs/squashfs
+ mount -n -t squashfs -o ro /dev/loop0 /run/initramfs/squashfs
+ '[' -d /run/initramfs/squashfs/LiveOS ']'
+ '[' -d /run/initramfs/squashfs/proc ']'
+ FSIMG=/run/initramfs/live/1.4.0/rootfs
+ '[' -z yes ']'
+ overlayfs=required
+ '[' -n /run/initramfs/live/1.4.0/rootfs ']'
+ '[' -n '' ']'
+ readonly_base=1
+ '[' -z /run/initramfs/live/1.4.0/rootfs -a -n '' -a -z required ']'
+ '[' -n '' ']'
+ '[' LABEL=ROOTRAID = none -o LABEL=ROOTRAID = None -o LABEL=ROOTRAID = NONE ']'
+ '[' /run/initramfs/live/1.4.0/rootfs = /run/initramfs/live/1.4.0/rootfs ']'
+ BASE_LOOPDEV=/dev/loop0
+ '[' '' = rw ']'
+ do_live_overlay
++ blkid -s LABEL -o value /dev/disk/by-label/SQFSRAID
+ l=SQFSRAID
++ blkid -s UUID -o value /dev/disk/by-label/SQFSRAID
+ u=5385c045-ac71-49e7-969f-e09efb53a7e1
+ '[' -z LABEL=ROOTRAID ']'
+ strstr LABEL=ROOTRAID :
+ '[' LABEL=ROOTRAID '!=' LABEL=ROOTRAID ']'
+ '[' -z '' -o '' = auto ']'
+ pathspec=/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1
+ devspec=LABEL=ROOTRAID
+ '[' -z '' -a -n LABEL=ROOTRAID -a -n /1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1 -a -n LABEL=ROOTRAID ']'
+ mkdir -m 0755 -p /run/initramfs/overlayfs
+ mount -n -t auto LABEL=ROOTRAID /run/initramfs/overlayfs
+ '[' -f /run/initramfs/overlayfs/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1 -a -w /run/initramfs/overlayfs/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1 ']'
+ '[' -d /run/initramfs/overlayfs/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1 ']'
+ '[' -d /run/initramfs/overlayfs/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1/../ovlwork ']'
+ ln -s /run/initramfs/overlayfs/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1 /run/overlayfs
+ ln -s /run/initramfs/overlayfs/1.4.0/overlay-SQFSRAID-5385c045-ac71-49e7-969f-e09efb53a7e1/../ovlwork /run/ovlwork
+ '[' -z required ']'
+ overlayfs=required
+ setup=yes
+ '[' -n required ']'
+ modprobe overlay
+ '[' -z yes -o -n '' ']'
+ '[' -z required ']'
+ '[' -n yes ']'
+ modprobe dm_thin_pool
+ mkdir -m 0755 -p /run/initramfs/thin-overlay
+ thin_data_sz=67108864
+ thin_meta_sz=6710886
+ dd if=/dev/null of=/run/initramfs/thin-overlay/meta bs=1b count=1 seek=6710886
+ dd if=/dev/null of=/run/initramfs/thin-overlay/data bs=1b count=1 seek=67108864
++ losetup --show -f /run/initramfs/thin-overlay/meta
+ THIN_META_LOOPDEV=/dev/loop1
++ losetup --show -f /run/initramfs/thin-overlay/data
+ THIN_DATA_LOOPDEV=/dev/loop2
+ echo 0 67108864 thin-pool /dev/loop1 /dev/loop2 1024 1024
+ dmsetup create live-overlay-pool
+ dmsetup message /dev/mapper/live-overlay-pool 0 'create_thin 0'
+ echo 0 '' thin /dev/mapper/live-overlay-pool 0 ''
+ dmsetup create live-rw
Invalid format on line 1 of table on stdin.
Command failed.
+ '[' -z required ']'
+ ln -s /dev/loop0 /dev/live-base
+ '[' -n '' ']'
++ getarg rootflags
++ debug_off
++ set +x
++ return 1
+ ROOTFLAGS=
+ '[' -n required ']'
+ mkdir -m 0755 -p /run/rootfsbase
+ '[' -n '' ']'
+ '[' -n '' ']'
+ ovlfs=lowerdir=/run/rootfsbase
+ mount -r /run/initramfs/live/1.4.0/rootfs /run/rootfsbase
+ '[' -z 1 ']'
+ '[' -e /run/initramfs/live/1.4.0/rootfs ']'
+ umount -l /run/initramfs/squashfs
+ ln -s null /dev/root
+ need_shutdown
+ :
+ exit 0
```

Here is `lsblk` and `losetup -a`

```bash
ncn-w003:~ # lsblk
NAME                       MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0                        7:0    0   5.8G  1 loop  /run/rootfsbase
loop1                        7:1    0   3.2G  0 loop
└─live-overlay-pool        254:0    0    32G  0 dm
loop2                        7:2    0    32G  0 loop
└─live-overlay-pool        254:0    0    32G  0 dm
sda                          8:0    0 447.1G  0 disk
├─sda1                       8:1    0   476M  0 part
│ └─md127                    9:127  0 475.9M  0 raid1 /metal/recovery
├─sda2                       8:2    0  22.8G  0 part
│ └─md126                    9:126  0  22.8G  0 raid1 /run/initramfs/live
├─sda3                       8:3    0 139.7G  0 part
│ └─md125                    9:125  0 139.6G  0 raid1 /run/initramfs/overlayfs
└─sda4                       8:4    0 139.7G  0 part
  └─md124                    9:124  0 279.1G  0 raid0
    └─metalvg0-CRAYS3CACHE 254:1    0   200G  0 lvm   /var/lib/s3fs_cache
sdb                          8:16   0 447.1G  0 disk
├─sdb1                       8:17   0   476M  0 part
│ └─md127                    9:127  0 475.9M  0 raid1 /metal/recovery
├─sdb2                       8:18   0  22.8G  0 part
│ └─md126                    9:126  0  22.8G  0 raid1 /run/initramfs/live
├─sdb3                       8:19   0 139.7G  0 part
│ └─md125                    9:125  0 139.6G  0 raid1 /run/initramfs/overlayfs
└─sdb4                       8:20   0 139.7G  0 part
  └─md124                    9:124  0 279.1G  0 raid0
    └─metalvg0-CRAYS3CACHE 254:1    0   200G  0 lvm   /var/lib/s3fs_cache
sdc                          8:32   0   1.7T  0 disk
├─sdc1                       8:33   0  69.8G  0 part  /run/containerd
├─sdc2                       8:34   0 645.5G  0 part  /run/lib-containerd
└─sdc3                       8:35   0 178.8G  0 part  /var/lib/kubelet
nbd0                        43:0    0     0B  0 disk
nbd1                        43:32   0     0B  0 disk
nbd2                        43:64   0     0B  0 disk
nbd3                        43:96   0     0B  0 disk
nbd4                        43:128  0     0B  0 disk
nbd5                        43:160  0     0B  0 disk
nbd6                        43:192  0     0B  0 disk
nbd7                        43:224  0     0B  0 disk
nbd8                        43:256  0     0B  0 disk
nbd9                        43:288  0     0B  0 disk
nbd10                       43:320  0     0B  0 disk
nbd11                       43:352  0     0B  0 disk
nbd12                       43:384  0     0B  0 disk
nbd13                       43:416  0     0B  0 disk
nbd14                       43:448  0     0B  0 disk
nbd15                       43:480  0     0B  0 disk
ncn-w003:~ # losetup -a
/dev/loop1: [0025]:1522 (/run/initramfs/thin-overlay/meta)
/dev/loop2: [0025]:1523 (/run/initramfs/thin-overlay/data)
/dev/loop0: [2430]:134 (/run/initramfs/live/1.4.0/rootfs)
```

Full boot logs are attached: [dracut-thin-overlay-extraneous-messages.txt](https://github.com/dracutdevs/dracut/files/10719126/dracut-thin-overlay-extraneous-messages.txt)

**Comment by aafeijoo-suse** [comment]
> Distribution used
> Which distribution was this behaviour seen in?
> SLES15SP4, SP3, and SP2.
> 
> Dracut version
> Which dracut version was this behaviour seen in?
> Currently dracut-055+suse.323.gca0e74f0-150400.3.13.1

This version is too old to be supported upstream. Is this issue reproducible with openSUSE Tumbleweed? if yes, we'll handle it here, otherwise, please report it to https://bugzilla.suse.com

Thanks.

**Comment by rustydb** [comment]
So there is no comment to current HEAD of this branch? The links I pointed out clearly show `sz` is undefined for that `dmsetup` command.

I'll open a bug with SUSE, but it seems hopeless given that this is broken in HEAD.

**Comment by rustydb** [comment]
> So there is no comment to current HEAD of this branch? The links I pointed out clearly show `sz` is undefined for that `dmsetup` command.
> 
> I'll open a bug with SUSE, but it seems hopeless given that this is broken in HEAD.

Having difficulty finding where to open the bug on bugzilla.suse.com, none of the categories seem they pertain to SLES15SP4. In the meantime I'm conversing with my team.

If someone could comment about the code, and the intention of thin overlays and squashFS, that may suffice.

**Comment by aafeijoo-suse** [comment]
> So there is no comment to current HEAD of this branch? The links I pointed out clearly show `sz` is undefined for that `dmsetup` command.

I didn't analyze the code you linked, just the dracut version you posted. If the code hasn't changed since then, this is the place to report it.

**Comment by FGrose** [comment]
>... thin overlays are not supposed to be used in this case ...

This is true.  Thin overlays are incompatible with flattened, SquashFS only base images.  These require OverlayFS overlays. The two don't mix.

The SquashFS software driver is limited to reading only.  If another filesystem with read-write capability is embedded within the SquashFS image, that filesystem, setup in a loop device, may be overlayed with the Device-mapper overlay tooling.

From Booting live images in https://github.com/dracutdevs/dracut/blob/master/man/dracut.cmdline.7.asc#booting-live-images  the line 
>For OverlayFS mount overlays, the filesystem structure may also be a direct compression of the root filesystem

should be read as "a SquashFS only direct/flattened compression of the root filesystem requires an OverlayFS mount overlay.

Not a bug.

**Comment by rustydb** [comment]
@FGrose , I think that provides the clarity I needed. Thank you.
