### ISSUE TITLE
[RFC] write down a modprobe.d/module-backlist.conf based on rd.driver.blacklist

### ISSUE THREAD

**Issue by kwizart** [dracutdevs/dracut#220]
Here I'm suggesting dracut to have a script (installed by default) to write down a /etc/modprobe.d/dracut-blacklist.conf (within the initramfs, then transfered on rootfs) based on the rd.driver.blacklist cmdline entries.

The problem is when I want to blacklist a module from the initramfs, most of the time, I also want it blacklisted from the entire runtime. (unless explicitly modprobe'd later).

Instead the current behavior requires a dedicated modprobe.d/myblacklist.conf file that might require to be bundled into the initramfs to really takes effect.

It's very efficient when this configuration remains static, but if I want to switch easily, this start to be difficult:
- Boot the OS to userspace
- Switch the modprobe.conf
- Switch the cmdline
- Recreate the initramfs with the appropriate blacklist bundled
- Reboot to the new configuration

If it possible to have dracut script (within the initramfs) to automatically generate the blacklist file, it would become:
- Switch the bootloader rd.driver.blacklist (or even pick an alternative config menu for grub2 or else).
And that's all.

The alternative is probably to make kmod learn about rd.driver.blacklist. (and to allow an override only with modprobe mymodule --force)

This issue is relevant for nvidia-drm nouveau switching.

**Comment by haraldh** [comment]
man modprobe (from kmod):

modprobe will also use module options specified on the kernel command line in the form of <module>.<option> and blacklists in the form of modprobe.blacklist=<module>.
