### ISSUE TITLE
make rpm fails with error: Installed (but unpackaged) file(s) found:

### ISSUE THREAD

**Issue by johnmeneghini** [dracutdevs/dracut#2204]
**Describe the bug**

```
> make rpm 
...
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Recommends: dracut-debugsource(x86-64) = 059-65.git20230214.fc36
Checking for unpackaged file(s): /usr/lib/rpm/check-files /var/tmp/rpmbuild-dracut.GZDEoi/BUILDROOT/dracut-059-65.git20230214.fc36.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib/dracut/modules.d/80test-makeroot/finished-false.sh
   /usr/lib/dracut/modules.d/80test-makeroot/module-setup.sh
   /usr/lib/dracut/modules.d/80test-root/module-setup.sh
   /usr/lib/dracut/modules.d/80test/hard-off.sh
   /usr/lib/dracut/modules.d/80test/module-setup.sh

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/dracut/modules.d/80test-makeroot/finished-false.sh
   /usr/lib/dracut/modules.d/80test-makeroot/module-setup.sh
   /usr/lib/dracut/modules.d/80test-root/module-setup.sh
   /usr/lib/dracut/modules.d/80test/hard-off.sh
   /usr/lib/dracut/modules.d/80test/module-setup.sh
make: *** [Makefile:256: rpm] Error 1
```
**Distribution used**
```
fedora-vm2:dracut(fix_rpm) > hostnamectl
 Static hostname: fedora-vm2
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: 5c079f3479774fdbac04330b59e0e7a7
         Boot ID: 0722b3e85c9b47baa7cfc7739a751af1
  Virtualization: kvm
Operating System: Fedora Linux 36 (Server Edition) 
     CPE OS Name: cpe:/o:fedoraproject:fedora:36
          Kernel: Linux 6.1.7-100.fc36.x86_64
    Architecture: x86-64
 Hardware Vendor: QEMU
  Hardware Model: Standard PC _i440FX + PIIX, 1996_
```
**Dracut version**

```
fedora-vm2:dracut(master) > git logl -10
61ceb35f 2023-02-14 1671538003  (HEAD -> master, origin/master, origin/HEAD) revert(network-manager): avoid restarting NetworkManager [ Antonio Álvarez Feijoo / lkundrak@v3.sk ]
a6dd5bfb 2023-02-13 1676283180  fix(dracut.sh): handle sbsign errors for UEFI builds [ Jóhann B. Guðmundsson / antonio.feijoo@suse.com ]
8602df70 2023-02-13 1676283069  fix(dracut.sh): handle out of space error for UEFI builds [ Jóhann B. Guðmundsson / antonio.feijoo@suse.com ]
726d56ca 2023-02-13 1675805055  fix(network): IPv6: don't wait for RA for static IPv6 assignments [ Antonio Álvarez Feijoo / mwilck@suse.com ]
b074216b 2023-02-13 1675803591  fix(network-legacy): always include af_packet [ Antonio Álvarez Feijoo / mwilck@suse.com ]
```
**To Reproduce**
```
make rpm
```
**Expected behavior**
rpms successfully build

**Comment by johannbg** [comment]
Note that we dont do downstream packaging maintainership ( rpm or otherwise ) here upstream anymore so the existing spec file is out of sync with what's in the repo since we aren't maintaining it ( nor planning on doing so ) we just haven't gotten around to drop the spec file ( along with make rpm section ) from the codebase.

You can workaround this issue by adding the file list from "Installed (but unpackaged) file(s)" to the %files section of the dracut.spec file but you should adjust your expectation that dracut.spec file along with make rpm is going away...

**Comment by johnmeneghini** [comment]
> Note that we dont do downstream packaging maintainership ( rpm or otherwise ) here upstream anymore so the existing spec file is out of sync with what's in the repo since we aren't maintaining it ( nor planning on doing so ) we just haven't gotten around to drop the spec file ( along with make rpm section ) from the codebase.

Understood.  I'm just trying to the upstream rpm build to work. I'll work on updating the Red Hat repository next.

> You can workaround this issue by adding the file list from "Installed (but unpackaged) file(s)" to the %files section of the dracut.spec file but you should adjust your expectation that dracut.spec file along with make rpm is going away...

I can do it this way if you prefer. I thought it might be easier to simply add these missing %files to the inventory.

**Comment by johannbg** [comment]
> I can do it this way if you prefer. I thought it might be easier to simply add these missing %files to the inventory.

That would imply we were still supporting it.
