### ISSUE TITLE
mosts systemd tests on arch are broken 

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2225]
This is a regression cased by distro changes. It impacts dracut development.

Likely started around Feb-17, with this container generation run - https://github.com/dracutdevs/dracut/actions/runs/4203327775

Here is one of the earliest failed test run - https://github.com/dracutdevs/dracut/actions/runs/4205070715

**Comment by aafeijoo-suse** [comment]
> Dracut Arch test container is already on 253-1, so likely this is arch hitting #2211 .

Yes, all arch tests that were failing are back to green after locally applying the fix proposed in https://github.com/dracutdevs/dracut/issues/2211#issuecomment-1438387138

https://github.com/aafeijoo-suse/dracut/actions/runs/4305433348
