### ISSUE TITLE
Fix CodeQL issues

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2228]
~~https://github.com/dracutdevs/dracut/runs/8493550424~~
https://github.com/dracutdevs/dracut/security/code-scanning

Security Alerts:

10 high
Other Alerts:

3 warnings
17 notes

Would be good to resolve at least the 10 high alerts

**Comment by nabijaczleweli** [comment]
the page linked doesn't work (the popups are broken and the direct code links all link to nothing), and the summaries mostly range from "*so what?*" to "idiotic", so not really, no

**Comment by johannbg** [comment]
@LaszloGombos given that you decided to merge this prior to fixing the issues the scanner had already detected as I had mentioned we should do prior to merging #1987 so we would have a clean state to start from this is now your responsibility to fix...
