### ISSUE TITLE
Use --long switch for zstd compression

### ISSUE THREAD

**Issue by akdjka** [dracutdevs/dracut#2276]
**Describe the enhancement**
Unless configured otherwise, dracut uses `-15 -T0` parameters for zstd compression.
However `-15 -T0 --long` is somewhat stronger (6.88 MB instead of 7.36 in my case...on larger images the difference should be larger).
Compression and decompression speed shouldn't be affected by this switch; only memory usage. I can't assess the impact on tiny machines with huge generic initramfs images but outside of this case I don't see a good reason against using `--long`.
So I suggest enabling it by default or at least - when building an image in host-only mode.

**Comment by aafeijoo-suse** [comment]
There is no need to add a new option in dracut for each specific compression parameter, if you don't like the default, you can use `--compress` for that. E.g.:
```
--compress="zstd -15 -T0 --long"
```

**Comment by akdjka** [comment]
That's what I've done before I switched to booster.
And I didn't mean introducing a new option but changing the defaults, so typical users can benefit from that as well.
