### ISSUE TITLE
dracut 057 not loaded during boot

### ISSUE THREAD

**Issue by svajghal** [dracutdevs/dracut#2278]
**Describe the bug**
Not observing dracut log/getting loaded during boot time causing OS to boot to initramfs and hung there.

**Distribution used**
Rocky Linux 9.1

**Dracut version**
using dracut 057

**Init system**
systemd

**To Reproduce**
Boot using RL with remote rootfs using iscsi target service. 

**Expected behavior**
"dracut" should be loaded while booting 

**Additional context**

We are using dracut to build the initrd image with specific modules enabled.  Observing dracut is not loaded and system is booting into initramfs and is stuck during the boot.

**RL9.1 log**

[    3.619302] Run /init as init process
[    3.629694] systemd[1]: systemd 250-12.el9_1 running in system mode (+PAM +AUDIT +SELI)
[    3.661735] systemd[1]: Detected architecture arm64.
[    3.666695] systemd[1]: Running in initial RAM disk.

Welcome to Rocky Linux 9.1 (Blue Onyx) dracut-057-13.git20220816.el9 (Initramfs)!

[    3.709320] systemd[1]: No hostname configured, using default hostname.
[    3.715974] systemd[1]: Hostname set to <localhost>.
[    3.720996] random: systemd: uninitialized urandom read (16 bytes read)
[    3.727609] systemd[1]: Initializing machine ID from random generator.
[    3.753486] systemd[1]: Unit initrd.target not found.

The same process is wokring for RL 8.5 and we used default supported dracut 049. Here are the logs from it.

[    3.628330] Run /init as init process
[    3.680888] dracut: dracut-049-191.git20210920.el8
[    3.717057] Loading iSCSI transport class v2.0-870.
>>>>System boot to RL 8.5 .....

We even tried RL9.1 with dracut 049 and dracut is loaded during boot time. 

[    3.588674] Run /init as init process
[    3.633772] dracut: dracut-049-218.git20221019.el8_7
[    3.669112] Loading iSCSI transport class v2.0-870.
[    3.678500] iscsi: registered transport (tcp)
>>>> System boot to RL 8.5 .....

**Comment by svajghal** [comment]
Can anyone help with this issue ?

**Comment by svajghal** [comment]
I see that there are many changes after 053 version with systemd.  Our usual procedure is working well until 053 release. Form 054 dracut, initrd is not able to login to iscsi target running remotely and thereby initramfs is not able to get mount the real rootfs. 

We follow the same procedure to build initrd i.e, by using dracut with iscsi,network,.. modules and some drivers enabled.

We even added many systemd modules while building initrd, but still boot always fails into initramfs and hangs there. With the help of debug logs, we see that it is failing at switch-root service.

Here's the command line we are using:
ip=<target_ip>::<gate_way>:255.255.255.0::<interface>:off root=/dev/sda netroot=iscsi:<initiator_ip>::::<iqn> initrdmem=0x440c000000,0x8000000 acpi=force


Can anyone help why initramfs is not able to login to remote iscsi target with dracut 054-057 releases? do we need to add any new systemd modules while building initrd ?

**Comment by svajghal** [comment]
Here's the error log:

```
Received SIGCHLD from PID 345 (systemctl).
Child 345 (systemctl) died (code=exited, status=1/FAILURE)
initrd-switch-root.service: Child 345 belongs to initrd-switch-root.service.
initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
initrd-switch-root.service: Failed with result 'exit-code'.
initrd-switch-root.service: Service will not restart (restart setting)
initrd-switch-root.service: Changed start -> failed
initrd-switch-root.service: Job 70 initrd-switch-root.service/start finished, result=failed
[FAILED] Failed to start Switch Root.
See 'systemctl status initrd-switch-root.service' for details.
Startup finished in 3.667s (kernel) + 0 (initrd) + 18.272s (userspace) = 21.940s.
initrd-switch-root.service: Unit entered failed state.
initrd-switch-root.service: Triggering OnFailure= dependencies.
emergency.target: Trying to enqueue job emergency.target/start/replace-irreversibly
initrd-switch-root.service: Failed to enqueue OnFailure= job, ignoring: Unit emergency.service not found.
initrd-switch-root.service: Triggering OnFailure= dependencies done.
initrd-switch-root.service: Consumed 3ms CPU time.
initrd-switch-root.service: Control group is empty.
systemd-journald.service: Received EPOLLHUP on stored fd 12 (stored), closing.
systemd-journald.service: Got notification message from PID 264 (WATCHDOG=1)
...
```

Here are the added modules for dracut:
-m "nfs network base iscsi syslog network-manager systemd-network-management systemd"

**Comment by mwilck** [comment]
> CC @mwilck
?

**Comment by mwilck** [comment]
@svajghal, if you want us to look at this in detail, please provide serial log with "rd.debug". Also, I suggest using `rd.break=...` and figuring out what went wrong (Link bringup, IP configuration, routing, DNS, or iSCSI connection itself), and why. 

The logs above provide no insight. In particular they do not provide any clue about your claim that "initrd is not able to login to iscsi target running remotely". 

Finally, if you report issues upstream, I suggest you use the lasest upstream code, which is 059 and not 057.

**Comment by svajghal** [comment]
Thanks for the responses, We missed to enable some kernel configs and also needed to include dracut-systemd module for initrd. We are not seeing this issue now.

**Comment by svajghal** [comment]
This dracut-systemd is not mandatory for us, we enabled this to provide emergency shell service, systemd doesn't provide it. So we can use dracut-systemd instead of systemd in such cases for debugging.

For the issue to be resolved, We needed to update kernel command line and enable some kernel config options related to ISCSI.
