### ISSUE TITLE
udev-rules script: The issue with ATTR "../" that changes the relative path one directory up

### ISSUE THREAD

**Issue by Zesko** [dracutdevs/dracut#2308]
**Describe the bug**

I noticed Dracut version 059 has the issue with my custom udev-rules script:

`$ cat /etc/udev/rules.d/90-disable-mouse.rules`
```
ACTION=="add", SUBSYSTEM=="usb", DRIVERS=="usb", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c539", ATTR{../power/wakeup}="disabled"
```
This script means that it disables my Logitech mouse USB that should not wake up my PC when the PC is in sleep mode.
It does not work with Dracut version 059 initramfs, but I am very sure it should work with mkinitcpio initramfs.

**The real issue:** A piece of the script described the path `../` in ATTR that causes the issue :
```
ATTR{../power/wakeup}="disabled"
```

**Distribution used**

Manjaro or any Arch based distros

**Dracut version**

Dracut 059  and Dracut 056, both have the same issue.

**Init system**
systemd 253

**To Reproduce**

If you have the Logitech G903 mouse:

1. create a udev-rule script: `/etc/udev/rules.d/90-disable-mouse.rules` to add:
```
ACTION=="add", SUBSYSTEM=="usb", DRIVERS=="usb", ATTRS{idVendor}=="XXXX", ATTRS{idProduct}=="YYYY", ATTR{../power/wakeup}="disabled"
```

2. reboot.
3. your PC goes into sleep mode or suspend
4. Check if your mouse should not wake up your PC, but in fact my mouse wakes up my PC.

**Expected behavior**
A part of this script:
```
ATTR{../power/wakeup}="disabled" 
```
The path `../` changes the relative path one directory up and should work like the behavior of mkinitcpio initramfs.

**Comment by Zesko** [comment]
> I can point you to a lot of documentation that recommends ATTR{power/wakeup} - e.g.

I did, but I got many error messages "No such file or directory"  in journalctl log when using `ATTR{power/wakeup}`

```
3-6:1.2: /etc/udev/rules.d/90-disable-mouse.rules:1 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:06:00.3/usb3/3-6/3-6:1.2/power/wakeup}, ignoring: No such file or directory
3-6:1.0: /etc/udev/rules.d/90-disable-mouse.rules:1 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:06:00.3/usb3/3-6/3-6:1.0/power/wakeup}, ignoring: No such file or directory
3-6:1.1: /etc/udev/rules.d/90-disable-mouse.rules:1 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:06:00.3/usb3/3-6/3-6:1.1/power/wakeup}, ignoring: No such file or directory
```

This is why I need `ATTR{../power/wakeup}="disabled"` to prevent these error messages.

**Comment by aafeijoo-suse** [comment]
Are your issues before or after switching root? i.e., could you exclude you custom rules file from the initrd and check if the journal displays the error anyway (after the "Switching root" message)?

**Comment by Zesko** [comment]
> could you exclude you custom rules file from the initrd and check if the journal displays the error anyway (after the "Switching root" message)?

If I removed this custom rules file, the journal does not displays these error messages.

**Comment by aafeijoo-suse** [comment]
I can't find anywhere in the code that adds all the rules from /etc/udev/rules.d to the initrd... what I mean is, try the following:
- Place your custom rules file in /etc/udev/rules.d
- Rebuild the initrd
- Boot the system and get the content of `journalctl -b | grep -e "90-disable-mouse" -e "Switching root"`

If the error is displayed after "Switching root", the issue is with your rule/systemd, not with dracut.

**Comment by aafeijoo-suse** [comment]
It's still not clear to me if your rule is included in the initrd. Could you show the output of `lsinitrd | grep etc/udev/rules.d`

**Comment by aafeijoo-suse** [comment]
> I see initramfs does not have `90-disable-mouse.rules`

That's what I was suspecting. So it's not our bug, it doesn't matter if the rule is correct or incorrect, it's not processed during the initrd phase.

**Comment by Zesko** [comment]
There are my 3 custom rules files in `/etc/udev/rules.d/` but they are not included in Dracut v059 initramfs.

However, I do not understand why **Dracut v059 works fine** with this custom rules that contains the line:
```
... RUN+="/bin/sh -c 'echo disabled > /sys$env{DEVPATH}/../power/wakeup'"
```
**but Dracut v059 does not work with the other line:** 
```
... ATTR{../power/wakeup}="disabled"
``` 


**mkinitcpio** works fine with both lines.  That's why I thought it was Dracut that has issue with `ATTR{../power/wakeup}="disabled"`
