### ISSUE TITLE
Gentoo test container regressed by upstream changes

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2326]
First day of container generation failure: May-8.

Failed run: https://github.com/dracutdevs/dracut/actions/runs/4914623282

Likely caused by default python version change: 
 - https://gentoobrowse.randomdan.homeip.net/news/2023-04-02-python3-11
 - https://forums.gentoo.org/viewtopic-p-8786747.html

**Comment by aafeijoo-suse** [comment]
It seems the Fedora container is also [failing](https://github.com/dracutdevs/dracut/actions/runs/4916355676/jobs/8779995944?pr=2327#step:6:151) because of this:

https://github.com/dracutdevs/dracut/blob/6178a9d83ffad67fa371cef2ff3f5bbb337bc8b7/test/container/Dockerfile-Fedora-latest#L40
