### ISSUE TITLE
Test 60 seems to fail on most distros

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2328]
The test runs very well on Fedora. I do not remember seeing a failure on Fedora.

Seems to fail on opensuse
https://github.com/dracutdevs/dracut/actions/runs/4932181615

Seems to fail on latest Arch
https://github.com/dracutdevs/dracut/actions/runs/4910624311

..and on latest debian
https://github.com/dracutdevs/dracut/actions/runs/4911580441

..with similar error message

grep: /run/initramfs/state/etc/sysconfig/network-scripts/ifcfg-*: No such file or directory

Related: https://github.com/dracutdevs/dracut/pull/2189

@bengal @aafeijoo-suse

**Comment by bdrung** [comment]
ifcfg is RedHat/Fedora/etc specific. Debian and derivatives do not have ifcfg.
