### ISSUE TITLE
/etc/fstab.empty is created and not used

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2371]
dracut creates /etc/fstab.empty for each generated initramfs and this does not seem to be used for anything. Get rid of it.

**Comment by aafeijoo-suse** [comment]
It's for `fsck`. See [fsck(8)](https://manpages.opensuse.org/Tumbleweed/util-linux/fsck.8.en.html):

> If no filesystems are specified on the command line, and the -A option is not specified, fsck will default to checking filesystems in /etc/fstab serially. This is equivalent to the -As options.
> ...
> FSTAB_FILE
> This environment variable allows the system administrator to override the standard location of the /etc/fstab file. It is also useful for developers who are testing fsck.
