### ISSUE TITLE
CONFIG_ACPI_INITRD_TABLE_OVERRIDE name change?

### ISSUE THREAD

**Issue by puellanivis** [dracutdevs/dracut#240]
My 4.11 kernel is using the kernel config parameter CONFIG_ACPI_TABLE_UPGRADE, not the one dracut is looking for.

This means I have to patch my dracut every time it updates…

**Comment by haraldh** [comment]
fixed with commit 940169e8d8e500498a3f350b2b3f341ae6548492

**Comment by puellanivis** [comment]
Gracias! :)
