### ISSUE TITLE
remove unused config examples

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2415]
https://github.com/dracutdevs/dracut/tree/master/dracut.conf.d

The examples that are used can be kept.

As an example, I do not think anybody is using the gentoo examples. Not even gentoo packaging.

**Comment by aafeijoo-suse** [comment]
AFAIK suse and fedora examples are being used downstream, but why do you tag this as a bug?

**Comment by aafeijoo-suse** [comment]
> Thanks @aafeijoo-suse , this is useful to know. I was looking for how it is used downstream, but could not find it - maybe I was looking at the wrong places. Can you help me with some pointers how `suse.conf.example` ends up in rpm packages ?

- https://github.com/openSUSE/dracut/blob/9d1fc72217f5a0d37ec4c1133b85025f9cb3996d/suse/dracut.spec#L165
- https://src.fedoraproject.org/rpms/dracut/blob/rawhide/f/dracut.spec#_249
