### ISSUE TITLE
Improve arch test container

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2422]
Install an [aur helper](https://wiki.archlinux.org/title/AUR_helpers) to make it easier to install aur packages (such us tgt)

Install the following packages to enable more testing (just like the Fedora container)
- bash-completion                                                                                                                                                                                          
- biosdevname                                                                                                                                                                                              
- bluez                                                                                                                                                                                                    
- busybox                                                                                                                                                                                                  
- bzip2                                                                                                                                                                                                    
- cifs-utils                                                                                                                                                                                               
- cryptsetup                                                                                                                                                                                               
- e2fsprogs                                                                                                                                                                                                
- f2fs-tools                                                                                                                                                                                               
- fuse3                                                                                                                                                                                                    
- iproute                                                                                                                                                                                                  
- iputils                                                                                                                                                                                                  
- kbd                                                                                                                                                                                                      
- lzop                                                                                                                                                                                                     
- memstrack                                                                                                                                                                                                
- ndctl                                                                                                                                                                                                    
- nvme-cli                                                                                                                                                                                                 
- rng-tools                                                                                                                                                                                                
- sbsigntools                                                                                                                                                                                              
- tar                                                                                                                                                                                                      
- tgt                                                                                                                                                                                                      
- tpm2-tools

**Comment by aafeijoo-suse** [comment]
Now the stale bot also works on issues?
