### ISSUE TITLE
gzip option is not in effect when microcode loading early

### ISSUE THREAD

**Issue by YoruStar** [dracutdevs/dracut#2439]
When I want to create initrd boot image files using compression, I found that the final generated image file was not compressed, The means of reproduction are as follows:

> $ dracut -f test.img --kver=$(uname -r) --gzip --no-hostonly
> $ file test.img
> $ test.img: ASCII cpio archive (SVR4 with no CRC)

I found that there is a/lib/firmware/amd ucode file in my system, this resulted in microcode loading early during the production process. If a file with the same name exists before compression, this will cause compression to fail.

I would like to know how to generate a compressed image file in this situation ？

Thanks in advance

**Comment by aafeijoo-suse** [comment]
The early microcode is not compressed, only the rest. That's why `file` thinks that everything is uncompressed.

**Comment by YoruStar** [comment]
> The early microcode is not compressed, only the rest. That's why `file` thinks that everything is uncompressed.

Thanks♪(･ω･)ﾉ

**Comment by YoruStar** [comment]
> The early microcode is not compressed, only the rest. That's why `file` thinks that everything is uncompressed.

Thanks♪(･ω･)ﾉ
