### ISSUE TITLE
Can't use loopback crypto keys to unlock multiple devices

### ISSUE THREAD

**Issue by sbrudenell** [dracutdevs/dracut#256]
If I use a commandline like

`rd.luks.uuid=abcd rd.luks.uuid=1234 rd.luks.key=key.img`

where the intent is to unlock a keyfile once and use it to `luksOpen` multiple devices with a single password entry. The `luksOpen` chain seems to happen correctly but cleanup is broken.

After unlocking 5 devices with the key, I get:
```Device /dev/mapper/keydev--dev-sdf1-key.img is not active.
Device /dev/mapper/keydev--dev-sdf1-key.img is not active.
Device /dev/mapper/keydev--dev-sdf1-key.img is not active.
Device /dev/mapper/keydev--dev-sdf1-key.img is not active.
```

spammed hundreds of times to the console, then dropped to a shell.

It looks like the problem is:
```
dracut:/# cat /lib/dracut/hooks/initqueue/finished/crypt-loop-cleanup-10-keydev--dev-sdf1-key.img.sh
[ -e "$job" ] && rm -f -- "$job"
/sbin/cryptsetup luksClose /dev/mapper/keydev--dev-sdf1-key.img
```

this is a "finished" hook trying to close the key multiple times, which fails. Other `crypt-look-cleanup-*` hooks are there but similarly trying to cleanup multiple times. By the time I get dropped to the dracut shell, I can just

```
rm /lib/dracut/hooks/initqueue/finished/crypt-loop-cleanup-*
```

and my boot succeeds.

[rdsosreport.txt](https://github.com/dracutdevs/dracut/files/1181136/rdsosreport.txt)

**Comment by haraldh** [comment]
Fixed by https://github.com/dracutdevs/dracut/pull/260
