### ISSUE TITLE
do --nofscks must set parameters？

### ISSUE THREAD

**Issue by snoweay** [dracutdevs/dracut#264]
I get the --nofscks  parameters from the help info, it says no parameters  need. But in the code of the dracut, it take the  --nofscks  as must be with parameters. 
        --long add-device: \
        --long nofscks: \
        --long ro-mnt \

If I understand it wrong, please reply to how the use of the parameters，thx.
We are expecting your reply.

**Comment by haraldh** [comment]
you are right, thank you!
