### ISSUE TITLE
network-legacy module dropped from Fedora 40 package

### ISSUE THREAD

**Issue by jmpolom** [dracutdevs/dracut#2640]
This may be the wrong place to post this issue but I'm unclear where a better place is.

Looks like the 35network-legacy module was dropped from the Fedora 40 (also rawhide) builds of the dracut-network package. Hate to say it but not everyone wants to have NetworkManager forced upon them like this. Any relevant discussion of this rather disruptive and unannounced change?

Is there forthcoming support in a module for systemd-networkd?

**Comment by aafeijoo-suse** [comment]
> This may be the wrong place to post this issue but I'm unclear where a better place is.

This is a ditro specific issue: https://pagure.io/fedora-workstation/issues

> Looks like the 35network-legacy module was dropped from the Fedora 40 (also rawhide) builds of the dracut-network package. 

https://src.fedoraproject.org/rpms/dracut/pull-request/53

**Comment by jmpolom** [comment]
I don't think this will be specific just to workstation; also didn't see a directly corresponding issue there or in fedora-server issue tracker.

 Looks like the last one is closest and sheesh. it was just thrown into that unrelated PR. What a mess.

**Comment by jmpolom** [comment]
@aafeijoo-suse can we get this re-opened? My question about support for systemd-networkd and general issue about having NetworkManager thrust upon me went unanswered.

What is the actual status of the 35network-legacy module? Is this module "obsolete" and pending removal at some point (IE: deprecated)?

In the PR that removed it from the Fedora dracut-network package it was referred to as obsolete. I can't really find any documentation in this repo that corroborates this? I'd really just like to understand what the plan is here and if dracut will eventually only support NM for networking in the initrd.

**Comment by LaszloGombos** [comment]
> My question about support for systemd-networkd

This should have been a discussion entry with a much better title and not an issue.

> My question about support for systemd-networkd ... I'd really just like to understand what the plan is here

https://github.com/dracutdevs/dracut/issues?q=is%3Aissue+is%3Aopen+systemd-networkd

**Comment by jmpolom** [comment]
> > My question about support for systemd-networkd
> 
> This should have been a discussion entry with a much better title and not an issue.

Feel free to re-title the issue to whatever works for this project. I believe the title works as good as any of the rest I see in the repo.

My question was specifically about the status of the module and where it is documented. I cannot locate any documentation indicating a deprecation status. Software requires documentation so users can use it and downstream consumers can make plans for changes. Absence of documentation is in fact an issue (not a discussion point).

What is the status of the network-legacy module? Is it deprecated? Please refer me to authoritative documentation and not a search of the github issues.

**Comment by aafeijoo-suse** [comment]
> @aafeijoo-suse can we get this re-opened? My question about support for systemd-networkd and general issue about having NetworkManager thrust upon me went unanswered.

As you can see there is a `systemd-networkd ` module upstream. I don't know if it's updated or anyone supports it.

> What is the actual status of the 35network-legacy module? Is this module "obsolete" and pending removal at some point (IE: deprecated)?

At least it will be available and supported in SUSE distros for years, I cannot speak for others. You should raise your concern in the place that removed it and deemed it obsolete.

**Comment by jmpolom** [comment]
> > @aafeijoo-suse can we get this re-opened? My question about support for systemd-networkd and general issue about having NetworkManager thrust upon me went unanswered.
> 
> As you can see there is a `systemd-networkd ` module upstream. I don't know if it's updated or anyone supports it.

I have seen the systemd-networkd module. Where is upstream? Here? I'd consider most distro packages downstream consumers. The spec for the Fedora RPM directly downloads the sources from releases on this github repo.

Are the modules in modules.d **not** directly supported or developed by the maintainers/developers active on this repo? Are these just collected modules from the "community"? It appears this repo is upstream and maintenance of the contents is coordinated here as well.

There's really no documentation I can find that clearly explains who maintains what and where. The source files themselves do not even have consistent headers and most I've looked also lack author/contact info (as can be customary in other projects).

> > What is the actual status of the 35network-legacy module? Is this module "obsolete" and pending removal at some point (IE: deprecated)?
> 
> At least it will be available and supported in SUSE distros for years, I cannot speak for others. You should raise your concern in the place that removed it and deemed it obsolete.

I can infer from your statement that it is not deprecated upstream by this project in this repo? Understand if a downstream consumer decides to nix it, but I'm asking specifically about whether it'll be maintained upstream (here?)?

**Comment by jmpolom** [comment]
@pvalena is this something you know about?
