### ISSUE TITLE
Start job for disk device hangs, Linux Zen images and snapshots fail to boot, after update from 059-6 to 101-1

### ISSUE THREAD

**Issue by krisutofu** [dracutdevs/dracut#2648]
**Description**
After updating from Dracut 059-6 to Dracut 101-1, the "start job" for the disk device looks like hanging for multiple minutes. With the update in place, all my Linux-Zen images won't boot anymore, including originally functional Linux-Zen images of previous snapshots. It's the infamous Samba Deamon failure symptom.

Detailed information can be found in my [Garuda Forum Post](https://forum.garudalinux.org/t/since-the-linux-update-from-14th-of-april-or-maybe-one-or-two-days-before-linux-zen-will-hang-when-booting/36162) which includes info about my computer setup. Unsure, if this is related to my particular device or a specific driver it comes with.

I was already suspecting or questioning the Dracut update, when it mentioned something about including Bluetooth explicitly during the Pacman update procedure.

**Distribution used**
I am using Garuda Linux.

**Dracut version**
101-1

**Init system**
Initramfs is used.

**To Reproduce**
`garuda-update` (updating Dracut) and then rebooting into Grub.

However, apparently the Garuda maintainers did not experience it and as there has not been a bug fix update in the whole last week, it probably isn't reproduced on your computers either.

**Expected behavior**
As before the update, it should not produce red error messages during the boot process. Old snapshots should not be affected by error messages and boot failures with the new Dracut version (not sure if that's just Dracut's fault). It does not need to wait for the start job to finish. I don't know, if it eventually boots because I interrupted the process after minutes of waiting.

**Comment by aafeijoo-suse** [comment]
> Dracut version
> 101-1

There is no such version in this repo.
