### ISSUE TITLE
Add bluetooth module

### ISSUE THREAD

**Issue by bl33pbl0p** [dracutdevs/dracut#270]
RFE: Add a module to pull in bluetooth related systemd units, config files, and state from /var to be able to pair and connect to bluetooth devices like keyboards in early boot which would allow the user to enter the LUKS password. bluetoothd could power on the controller automatically if the config has AutoEnable=true on the host generating the initramfs. This would work well with kernels which have their bluetooth driver built into the kernel image, or it could be added as a module in the initramfs.

**Comment by adamoa** [comment]
Hi. bluetoothd requires DBus. I prepared one module for bluetoothd and another for an adjusted version of DBus service that can start before sysinit.target. I used sed to change the service file for this. Would it be worth to submit a PR?

**Comment by andrey82k** [comment]
> I prepared one module for bluetoothd
Thank you!

> Would it be worth to submit a PR?
Sure!

**Comment by irreleph4nt** [comment]
I have commented on the PR as well. Can someone please review so this can get merged? Bluetooth connectivity in initramfs is a very useful thing to have. Thank you.

**Comment by irreleph4nt** [comment]
Not stale.

**Comment by bam80** [comment]
And how to reopen it now?

**Comment by Neurognostic** [comment]
I think someone has to reopen now, because the thread was not poked soon enough.... thanks stale bot.

**Comment by johannbg** [comment]
@Neurognostic I will be implementing this since I'm currently working on improving the systemd implementation in dracut. That work should hopefully land in the next dracut release, which should be released ca 2 weeks from now.

**Comment by bgmilne** [comment]
With the current revision of https://github.com/dracutdevs/dracut/pull/1139, I am able to use 2 different Bluetooth keyboards in dracut, e.g. when booting with `rd.break` I can enter my root password using a Bluetooth keyboard at the `Enter root password to access an emergency shell` prompt.

However, my current setup has only `/home` on LUKS, so if someone who has their rootfs on LUKS can test, that would probably be better.

Besides using e.g. https://github.com/bgmilne/dracut/commit/9133705a616d87c97c220aad98fd43ae3fc48ab4 you also need to ensure that the `systemd` module isn't omitted (e.g. by files in /etc/dracut.conf*), and regenerate your initrd/initramfs with dracut (you may want to keep a backup). Check with `lsinitrd <initramfs file>|grep bluetooth` that at least some Bluetooth-related files are included, and then reboot.

**Comment by bgmilne** [comment]
Since my last comment, I have changed my setup so both / and /home (LVM volumes) use LUKS, and I can now use either Bluetooth keyboard to enter the passphrase (that works for both) once in the initrd. I only need to move the USB cable to access GRUB if I want to change some boot parameter.
