### ISSUE TITLE
virtio-rng is not loaded early enough if fips is enabled, making virtual machines hang forever during boot

### ISSUE THREAD

**Issue by lsiudut** [dracutdevs/dracut#273]
The whole story is described here https://bugzilla.redhat.com/show_bug.cgi?id=1341280#c37 .

In short. Since v 19.6.95-1 Lorax is encorcing fips mode by default. It triggers a bit different code paths in underlying libraries, one of them is libgcrypt. In certain cases it uses `getrandom` syscall to initialize some internal entropy pools. The problem is that `getrandom` is blocking by default unless kernel non-blocking random pool get initialized.

In image built by dracut _/init_ is a symlink to `systemd` binary and its execution triggers mentioned behavior. On bare metal there's a lot of hw events that can be used to initialize kernel non-blocking random pool and it eventually happens after few seconds. On kvm-based VM there's none unless `virtio-rng` module is loaded. Therefore systemd execution lasts forever, being blocked on `getrandom`.

Our hacky solution is to replace _/init_ symlink by a small bash script that preloads `virtio-rng` module before exec to systemd.

I guess that other virtualization systems may require other modules/quirks to make them work. Surely, as for now, dracut initrd image is unusable for virtual machines provisioning when fips is enabled.

Let me know if you need more details.

**Comment by haraldh** [comment]
Moved the job to systemd https://github.com/systemd/systemd/pull/6665

**Comment by lsiudut** [comment]
@heraldh I don't think this is a good idea. The issue is caused by CentOS-only patch applied over libgcrypt... This is not related to systemd at all.

**Comment by haraldh** [comment]
@lsiudut which patch?

**Comment by lsiudut** [comment]
https://git.centos.org/commitdiff/rpms!libgcrypt.git/f268f105748f455df30c79bb1b21bb94a6575f2d;jsessionid=6i5sotd7c7a78z3ypmmozhk5

It does check if /etc/system-fips exists in the system, if so initializes some internal random pools. The problem is that it uses getrandom along the way.

Libgcrypt itself does read /etc/gcrypt/random.conf file where you can define `urandom-only` option. Maybe it would be better to follow up that setting and give up using getrandom if it is set?

Anyway, it doesn't seem like systemd issue to me :).

**Comment by haraldh** [comment]
@lsiudut It's not CentOS only.. it's RHEL

And doing this in the library constructor is evil!!

**Comment by lsiudut** [comment]
Couldn't agree more :).

**Comment by lsiudut** [comment]
Actually that's one of the reasons why I don't want to PR this. I don't feel confident what's the idea behind and have a feeling that it should be properly internally-escalated.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by lsiudut** [comment]
Yea, it seems fine atp. Thanks!

**Comment by johannbg** [comment]
Ok closing
