### ISSUE TITLE
Has dracut behaviour changed with regards to rd.lvm.lv?

### ISSUE THREAD

**Issue by jcberthon** [dracutdevs/dracut#283]
On a production machine we encountered the following problem. After upgrading to CentOS 1708 (aka 7.4), we failed on reboot. Dracut timed-out during early boot and we got the rescue shell.

After investigation it was because we moved 7 months ago the swap from one LVM volume group to another one, and we did not see that under `/etc/default/grub` there was still an entry `rd.lvm.lv=old_vg/swap`. By removing the entry and regenerating our GRUB configuration, we were able to restore our system.

What I'm trying to understand is why it was working for 7 months with CentOS 1611 (aka 7.3, dracut-033-463.el7_3.2), and I would like to learn how I could have see the problem earlier and prevented it. By booting an older Kernel with an older (not regenerated) initramfs, I was able to see that during boot, we also had a timeout after 3 minutes (190s) due to the missing LVM LV (but that was not visible in the boot output or logs), but after the timeout, the system continue booting. With CentOS 1708 (dracut-033-502.el7), that behaviour changed to after the timeout, the system stop booting and an emergency shell is opened.

I've skimmed the commit messages from the past year on the branch RHEL-7 but there was no obvious changes that seems related. I also looked at the release note for RHEL 7.4 and CentOS 1708, and did not find any relevant information.

Could someone shime in?

*PS: I am not trying to blame anyone here. I was the one who moved the LV to a new VG and did not see that the boot time was 3 minutes longer after that change, and that there was some timeout on boot. I just want to understand why the hidden problem has become real, and how I could have prevented it.*

**Comment by haraldh** [comment]
Yeah, there was a change in timeouts, which had the sideeffect to turn the failure to find the swap from a soft to a hard error.

I am sorry, and I think this will be fixed with 7.5

**Comment by jcberthon** [comment]
Hi @haraldh 

Thanks for the feedback.

Good to know this will be fixed :-) but in a way I'm happy it failed hard so I discovered about the missing configuration in our grub config and I solved our long boot time. So we have a cleaner installation. I'm still puzzled why the timeouts were not obvious when I was parsing the logs.
