### ISSUE TITLE
Please write out JobRunnningTimeoutSec=infinity and JobTimeoutSec=infinity

### ISSUE THREAD

**Issue by poettering** [dracutdevs/dracut#289]
currently, dracut turns off device timeouts by generating .device drop-ins setting JobTimeoutSec=0. This leaves JobRunningTimeoutSec= set however. Moreover "0" is actually a legacy way to turn off timeouts, please use `infinity` instead. Hence, please use the following two lines:

```
JobTimeoutSec=infinity
JobRunningTimeoutSec=infinity
```

This came up in systemd issue https://github.com/systemd/systemd/issues/6402

**Comment by lnykryn** [comment]
https://github.com/dracutdevs/dracut/pull/288
