### ISSUE TITLE
Can't reboot : dracut Warning

### ISSUE THREAD

**Issue by freeroot** [dracutdevs/dracut#295]
When I reboot my pc (Fedora 26), it displays a black screen with those lines :

mount: /oldsys/sys : filesystem was mounted, but any subsequent operation failed; Permission denied.
mount: /oldsys/proc : filesystem was mounted, but any subsequent operation failed; Permission denied.
mount: /oldsys/run : filesystem was mounted, but any subsequent operation failed; Permission denied.
mount: /oldsys/dev : filesystem was mounted, but any subsequent operation failed; Permission denied.
dracut Warning: Killing all remainning processes
[  177.254126] reboot: Restarting system
_

It stays on this screen eternally, so, I must power off to turn off my pc and boot manually.

**Comment by haraldh** [comment]
Does it work if you set selinux to permissive?

**Comment by freeroot** [comment]
I don't know because when selinux is setting to permissive (with `sudo setenforce Permissive`), it displays just a black screen without any lines but my pc neither reboot nor turn off.

**Comment by haraldh** [comment]
If you remove /run/initramfs/.need_shutdown before shutdown, does it turn off?

**Comment by freeroot** [comment]
Without /run/initramfs/.need_shutdown, with selinux set either to permissive, either to enforcing, I have always the empty black screen.

But I have now a new errors message :

[ 206.411345] nv_tco: Unexpected close, not stopping watchdog!
Kernel not configured for semaphores (System V IPC), Not using udev synchronisation code.
Rebooting.
[ 206.715739] reboot: Restarting system

I don't understand why and how to correct those new issues..

**Comment by haraldh** [comment]
Seems like a kernel/BIOS/firmware issue.. no dracut involved here.

**Comment by freeroot** [comment]
Ok, thanks
