### ISSUE TITLE
Requesting luks keys of not configured devices

### ISSUE THREAD

**Issue by Massimo-B** [dracutdevs/dracut#297]
As described in the Gentoo forums [here](https://forums.gentoo.org/viewtopic-t-1071086.html), I have an encrypted btrfs-on-luks-on-bcache. Beside that I have an encrypted swap partition. That swap partition LUKS gets opened later by OpenRC dmcrypt and passwordless via keyfile from the encrypted rootfs. This swap device is not configured in the CMDLINE but dracut still requests 2 passwords at boot, for the rootfs and the swap device:
```bash
# grep "^GRUB_CMDLINE_LINUX_DEFAULT" /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="drm_kms_helper.edid_firmware=edid/1920x1080.bin rd.vconsole.font=ter-u12n rd.vconsole.keymap=de-latin1-nodeadkeys rd.locale.LANG=de_DE.UTF-8 rd.lvm=0 rd.md=0 rd.dm=0 rd.luks.uuid=cae6cb89-57c3-4837-91a1-e28b2e2f44e0 root=LABEL=gentoo rootflags=subvol=root"
```
```bash
# dracut --help |grep Version
Version: 045
```
```bash
# cat /etc/dracut.conf.d/custom.conf 
compress="lzma"
add_dracutmodules+="bcache"
install_items+="/lib/firmware/radeon/* /lib/firmware/edid/*"
```
```bash
# cat  /proc/cmdline 
BOOT_IMAGE=/vmlinuz root=UUID=74a86765-24c7-4f9a-b4e7-884309963330 ro rootflags=subvol=root drm_kms_helper.edid_firmware=edid/1920x1080.bin rd.vconsole.font=ter-u12n rd.vconsole.keymap=de-latin1-nodeadkeys rd.locale.LANG=de_DE.UTF-8 rd.lvm=0 rd.md=0 rd.dm=0 rd.luks.uuid=cae6cb89-57c3-4837-91a1-e28b2e2f44e0 root=LABEL=gentoo rootflags=subvol=root
```
Who added the root=UUID eventhough there is a root=LABEL defined?

**Comment by haraldh** [comment]
regarding the kernel command line: this is a grub issue

regarding OpenRC dmcrypt: dracut supports that via /etc/crypttab
https://www.freedesktop.org/software/systemd/man/crypttab.html

regarding /etc/dracut.conf.d/custom.conf: please add spaces around the ```"``` enclosed contents for ```+=```:
```
add_dracutmodules+=" bcache "
install_items+=" /lib/firmware/radeon/* /lib/firmware/edid/* "
```

**Comment by haraldh** [comment]
regarding crypttab see also:
https://wiki.archlinux.org/index.php/Dm-crypt/System_configuration#crypttab

**Comment by Massimo-B** [comment]
I don't have a crypttab yet, isn't that a pure systemd feature?

You mean crypttab supports opening further LUKS devices? Where is that related to dracut, because using the rootfs /etc/crypttab is already outside of the initramfs?
I don't have issues opening the swap device.

My issue is that dracut asks for 2 passwords but it should only ask for one.

**Comment by haraldh** [comment]
With the help of ```plymouth``` dracut will only ask once for the password.

**Comment by haraldh** [comment]
https://www.freedesktop.org/wiki/Software/Plymouth/

**Comment by Massimo-B** [comment]
Graphical boot animation solves input of encryption password? If so, then something is wrong about the design or just working accidentally. Is there any reason to do that in the plymouth module?

**Comment by haraldh** [comment]
Well, plymouth also works in text mode. It is our common way to get user input in the early boot.

**Comment by haraldh** [comment]
What do you suggest? Save the password in a file?

**Comment by Massimo-B** [comment]
You are assuming some knowledge about what you mean by "plymouth will only ask once"... so let me guess what you mean with that. The password is requested once and used 2 times for 2 LUKS devices using the same password? Who would do that? Why not a file? Duplicating passwords does not duplicate any security.
But please let us stay on topic of this issue. I configured the CMDLINE to open exactly one LUKS device, then dracut searches for others and even tries to open them. This leads to several questions:
* Why do I need to configure a LUKS device if dracut is searching for others anyway?
* Why does dracut search for LUKS devices that are not defined?
* Why does dracut violate the dracut.html manuals that say

>    rd.luks.uuid=<luks uuid>
           only activate the LUKS partitions with the given UUID.

And now with you recommending to use plymouth:
* Why do I need to add the plymouth module if I don't use plymouth?

_I'm going to look for plymouth later, though I preferred fbsplash in the old days._

**Comment by Massimo-B** [comment]
And about
> It is our common way to get user input in the early boot.
What is wrong about the usual LUKS password input? That already works. even if plymouth has its graphical replacement for that.

**Comment by haraldh** [comment]
Could you give me /run/initramfs/rdsosreport.txt booting with "rd.break rd.debug" on the kernel command line added. Just exit the shell in between.
Then I can debug why the double ask is happening

**Comment by Massimo-B** [comment]
[rdsosreport.txt](https://github.com/dracutdevs/dracut/files/1430502/rdsosreport.txt)

**Comment by haraldh** [comment]
yeah:
/etc/cmdline.d/90crypt.conf in the initramfs was automatically created and contains:
```
 rd.luks.uuid=luks-e58808c3-28c6-4d94-b55e-81f123a7d20c rd.luks.uuid=luks-cae6cb89-57c3-4837-91a1-e28b2e2f44e0
```
In hostonly mode, dracut finds out about your root device and swap device.
If hostonly_cmdline is not explicitly set to "no", dracut will also create a default kernel command line.
For Fedora this is set to "no" by default.
The swap partition is added, because to resume from suspend, you need to unlock the swap partition first.

If you don't want thist, set 
```
# echo 'hostonly_cmdline="no"' > /etc/dracut.conf.d/my.conf
```

Sorry for the hassle.

**Comment by Massimo-B** [comment]
Thank you very much!
However now I get what it means to resume from encrypted swap, which I also like to do in the next step as decribed in the Gentoo forums [here](https://forums.gentoo.org/viewtopic-t-1071086.html). We can add a separate issue for this here..
Does this always need to enter the password for the resume partition swap? I prefer for both normal boot and hibernation resumption to use a keyfile for swap stored on the root LUKS.

**Comment by Massimo-B** [comment]
Forwarded new issue to #306.
