### ISSUE TITLE
cat: '2>/dev/null': No such file or directory

### ISSUE THREAD

**Issue by yuwata** [dracutdevs/dracut#301]
With recent snapshot d976e193256407b7839b02cb888ea95a8d442180, I get the following message.
```
$ sudo dracut -f /boot/initramfs-4.13.10-200.fc26.x86_64.img
cat: '2>/dev/null': No such file or directory
```
Such message does not appear with 4b758ebe2288e594a1f522334192e5d8fa1f96af.
I am not sure but I guess e190224345f3a8b2f9e85d84bc879dd96bf265da causes this.

Note that the created initrd image works fine.

**Comment by haraldh** [comment]
sorry... fixed by 18a5011ff2465b7923db907100f0f59f01908c4e
