### ISSUE TITLE
Software raid is not reliably marked as clean during shutdown

### ISSUE THREAD

**Issue by cbvms123** [dracutdevs/dracut#342]
When I installed my new machine with a BIOS based RAID, the RAID was rebuild whenever the machine was rebooted. I was able to track this issue down to mdraid module and applied a fix which finally made my system work:

A) mdraid-waitclean.sh

change:
mdadm $_offroot -W "$md" >/dev/null 2>&1
to:
mdadm $_offroot --wait-clean "$md" >/dev/null 2>&1

B) module-setup.sh
Add 
inst_hook pre-shutdown 40 "$moddir/mdraid-waitclean.sh"
so that the script is called just before shutting down.

**Comment by haraldh** [comment]
Oh, A) is clearly a "bug" ... seems like ```-W``` should really be ```--wait-clean```

But B) should be covered with 
```
module-setup.sh:    inst_hook shutdown 30 "$moddir/md-shutdown.sh"
```
Where md-shutdown.sh has:
```
    mdadm $_offroot -vv --wait-clean --scan| vinfo
```
If you boot your system, does ```/run/initramfs/shutdown``` exist?

**Comment by haraldh** [comment]
fix for A)
https://github.com/dracutdevs/dracut/commit/bc4ce61efce3e2d8b2be4f4e3e5fdef6ca08409f

**Comment by cbvms123** [comment]
There is no /run/initramfs/shutdown  on my system after booting. I am on Fedora 27.

**Comment by haraldh** [comment]
what is the output of:
```
# ls -l /dev/md[0-9_]*
```
?

**Comment by cbvms123** [comment]
```
# ls -l /dev/md[0-9_]*

brw-rw----. 1 root disk   9, 126  3. Jan  09:27 /dev/md126
brw-rw----. 1 root disk 259,   0  3. Jan  09:27 /dev/md126p1
brw-rw----. 1 root disk 259,   1  3. Jan  09:27 /dev/md126p2
brw-rw----. 1 root disk 259,   2  3. Jan  09:27 /dev/md126p3
brw-rw----. 1 root disk   9, 127  3. Jan  09:27 /dev/md127

```
```
# cat /proc/mdstat

Personalities : [raid1] 
md126 : active raid1 sda[1] sdb[0]
      1953511424 blocks super external:/md127/0 [2/2] [UU]
      
md127 : inactive sda[1](S) sdb[0](S)
      6056 blocks super external:imsm
       
unused devices: <none>

```
```
# dmsetup ls --tree

fedora_linux-swap (253:1)
 └─ (259:2)
fedora_linux-root (253:0)
 └─ (259:2)
fedora_linux-home (253:2)
 └─ (259:2)

```

**Comment by haraldh** [comment]
oops, I meant: ```/run/initramfs/.need_shutdown```

**Comment by cbvms123** [comment]
Yes there is a /run/initramfs/.need_shutdown after booting. 

In order to find more evidence what may be wrong during shutdown I enabled 
rd.debug rd.break=pre-shutdown rd.break=shutdown

This revealed the below messages before powering off:

```
dracut:Disassembling device-mapper devices
dracut: Waiting for mdraid devices to be clean.
dracut: mdadm --vv --wait-clean --scan
dracut: Disassembling mdraid devices.
dracut: mdadm --vv --stop --scan
mdadm: stopped /dev/md126
mdadm: Error connecting monitor with /run/mdadm/md127.sock: no such file or directory
mdadm: stopped /dev/md127

dracut Warning: Break before shutdown
```

This leads to https://bugzilla.redhat.com/show_bug.cgi?id=1375002 and related issues. With the difference that the .sock file cannot be found.

**Comment by haraldh** [comment]
Seems like https://bugzilla.redhat.com/show_bug.cgi?id=1379044 was never fixed

**Comment by haraldh** [comment]
I would file a bug for mdadm for
```
mdadm: Error connecting monitor with /run/mdadm/md127.sock: no such file or directory
```

**Comment by haraldh** [comment]
There is not much dracut can do here.
