### ISSUE TITLE
unable to pxe boot a LiveDVD iso that is using dracut like CentOS, Red Hat, openSUSE

### ISSUE THREAD

**Issue by beta-tester** [dracutdevs/dracut#348]
hello,
i have project [RPi-PXE-Server](https://github.com/beta-tester/RPi-PXE-Server/tree/testing) where  tiny [Raspberry Pi](https://en.wikipedia.org/wiki/Raspberry_Pi) computer acts as a pxe server.
on that pxe server i provide multiple Linux distribution to boot straight into its live dvd iso image contents.
for nearly all debian based iso images it is easily possible to pxe boot into its iso content.
on pxe server side: mount linux iso image and export its content via nfs. and provide pxe boot menu entries.
super easy and it works very well.
## a debian example
```
LABEL Debian x64
    KERNEL /nfs/debian-x64/live/vmlinuz-4.9.0-4-amd64
    APPEND initrd=/nfs/debian-x64/live/initrd.img-4.9.0-4-amd64 netboot=nfs nfsroot=10.11.12.13:/srv/nfs/debian-x64 ro boot=live config
    TEXT HELP
        Boot to Debian x64 Live LXDE
        User: user, Password: live
    ENDTEXT
```
but all linux live dvd iso images, that are using dracut, i have huge problems to get those linux distributions to work to boot into its live os.

## i tried several dracut boot parameters with no success:
```
LABEL CentOS x64
    KERNEL /nfs/centos-x64/isolinux/vmlinuz0

# dracut: FATAL: Don't know how to handle 'root=live:nfs:10.11.12.13:/srv/nfs/centos-x64';
#APPEND initrd=/nfs/centos-x64/isolinux/initrd0.img root=live:nfs:10.11.12.13:/srv/nfs/centos-x64 root-path=/LiveOS/squashfs.img rootfstype=auto ro rd.live.image rd.luks=0 rd.md=0 rd.dm=0 vga=794 rd.shell

# dracut: FATAL: Don't know how to handle 'root=live:nfs:10.11.12.13:/srv/nfs/centos-x64/LiveOS/squashfs.img';
#APPEND initrd=/nfs/centos-x64/isolinux/initrd0.img root=live:nfs:10.11.12.13:/srv/nfs/centos-x64/LiveOS/squashfs.img rootfstype=auto ro rd.live.image rd.luks=0 rd.md=0 rd.dm=0 vga=794 rd.shell

# mount.nfs: mountpoint /sysroot is not a directory
#APPEND initrd=/nfs/centos-x64/isolinux/initrd0.img root=nfs:10.11.12.13:/srv/nfs/centos-x64/LiveOS/squashfs.img rootfstype=auto ro rd.live.image rd.luks=0 rd.md=0 rd.dm=0 vga=794 rd.shell

# Warning: Could not boot.
# Warning: /dev/mapper/live-rw does not exist
# Starting Dracut Emergency Shell
APPEND initrd=/nfs/centos-x64/isolinux/initrd0.img root=nfs:10.11.12.13:/srv/nfs/centos-x64 root-path=/LiveOS/squashfs.img rootfstype=auto ro rd.live.image rd.luks=0 rd.md=0 rd.dm=0 vga=794 rd.shell

    TEXT HELP
        Boot to CentOS LiveGNOME
        User: liveuser
    ENDTEXT
```
### when try to use nfs:
```
mount.nfs: mountpoint /sysroot is not a directory
```
or here, the mount point /sysroot is mounted successfully and i can list all the files
/sysroot/isolinux/...
/sysroot/LiveOS/squashfs.img
/sysroot/LiveOS/...
but even then the os could not boot
```
Warning: Could not boot.
Warning: /dev/mapper/live-rw does not exist
Starting Dracut Emergency Shell
```
and here, the keyword "**_live_**" is unknown, the types "**_http_**://10.11.12.13/...", "**_tftp_**://10.11.12.13/..." are unknown
```
dracut: FATAL: Don't know how to handle 'root=live:nfs:10.11.12.13:/srv/nfs/centos-x64';
```
```
dracut: FATAL: Don't know how to handle 'root=live:http://10.11.12.13/LiveOS/squashfs.img';
```
```
dracut: FATAL: Don't know how to handle 'root=http://10.11.12.13/LiveOS/squashfs.img';
```
```
dracut: FATAL: Don't know how to handle 'root=tftp://10.11.12.13/squashfs.img';
```

i tried:
CentOS-7-x86_64-LiveGNOME-1708.iso
Fedora-Workstation-Live-x86_64-26-1.5.iso
to get boot into live os by using its live dvd iso images - unfortunately no success.
i searched in forums of Red Hat, Fedora, CentOS and man pages of dracut... none of the information and none boot parameter combination i used worked.
any idea what's going on?
is this a bug in dracut?
when i burn the iso images to a physical media (DVD) it boots, but not via pxe, nfs (tftp or http).

**Comment by beta-tester** [comment]
ok, unfortunately after my first fail with Fedora to get it pxe boot i tried all the other parameter combinations CentOS only.
now i realized, that Fedora and CentOS are very different in their boot behaviour.

with Fedora-Workstation-Live-x86_64-27-1.6.iso and the following pxe boot entry
i can get Fedora to PXE boot.
```
LABEL Fedora x64
    KERNEL /nfs/fedora-x64/isolinux/vmlinuz
    APPEND initrd=/nfs/fedora-x64/isolinux/initrd.img root=live:http://10.11.12.13/fedora-x64/LiveOS/squashfs.img ro rd.live.image rd.lvm=0 rd.luks=0 rd.md=0 rd.dm=0 vga=794
    TEXT HELP
        Boot to Fedora Workstation Live
        User: liveuser
    ENDTEXT
```
thanks of the hint of **_Aleksandar Kostadinov_** at [[solved] PXE boot Fedora live dvd results in timeout](https://ask.fedoraproject.org/en/question/113280/solved-pxe-boot-fedora-live-dvd-results-in-timeout/?answer=115533#post-id-115533)

http is not my preferred way, i would prefer NFS, but up to now it is the best and only way i got.

but how to get it work via NFS
and what is different between Fedora 27 and CentOS 7 boot process...?

**Comment by beta-tester** [comment]
CentOS and openSUSE shows up the error message

`dracut: FATAL: Don't know how to handle 'root=live:http://10.11.12.13/nfs/centos-x64/LiveOS/squashfs.img';
`

`dracut: FATAL: Don't know how to handle 'root=live:http://10.11.12.13/nfs/opensuse-x64/LiveOS/squashfs.img';`

an idea where that issue is coming from?

Fedora-Workstation-Live-x86_64-28-1.1.iso is able to pxe-boot with that `root=live:<url>` option very well.

**Comment by haraldh** [comment]
The initramfs you are using does not include the live dracut module, I guess.

**Comment by ITAC2018** [comment]
hola buen dia estoy tratando de que mi pxe corra la iso de fedora o ubunto pero me aparece un error de dracut o en fedora initrd-switch-root.service no me deja avanzar de hay e probado con varias opciones de arranque que e visto en redhat y los que han dejado comantado pero aun me persiste la averia aclaro que en la empresa donde trabajo tenemos un dhcp interno por lo cual al pxe no le e instalado ni configurado el dhcp 

agadeceria quien me puede ayudar con este lio 

KERNEL fedora/vmlinuz 
APPEND fedora/initrd=initrd.img inst.stage2=http://192.168.200.30/ inst.repo=http://192.168.200.30 ip=dhcp root=live:http://192.168.200.30/LiveOS/squashfs.img


esta es la ultima configuración que probé y aun sigue con la misma molesta que nombre anterior mente

**Comment by beta-tester** [comment]
@ITAC2018 i got Fedora 29 and ubuntu 16.04 ..18.10, ubuntu Daily (Disco) pxe booting...
take a look to my [RPi-PXE-Server](https://github.com/beta-tester/RPi-PXE-Server) project
(specially to the p2-include-menu.sh file)

BTW: ubuntu isn't using dracut.

but CentOS, OpenSUSE still arn't pxe boot.

**Comment by ITAC2018** [comment]
Gracias por los menús pero ninguno me sirvió ya que ellos apuntan como si todo estuviera en una misma unidad de disco y en mi caso yo lo tengo en 2 particiones y esto afecta al momento de modificar lo solo cuadre fedora y linux-mint arranca pero se queda en el icono de carga y no pasa de hay si sabes una solución lo agradecería

**Comment by beta-tester** [comment]
i don't know what you mean with 2 partitions.

when i taks your example an apply it to my menu, then it would give somehting like:
```
LABEL FEDORA_X64
    MENU LABEL Fedora x64
    KERNEL FEDORA_X64/isolinux/vmlinuz
    INITRD FEDORA_X64/isolinux/initrd.img
    APPEND root=live:http://192.168.200.30/FEDORA_X64/LiveOS/squashfs.img ro rd.live.image rd.lvm=0 rd.luks=0 rd.md=0 rd.dm=0 vga=794
```
... and this is not working for you?
i don't know the folder structure and what software of your setup. i use the debian package pxelinux and from that i use the lpxelinux.0 module (/usr/lib/PXELINUX/lpxelinux.0), to be able to use http as source instead of tftp only for a bit more flexibility.
so it does not matter where the files are located as long they are accessable via network.

**Comment by beta-tester** [comment]
oops... sorry i pushed the wrong button

**Comment by ITAC2018** [comment]
already fedora rips me but linux mint does not start me it stays stuck in the beginning and from there it does not happen

label 2
      MENU LABEL ^2) linux-mint-xfce
      default
      KERNEL linux-mint/vmlinuz
      INITRD linux-mint/initrd.lz
      APPEND boot=live username=user hostname=saucy live-config quiet union=overlayfs noswap edd=on locales=es_ES.UTF-8 keyboard-layouts=es ocs_live_run="ocs-live-general" ocs_live_batch=no video=uvesafb:mode_option=1024x768-32 ip=frommedia splash netboot=nfs nfsroot=192.168.200.27:/linux-mint

**Comment by beta-tester** [comment]
i never tried linux-mint, but as i saw is mint based on ubuntu and this doesn't use dracut at all...
so, everything you are asking here is a bit off-toppic.
you can try the boot parameters for ubuntu, debian or devuan.

**Comment by ITAC2018** [comment]
ok sorry for asking I thought this was free for one to solve the doubts but thank you

**Comment by beta-tester** [comment]
maybe a better place to continue this conversation is on my project and you make a request for adding linux-mint ;)

**Comment by beta-tester** [comment]
@ITAC2018 i just added linux-mint to my project.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by beta-tester** [comment]
it is still an issue, that dracut does not understand how to handle kive:nfs, live:http, live:ftp
for openSUSE, they implemented AoE that i can use as workaround for the lack of support in dracut.
see https://bugzilla.suse.com/show_bug.cgi?id=1099548
but this AoE method is not working for CentOS nor RedHad

**Comment by johannbg** [comment]
@beta-tester sorry I dont follow, dracut has understood how to handle live: foo since livenet module got merged ( roughly 8 years ) and for that to work that module needs to be included/enabled in relevant *downstream* initrd's of what is being fetched  ( Has been included only in the initrd on the Fedora Live's since Fedora 24, it is not included in the initrd on Fedora from the dvd/boot.iso or tree so trying to use those wont work). You need to file an issue *downstream* requesting that livenet module be included in the initrd's being fetched.

**Comment by johannbg** [comment]
Closing this issue since it's an downstream issue.
