### ISSUE TITLE
Dracut build process takes a long time scanning large number of LVM volumes

### ISSUE THREAD

**Issue by kstange** [dracutdevs/dracut#349]
Hi,

I have a system which has a very large number of iSCSI-based LVM volumes and dracut can take an incredibly large amount of time to scan these volumes for no particular benefit when building a new initramfs.  I determined the functions check_vol_slaves_all and check_vol_slaves from /usr/lib/dracut/dracut-functions.sh are responsible for all of this time and that by commenting out these two calls, the process finishes much faster, with no detriment to my system.  I do not need dracut to provide availability of LVM during the initramfs boot process, so I really just need a way to skip this.  The package version is dracut-033-502.el7_4.1.x86_64 from CentOS 7.4.

I'm posting this here at the suggestion of haraldh from IRC.

time dracut -f --debug test.img 2> dracut.log

real	26m1.560s
user	3m32.042s
sys	22m44.516s

I've attached the output to this issue.
[dracut.log.gz](https://github.com/dracutdevs/dracut/files/1620185/dracut.log.gz)

**Comment by kstange** [comment]
Just to compare, with the two indicated function calls commented out:

time dracut -f --debug test.img 2> dracut.log

real	1m55.555s
user	0m30.177s
sys	1m37.712s

**Comment by haraldh** [comment]
Does commit 9ed6eb741f0bc0178167e7063751eb2bb4ac6de5 with your issue?

**Comment by kstange** [comment]
I can confirm significant improvement nearly identical to having the functions commented out running this command:

time dracut -f --debug test.img 2> dracut.log

Original code:

real	29m41.520s
user	3m44.359s
sys	26m11.600s

Functions commented out:

real	2m7.550s
user	0m31.006s
sys	1m49.991s

New code:

real	2m7.209s
user	0m31.060s
sys	1m49.643s

I haven't tested the functionality is equivalent, because as noted I do not need dracut to make LVM available that early in boot.

Thank you so much for a very quick fix.

**Comment by haraldh** [comment]
@lnykryn looks like a backport candidate

**Comment by lnykryn** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1534966
