### ISSUE TITLE
dracut does not building 

### ISSUE THREAD

**Issue by betcher** [dracutdevs/dracut#357]
Hi.  Dracut does not  compiling in some  systems after this commit:
https://github.com/dracutdevs/dracut/commit/ef84ce2521a5b0463d9e8c9ced101d03cec4937c#diff-3af9385298fa8fd2699c5451ecfaf58e
Then i discard this commit i can build latest  version of dracut. 

make errors:

user@MagOS dracut $ LC_MESSAGES=en make
cc -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -I/usr/include/kmod-20    -c -o install/dracut-install.o install/dracut-install.c
install/dracut-install.c: In function ‘install_modules’:
install/dracut-install.c:1400:20: warning: implicit declaration of function ‘kmod_get_dirname’ [-Wimplicit-function-declaration]
         abskpath = kmod_get_dirname(ctx);
                    ^
install/dracut-install.c:1400:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         abskpath = kmod_get_dirname(ctx);
                  ^
cc -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -I/usr/include/kmod-20    -c -o install/hashmap.o install/hashmap.c
cc -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -I/usr/include/kmod-20    -c -o install/log.o install/log.c
cc -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -I/usr/include/kmod-20    -c -o install/strv.o install/strv.c
cc -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -I/usr/include/kmod-20    -c -o install/util.o install/util.c
cc  -o install/dracut-install install/dracut-install.o install/hashmap.o install/log.o install/strv.o install/util.o  -lkmod 
install/dracut-install.o: In function `install_modules':
/home/user/Programming/fork/uird/dracut/install/dracut-install.c:1400: undefined reference to `kmod_get_dirname'
collect2: error: ld returned 1 exit status
make: *** [Makefile:64: install/dracut-install] Error 1

**Comment by haraldh** [comment]
you need a newer kmod devel >= 23 package installed
