### ISSUE TITLE
Bump version in dracut.asc

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#369]
I'm not familiar with the dracut release process, but if there is a checklist, bumping the release version and date should be added. 

In theory, this could be done through variables (dynamic replacement), but especially the date would make the builds non-reproducible. Also, the release number is not indicated anywhere except for the NEWS file (and we surely wouldn't want to parse it from there).

Either way, the current version statement `v3.0, October 2013` is most certainly wrong :)

**Comment by haraldh** [comment]
yeah 😄 , I am open for PRs

**Comment by danimo** [comment]
Well, the idea was to discuss how that PR should look. If I am submitting a static bump now, nothing really changes.
