### ISSUE TITLE
Infinite loop in check_block_and_slaves_all

### ISSUE THREAD

**Issue by judu** [dracutdevs/dracut#373]
# The issue
Since I updated to 4.15.0 (then 4.15.1), I'm unable to run dracut to update my kernel in by /boot partition. dracut hangs and then dumps core after exhausting process numbers. Looks like an infinite loop.

## My system

I'm using a nvme ssd disk named "nvme0n1". It has two partitions: an EFI one and a luks encrypted btrfs volume. So in `/dev` I have `/dev/dm-0` that is referenced to by `/dev/mapper/root`. `/dev/mapper/root` is the mapped un-encrypted volume used as a btrfs volume.

I also use btrfs submodules, so here is my mount output:

```
/dev/mapper/root on / type btrfs (rw,noatime,compress=zlib:3,ssd,discard,space_cache,subvolid=257,subvol=/exherbo)
/dev/mapper/root on /home type btrfs (rw,noatime,compress=zlib:3,ssd,discard,space_cache,subvolid=258,subvol=/home)
```

## What happens
I tracked it down in check_block_and_slaves_all. 
So, dracuts tries to `check_block_and_slaves_all _get_fs_type $(get_maj_min "/dev/dm-0")`. The value of `get_maj_min "/dev/dm-0"` is `249:0`.

1. `check_block_and_slaves_all` tries to read `/sys/dev/block/249\:0/../dev` (it fails) then reads `/sys/dev/block/249\:0/slaves/nvme0n1p2/dev` which reads `259:2`.

2. Then it recursively calls itself with `259:2`, reads `/sys/dev/block/259\:2/../dev`, which reads `259:0`.

3. Then it recursively calls itself with `259:0`, reads `/sys/dev/block/259\:0/../dev`, which reads… `249:0`.

4. Start back at 1.

## What I tried

I tried with/without MULTIPATH kernel options (tried 10 times, enabling/disabling options) and nothing changed: with linux 4.15.{0,1} dracut loops forever.

**Comment by judu** [comment]
(It can be a kernel bug, though.)

**Comment by haraldh** [comment]
which dracut version is this?

**Comment by haraldh** [comment]
Does it work with older kernels?

**Comment by judu** [comment]
It happens with 0.46 and yesterday's master. (Tried both before complaining)

Works with kernel 4.13.x and 4.14.x. Doesn't work with kernel 4.15.{0,1,2}.

I'm open to more tests. :)

**Comment by judu** [comment]
I just tried with my added logs, and it turns out that:
 - **before** Linux 4.15, `get_maj_min /dev/dm-0` returns `250:0`. Which loops to `259:2`, which loops with `259:0`, then with `249:0` which does not exist in `/sys/dev/block/`.
 -  **starting at** Linux 4.15, `get_maj_min /dev/dm-0` returns `249:0`. Which loops to `259:2` -> `259:0` -> `249:0` -> `259:2` -> …

**Comment by keithbusch** [comment]
Do you happen to have CONFIG_NVME_MULTIPATH=y in your 4.15 kernel config?

**Comment by judu** [comment]
Yes, I tried all the options before posting any issue.

With CONFIG_NVME_MULTIPATH=y, without it, I tried with and without every options having multipath and nvme in their names.

My current kernel config:

```
# NVME Support
CONFIG_NVME_CORE=y
CONFIG_BLK_DEV_NVME=y
CONFIG_NVME_MULTIPATH=y
# CONFIG_NVME_FC is not set
CONFIG_NVME_TARGET=y
# CONFIG_NVME_TARGET_LOOP is not set
# CONFIG_NVME_TARGET_FC is not set
CONFIG_RTC_NVMEM=y
CONFIG_NVMEM=y
CONFIG_DM_MULTIPATH=y
CONFIG_DM_MULTIPATH_QL=y
CONFIG_DM_MULTIPATH_ST=y
```

I think I enabled and disablend each and everyone of these. Some broke my boot ;)

My lspci output: https://paste.pound-python.org/raw/MgcifV0bpAcWw6WYi2uO/

I'm open to test different options if you need.

**Comment by keithbusch** [comment]
Okay, just wanted to confirm it's still broken when CONFIG_NVME_MULTIPATH disabled. When enabled, that was the single biggest change in 4.15 with how nvme interacts with the block layer. I don't have any other immediate suggestion at the moment, unfortunately.

**Comment by judu** [comment]
It is still broken with NVME_MULTIPATH disabled ;)
Right now, I survive by booting my 4.14 whenever I need to run dracut!

I posted my bug in the linux-kernel mailing list just in case. Will come back if I get something from there.

**Comment by keithbusch** [comment]
Is it possible to attach output of `ls -l /dev/{nvme,dm}*`?

**Comment by judu** [comment]
```
brw-rw---- 1 root disk 249, 0 févr. 15 14:38 /dev/dm-0
crw------- 1 root root 249, 0 févr. 15 14:38 /dev/nvme0
brw-rw---- 1 root disk 259, 0 févr. 15 14:38 /dev/nvme0n1
brw-rw---- 1 root disk 259, 1 févr. 15 14:38 /dev/nvme0n1p1
brw-rw---- 1 root disk 259, 2 févr. 15 14:38 /dev/nvme0n1p2
```
As a bonus:

```
lrwxrwxrwx 1 root root       7 févr. 15 14:38 /dev/mapper/root -> ../dm-0
```

And `/dev/dm-0` is `/dev/nvme0n1p2` after cryptsetup (luks) has handled it.

**Comment by keithbusch** [comment]
Okay, the dm-0 maj/min is colliding with the nvme character device's maj/min. That's the problem.

**Comment by judu** [comment]
Oh, I did not notice the "249, 0" column in the ls output O_o

Ok, would you say it's a kernel issue? A cryptsetup issue?

**Comment by keithbusch** [comment]
Well ... block and character device major/minor numbers are independent of each other, so they historically have been allowed to co-exist with the same numbers. I think the problem is that dracut is assuming the major/minor of the nvme namespace's parent device is for a block device, and that number happens to also be allocated to a block device.

**Comment by keithbusch** [comment]
Not sure what's really feasible here. Maybe the script can check the the device attributes before assuming it's a block device. Something like

`udevadm info $(readlink -f /sys/dev/block/259\:0/../)`

And verify `SUBSYSTEM=block`, or `DEVTYPE=disk` before reading `/sys/dev/block/259\:0/../dev`.

**Comment by judu** [comment]
(Ok, I just matched the Keith from linux-kernel and you… so I'm going to continue discussing this here. Ignore the question I just emailed…)

Thanks for this answer, I will try and read what dracut uses this information for, now.

**Comment by judu** [comment]
Oh, I see. In dracut-functions.sh:513:

```
[[ -b /dev/block/$2 ]] || return 1 # Not a block device? So sorry.
```

Since there is a matching block device, we do not return.

I guess there should be some kind of loop detection.

**Comment by haraldh** [comment]
Could you please test:
```bash
# Walk all the slave relationships for a given block device.
# Stop when our helper function returns success
# $1 = function to call on every found block device
# $2 = block device in major:minor format
check_block_and_slaves() {
    local _x
    [[ -b /dev/block/$2 ]] || return 1 # Not a block device? So sorry.
    if ! lvm_internal_dev $2; then "$1" $2 && return; fi
    check_vol_slaves "$@" && return 0
    if [[ -f /sys/dev/block/$2/../dev ]] && [[ /sys/dev/block/$2/../subsystem -ef /sys/class/block ]]; then
        check_block_and_slaves $1 $(<"/sys/dev/block/$2/../dev") && return 0
    fi
    [[ -d /sys/dev/block/$2/slaves ]] || return 1
    for _x in /sys/dev/block/$2/slaves/*; do
        [[ -f $_x/dev ]] || continue
        [[ $_x/subsystem -ef /sys/class/block ]] || continue
        check_block_and_slaves $1 $(<"$_x/dev") && return 0
    done
    return 1
}

check_block_and_slaves_all() {
    local _x _ret=1
    [[ -b /dev/block/$2 ]] || return 1 # Not a block device? So sorry.
    if ! lvm_internal_dev $2 && "$1" $2; then
        _ret=0
    fi
    check_vol_slaves_all "$@" && return 0
    if [[ -f /sys/dev/block/$2/../dev ]] && [[ /sys/dev/block/$2/../subsystem -ef /sys/class/block ]]; then
        check_block_and_slaves_all $1 $(<"/sys/dev/block/$2/../dev") && _ret=0
    fi
    [[ -d /sys/dev/block/$2/slaves ]] || return 1
    for _x in /sys/dev/block/$2/slaves/*; do
        [[ -f $_x/dev ]] || continue
        [[ $_x/subsystem -ef /sys/class/block ]] || continue
        check_block_and_slaves_all $1 $(<"$_x/dev") && _ret=0
    done
    return $_ret
}
```

**Comment by judu** [comment]
It works well! It generated the initrd for my 4.15.4 while my 4.15.3 was running :)
