### ISSUE TITLE
modules.d/90mdraid/module-setup.sh improper mdadm check for imsm support

### ISSUE THREAD

**Issue by LouHafer** [dracutdevs/dracut#376]
System is Fedora 27, dracut 046-8.git20180105.fc27. Root is on a cached LV on md raid array. Tried to regenerate my initramfs after adding SSD caching PV for the root LV. System failed to boot. After a fair bit of fumbling about, discovered that md-noimsm.sh was present in the initramfs. A bit more fumbling about leads to this snippet in module-setup.sh:
if ! mdadm -Q -e imsm /dev/null ; then
  inst_hook pre-trigger 30 "$moddir/md-noimsm.sh
fi
The test seems to me to be incorrect. It always fails on my system (mdadm v4.0) with the message /dev/null is not an array. Commenting out the test allows me to generate a working initramfs. I'm not sure what the correct test should be, but this isn't it.

Lou

**Comment by varlink-travis** [comment]
Hmm, that code snippet is from 2014 in commit 3564cb7c2cfe8e3e4543e5769e6364da4046eaaa .
Seems like mdadm changed behavior.

**Comment by haraldh** [comment]
Hmm, that code snippet is from 2014 in commit 3564cb7 .
Seems like mdadm changed behavior.

**Comment by haraldh** [comment]
Hmm, seems to work for me as root:
```bash
# mdadm -Q -e imsm /dev/null &>/dev/null ; echo $?
0
#  mdadm -Q -e foo /dev/null &>/dev/null ; echo $?
2
# rpm -q mdadm
mdadm-4.0-5.fc27.x86_64
```
as a normal user though, I get:
```bash
$ mdadm -Q -e imsm /dev/null &>/dev/null ; echo $?
1
$ mdadm -Q -e foo /dev/null &>/dev/null ; echo $?
2
```

Are you creating the initramfs as non-root?

**Comment by LouHafer** [comment]
Duh. I'm feeling suitably abashed. Yes, creating initramfs as non-root then copying into place as root. Apologies for the false alarm. Works just fine once I run mkinitrd as root. In retrospect, it's a wonder it worked at all as non-root.
