### ISSUE TITLE
Migrate from "initramfs tools" to "dracut".

### ISSUE THREAD

**Issue by DareDevil73** [dracutdevs/dracut#391]
Hi, I would migrate my Linux Mint 18.3 (Ubuntu 16.04) from **initramfs tools** to **dracut**.

As explained [here](https://superuser.com/questions/1315005/migrate-from-initramfs-tools-to-dracut) I need to include my initramfs customization scripts.

How could I achieve this?

Thank you so much,
Antonio

**Comment by DareDevil73** [comment]
Any idea from the Dracut dev team?

**Comment by vtolstov** [comment]
2018-04-19 10:15 GMT+03:00 Antonio Petricca <notifications@github.com>:

> Hi, I would migrate my Linux Mint 18.3 (Ubuntu 16.04) from *initramfs
> tools* to *dracut*.
>
> As explained here
> <https://superuser.com/questions/1315005/migrate-from-initramfs-tools-to-dracut>
> I need to include my initramfs customization scripts.
>
> How could I achieve this?
>
> Thank you so much,
> Antonio
>
>
> What you do with customization scripts?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by DareDevil73** [comment]
I have installed linux on loopback devices as [explained on a project of mine](https://github.com/DareDevil73/linux-on-loopback-usb/issues/1).

Thank you for your attention.
Antonio

**Comment by vtolstov** [comment]
may be i'm wrong, but you need to write you own dracut module for this kind of feature.
But i think that loop booting proper doing from grub....

**Comment by DareDevil73** [comment]
My thought was about an hypothetic automatic conversion of scripts during dracut installation.

I am going to write my own module. 

Thank you so much! ;)
