### ISSUE TITLE
Reference to executable find_btrfs_devs doesn't work

### ISSUE THREAD

**Issue by petropolis** [dracutdevs/dracut#401]
OpenSUSE Tumbleweed 20180502

When running dracut, it is running the command [find_btrfs_devs](https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1239) and this command doesn't exist anywhere.

**Comment by haraldh** [comment]
Oops.... fixed with commit bfa4e45fa74fabf70ca0d80869e3b209f300ef6d
