### ISSUE TITLE
no resolv.conf in installer if interface name < MAC-Address (sic!)

### ISSUE THREAD

**Issue by Zugschlus** [dracutdevs/dracut#410]
Hi,

this is a hairy issue my colleagues and me found when installing CentOS on Dell hardware with bonding (see https://bugs.centos.org/view.php?id=14293). If the interface name (e.g. "bond0") is lexically smaller than the MAC address as it is the case with some series of Dell R630 servers with MAC addresses starting with "ec", the installer ends up with an empty /etc/resolv.conf (and non-existing /run/initramfs/state/etc/resolv.conf in the rd.break state) and has a point in being unhappy with that.

With the help of kabe in the CentOS bug report, I believe now this is caused by the following:
* some early stage writes a /tmp/net.*.did-setup file for both the Interface ("/tmp/net.bond0.did-setup") and the MAC address ("/tmp/net.ec:f4:bb:00:00:00.did-setup").
* Code that makes it from modules.d/45ifcfg/write-ifcfg.sh in git to /lib/dracut/hooks/pre-pivot/85-write-ifcfg.sh in the installer the iterates over /tmp/net.*.did-setup (starting line 112), with the last entry that is processed winning. In the bond0 < ec case, this is the MAC address and an empty resolv.conf

This happens rather seldomly because it only happens when one already asks the installer on the command line to do bonding (or bridging, but I investigated only the bonding case) AND the MAC address is >= e0. In the non-bonding case, the same will probably happen with a MAC address >= f0 since ef < (em|ens|eth) < f0.

I think it would be a probable fix if write-ifcfg.sh would ignore all *.did-setup files for MAC addresses. Since I do not know how to re-build an installer image, I cannot test my suggestion.

Please consider fixing this for a future release.

Greetings
Marc

**Comment by f0** [comment]
Any progress here?
