### ISSUE TITLE
Error importing .evm keyring

### ISSUE THREAD

**Issue by acs3ss** [dracutdevs/dracut#420]
There is a small error in the script dracut/modules.d/98integrity/evm-enable.sh. See the code block below:

    local evm_pubid
    local line=$(keyctl describe %keyring:.evm)
    if [ $? -eq 0 ]; then
        # the kernel already setup a trusted .evm keyring so use that one
        evm_pubid=${line%%:*}
    else
        # look for an existing regular keyring
        evm_pubid=`keyctl search @u keyring _evm`
        if [ -z "${evm_pubid}" ]; then
            # create a new regular _evm keyring
            evm_pubid=`keyctl newring _evm @u`
        fi
    fi

The if statement will always evaluate to true, since it is evaluating the result of the declaration of the variable `line` as a local variable, not the result of `keyctl describe %keyring:.evm`. When booting up your system, if you do not have a .evm trusted keyring, evm_pubid will be blank and Dracut will fail to recognize any evm keyring. The fix is pasted below:

    local evm_pubid line
    line=$(keyctl describe %keyring:.evm)
    if [ $? -eq 0 ]; then
    ...

**Comment by haraldh** [comment]
Care to open a pull request?

**Comment by haraldh** [comment]
Care to open a pull request?
