### ISSUE TITLE
Additional LKM not added after upgrading to Ubuntu 18.04 (maybe be a bug in "libkmod")

### ISSUE THREAD

**Issue by antonio-petricca** [dracutdevs/dracut#426]
Hi, I am the author of [Buddy Linux](https://github.com/antonio-petricca/buddy-linux).

Today I have upgraded my Buddy Linux installation to **Linux Mint 19 (Ubuntu 18.04)**.

As part of my setup I add the [Paragon NTFS driver](https://www.paragon-software.com/home/ntfs-linux-professional/) as specified inside the [Dracut configuraion file](https://github.com/antonio-petricca/buddy-linux/blob/master/assets/dracut/20-buddy-linux-paragon.conf).

After upgrading I never get **usfd.ko** added to **initramfs**. Here an exercpt of the dracut output:

> ...
> dracut: *** Including modules done ***
> dracut-install: Failed to find module 'crc32c'
> dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.pA7YOr/initramfs --kerneldir /lib/modules/4.11.0-14-generic/ -m crc32c fuse loop netconsole ufsd
> dracut: *** Installing kernel module dependencies ***
> ...

Could somebody address me to the solution?

Thank you!
Antobio

**Comment by antonio-petricca** [comment]
Could somebody explain me how to debug dracut with GDB?

**Comment by antonio-petricca** [comment]
Hi, I managed to reproduce the issue:

I generated a dracut image into **/tmp/dracut.img** using the parameter **--keep** which held generated files into **/var/tmp/dracut.Y29ks2/initramfs**, then posted the following instructions that explain the where dracut fails:

```
root@svd026p15s:/home/antonio/projects/github/forks/dracut# /usr/lib/dracut/dracut-install         -D /var/tmp/dracut.Y29ks2/initramfs                                    --kerneldir /lib/modules/4.12.14-041214-generic/                           -m "crc32"

root@svd026p15s:/home/antonio/projects/github/forks/dracut# /usr/lib/dracut/dracut-install         -D /var/tmp/dracut.Y29ks2/initramfs                                    --kerneldir /lib/modules/4.12.14-041214-generic/                           -m "netconsole"

root@svd026p15s:/home/antonio/projects/github/forks/dracut# /usr/lib/dracut/dracut-install         -D /var/tmp/dracut.Y29ks2/initramfs                                    --kerneldir /lib/modules/4.12.14-041214-generic/                           -m "crc32 netconsole"

dracut-install: Failed to find module 'crc32 netconsole'
```
As you can see the issue is related to the **-m | --module** parameter which does not split the space separeted modules list!

**Comment by antonio-petricca** [comment]
I have debugged **dracut-install** by _gdb_ using the dracut **master** branch sources, and it found that in **dracut-install.c** at line **1634** the function **kmod_module_new_from_lookup** returns a **null** modules list starting from the list provided by the command line.

Due to that fact at line **1644** the **"Failed to find module '%s'"** is reported.

I am investigating further why this happens...

**Comment by haraldh** [comment]
you should add spaces before and after ```add_drivers+=" ufsd "```

**Comment by haraldh** [comment]
Which commands did you run with the ```'crc32 netconsole'``` problem?

**Comment by antonio-petricca** [comment]
Here a small program to demostrate what I am saying:

```c
#include <libkmod.h>
#include <stdio.h>

#define _cleanup_(x) __attribute__((cleanup(x)))

static inline void kmod_module_unref_listp(struct kmod_list **p) {
        if (*p)
                kmod_module_unref_list(*p);
}

#define _cleanup_kmod_module_unref_list_ _cleanup_(kmod_module_unref_listp)

static inline void kmod_module_info_free_listp(struct kmod_list **p) {
        if (*p)
                kmod_module_info_free_list(*p);
}

#define _cleanup_kmod_module_info_free_list_ _cleanup_(kmod_module_info_free_listp)

static inline void kmod_unrefp(struct kmod_ctx **p) {
        kmod_unref(*p);
}

#define _cleanup_kmod_unref_ _cleanup_(kmod_unrefp)

int main(int argc, char** argv) {
    _cleanup_kmod_unref_ struct kmod_ctx *ctx = NULL;
    _cleanup_kmod_module_unref_list_ struct kmod_list *list = NULL;
    int err;

    //char alias[2048]    = "cryptd";
    char alias[2048]    = "ahci cryptd";

    char kerneldir[256] = "/lib/modules/4.15.0-24-generic/";

    printf("libkmod tester...\n");

    ctx = kmod_new(kerneldir, NULL);
    err = kmod_module_new_from_lookup(ctx, alias, &list);

    if (err < 0) {
        printf("Error (%d) looking for aliases \"%s\"\n.", err, alias);
        return 1;
    }

    printf("Got list pointer 0x%lx .\n.", (unsigned long)(void *)list);

    return 0;
}
```

Here the compiling command line:

```bash
#!/bin/bash

CUR_DIR=$(dirname $0)
EXE_NAME=kmod-tester

gcc -Wall *.c -lkmod -o ${EXE_NAME} && \
${CUR_DIR}/${EXE_NAME}
```

**Comment by antonio-petricca** [comment]
I have just notified the bug to the Ubuntu Team.

https://bugs.launchpad.net/ubuntu/+source/man-db/+bug/1781143

**Comment by haraldh** [comment]
why not just remove the ```""``` ???
```
/usr/lib/dracut/dracut-install -D /tmp/my-dracut --kerneldir /lib/modules/$(uname -r)/ -m crc32 netconsole
```
works as expected...
```
$ find /tmp/my-dracut -name '*.ko*'
/tmp/my-dracut/usr/lib/modules/4.18.0-0.rc0.git5.1.fc29.x86_64/kernel/drivers/net/netconsole.ko.xz
/tmp/my-dracut/usr/lib/modules/4.18.0-0.rc0.git5.1.fc29.x86_64/kernel/crypto/crc32_generic.ko.xz
/tmp/my-dracut/usr/lib/modules/4.18.0-0.rc0.git5.1.fc29.x86_64/kernel/arch/x86/crypto/crc32-pclmul.ko.xz
```

**Comment by antonio-petricca** [comment]
Hi, sure, I have tried without quotes and I got the same issue. I tried on fresh Linux Mint 19 (Ubuntu 18.04) installation, and I got the same problem:

- Have you tested it on my same distribution?
- Have you run the C sample code I have posted above?

Thank you again!

**Comment by haraldh** [comment]
well, dracut-install uses argv[] and does not process individual argv[] array entries. So if you pass "crc32 netconsole" it will not be seperated by space.

**Comment by antonio-petricca** [comment]
Sorry, but I think the problem has not been explained by me.

The dracut command line it's only an example. I'm the author of the project [Buddy Linux](https://github.com/antonio-petricca/buddy-linux) which uses [Dracut configuration files](https://github.com/antonio-petricca/buddy-linux/tree/master/assets/dracut) to add the need drivers. I never call it directly.

That configuration worked up to **Linux Mint 18.3 / Ubuntu 16.04**, and no more since **Linux Mint 19 / Ubuntu 18.04**.

I'm going to debug again **dracut-install** to provide you more informatio...

Thank you again!
;)

**Comment by haraldh** [comment]
This will never work.
```
    char alias[2048]    = "ahci cryptd";
[…]
    err = kmod_module_new_from_lookup(ctx, alias, &list);
```
kmod_module_new_from_lookup() does not lookup each space separated entry. It looks up the full string.

as for dracut-install, if you don't do ```-m "crc32 netconsole"``` but ```-m crc32 netconsole``` all should work as expected...

Maybe you had in module-setup.sh ```instmods "crc32 netconsole"``` ... just transform it to ```instmods crc32 netconsole```

**Comment by antonio-petricca** [comment]
Thank you very much!

Are you suggesting me to abandon the **.conf** file way and use **insmod** in **buddy linux** module?

**Comment by haraldh** [comment]
Yes, but let's debug your issue first.
The output of dracut with the ```--debug``` option would be interesting.

**Comment by haraldh** [comment]
see: https://github.com/antonio-petricca/buddy-linux/issues/2#issuecomment-404505527
