### ISSUE TITLE
Remote squashfs+overlayfs root (cannot combine root=live:<URL> with rd.live.overlay.overlayfs=1)

### ISSUE THREAD

**Issue by GigabyteProductions** [dracutdevs/dracut#432]
I'm trying to use a root filesystem on an HTTP-downloaded squashfs, and making it writeable with `rd.live.overlay.overlayfs=1`. For my purposes, I cannot use the old dmsquash-live block device overlays due to unreliability in how free space works.

I can achieve the live squashfs portion of my goal if outer squashfs is placed on local media and `root=live:/dev/sda` is used with `rd.live.overlay.overlayfs=1`.

However, I am finding that this does *not* work when using a URL to the outer squashfs instead of placing it on local media (this is the bug).

I've booted with `rd.debug` and captured output on a serial console. The following lines of interest are repeated until timeout:
```
[   20.779838] dracut-initqueue[367]: /bin/dracut-initqueue@37(main): check_finished
[   20.781092] dracut-initqueue[367]: /lib/dracut-lib.sh@439(check_finished): local f
[   20.786956] dracut-initqueue[367]: /lib/dracut-lib.sh@440(check_finished): for f in $hookdir/initqueue/finished/*.sh
[   20.788702] dracut-initqueue[367]: /lib/dracut-lib.sh@441(check_finished): '[' '/lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2froot.sh' = '/lib/dracut/hooks/initqueue/finished/*.sh' ']'
[   20.791628] dracut-initqueue[367]: /lib/dracut-lib.sh@442(check_finished): '[' -e '/lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2froot.sh' ']'
[   20.793116] dracut-initqueue[367]: /lib/dracut-lib.sh@442(check_finished): . '/lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2froot.sh'
[   20.798484] dracut-initqueue[367]: //lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2froot.sh@1(source): '[' -e /dev/root ']'
[   20.810182] dracut-initqueue[367]: /lib/dracut-lib.sh@442(check_finished): return 1
```

Specifically, when using `root=live:/dev/sda`, I've noticed that instead of checking for `-e /dev/root`, dracut checks for `-e /dev/sda` (which is immediately satisfied so dracut moves on). When using `root=live:<URL>` without `rd.live.overlay.overlayfs=1`, /dev/root becomes a symlink to the old overlay block device, due to: https://github.com/dracutdevs/dracut/blob/bc01f822de732d85d4bfc77bae44c6bd4abe43d7/modules.d/90dmsquash-live/dmsquash-live-root.sh#L385

Specifically when combining `root=<URL>` with `rd.live.overlay.overlayfs=1`, the check is for `-e /dev/root` but /dev/root is never symlinked to anything. A line of interest:
https://github.com/dracutdevs/dracut/blob/bc01f822de732d85d4bfc77bae44c6bd4abe43d7/modules.d/90dmsquash-live/dmsquash-live-root.sh#L379

The following patch satisfied the /dev/root symlink with something kinda sensible. I have not investigated the side effects of doing this on the rest of dracut, nor am I sure that this is the best solution.
```
diff --git a/modules.d/90dmsquash-live/dmsquash-live-root.sh b/modules.d/90dmsquash-live/dmsquash-live-root.sh
index 8f3b2bf9..6d89a88a 100755
--- a/modules.d/90dmsquash-live/dmsquash-live-root.sh
+++ b/modules.d/90dmsquash-live/dmsquash-live-root.sh
@@ -375,6 +375,7 @@ if [ -n "$overlayfs" ]; then
     else
         mount -r $FSIMG /run/rootfsbase
     fi
+    ln -s $FSIMG /dev/root
     if [ -z "$DRACUT_SYSTEMD" ]; then
         #FIXME What to link to /dev/root? Is it even needed?
         printf 'mount -t overlay LiveOS_rootfs -o%s,%s %s\n' "$ROOTFLAGS" \
```

**Comment by FGrose** [comment]
@GigabyteProductions:  Please test the patches at pull request #437.

**Comment by GigabyteProductions** [comment]
I have applied the hunks (except dracut.cmdline.7.asc) from c2fb396cb42901786a1170152ea85c60b11acfe1 to my /usr/lib/dracut/ for dracut-046-8.git20180105.fc27.x86_64 in Fedora.

It works well both with and without systemd.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by GigabyteProductions** [comment]
Will test soon

**Comment by GigabyteProductions** [comment]
Sorry about that.

Just tested using dracut 050 on Fedora 33. Works with and without systemd. Also works without `rd.live.overlay.overlayfs=1` thanks to this code: https://github.com/FGrose/dracut/blob/6734a42405a22d550224002045c69852f1966207/modules.d/90dmsquash-live/dmsquash-live-root.sh#L300-L301
