### ISSUE TITLE
Live root filesystem on squashfs

### ISSUE THREAD

**Issue by GigabyteProductions** [dracutdevs/dracut#433]
Before support for overlayfs existed in dracut, it made sense to require that squashfs live images simply contain a image of a writeable root file system (for use with block device overlays).

However, now that read-only root file systems can be made writeable by overlaying a tmpfs using overlayfs, it would make more sense to allow for the root file system to be provided directly by the downloaded squashfs image.

As a workaround, I am currently booting with a squashfs-in-squashfs image to satisfy the inner image search requirement.

To clarity, specifically what I am referring to is the following currently required image layout (from [dracut.cmdline(7)](https://github.com/dracutdevs/dracut/blob/bc01f822de732d85d4bfc77bae44c6bd4abe43d7/dracut.cmdline.7.asc#booting-live-images)):
```
               squashfs.img          |  Squashfs from LiveCD .iso downloaded via network
                  !(mount)
                  /LiveOS
                      |- rootfs.img  |  Filesystem image to mount read-only
                           !(mount)
                           /bin      |  Live filesystem
                           /boot     |
                           /dev      |
                           ...       |
```
I would instead like to use:
```
               squashfs.img          |  Squashfs from LiveCD .iso downloaded via network
                  !(mount)
                  /bin               |  Live filesystem
                  /boot              |
                  /dev               |
                  ...                |
```

**Comment by alkisg** [comment]
[Linux Terminal Server Project](http://www.ltsp.org) would appreciate this as well.

A squashfs image is served over NBD, and by using root=live:nbd:server:export, we would be able to netboot it without having to add custom code in the initramfs.

**Comment by dtardon** [comment]
#447 claims to have fixed this -> close?

**Comment by johannbg** [comment]
Closing as this issue seems resolved. Thank you for your contributions.

**Comment by GigabyteProductions** [comment]
Haven't utilized the feature yet. Will test, soon.

**Comment by GigabyteProductions** [comment]
Yep, works. Note: Make sure /proc exists in the image, so this test passes: https://github.com/FGrose/dracut/blob/6734a42405a22d550224002045c69852f1966207/modules.d/90dmsquash-live/dmsquash-live-root.sh#L298

That bit me in running the following command:
```
sudo mksquashfs "$root" "$image" -e dev -e proc -e sys
```

instead of this one:
```
sudo mksquashfs "$root" "$image" -wildcards -e 'dev/*' -e 'proc/*' -e 'sys/*'
```
