### ISSUE TITLE
udev version detection broken with current systemd git

### ISSUE THREAD

**Issue by Keruspe** [dracutdevs/dracut#468]
Currently, udev version is handled like this: `[ -z "$UDEVVERSION" ] && export UDEVVERSION=$(udevadm --version)`

Here is the output of `udevadm --version` with systemd git:

```
systemd 239
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN -PCRE2 default-hierarchy=hybrid
```

Conditions like `if [ $UDEVVERSION -ge 174 ]; then` cannot work

**Comment by Keruspe** [comment]
Regression introduced by https://github.com/systemd/systemd/pull/9920

**Comment by haraldh** [comment]
Shouldn't this be filed against systemd as a regression?

**Comment by yuwata** [comment]
Sorry, I will fix this on systemd side.

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/pull/10142

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/pull/10142 is merged.

**Comment by Keruspe** [comment]
@haraldh I wasn't sure where to file this, as relying on text output is often not recommended, especially on the systemd side

Anyway, we can close this as it has been fixed in systemd
