### ISSUE TITLE
Spawn emergency console on all console ttys

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#476]
Currently, when there is an emergency in dracut, it will only spawn the emergency console (e.g. on rd.break) on the primary tty. However, it should present a console on all  ttys.

mkinitrd uses sulogin for this. For systemd systems there is systemd-sulogin, which we would need to patch to issue a custom output.

Any comment on this before I get to it?

**Comment by herrold** [comment]
It is usually useful to leave an error message on the console at which it was expressed.  As I understand it, your suggestion would lose that information when a console is spawned

This seems like this needs more consideration

**Comment by danimo** [comment]
The information about the error has to be preserved as well as possible, of course.

**Comment by danimo** [comment]
https://github.com/dracutdevs/dracut/pull/499 is the suggested PR, it does not yet address your concern, but it is an improvement over not being able to do anything on the wrong console.

**Comment by danimo** [comment]
With https://github.com/dracutdevs/dracut/pull/499/commits/9a5cb9c5f2128ee5635a48ceb22e0d77e49d708b, we now have the emergency information on all ttys. All other relevant errors _should_ show up in the journal.
