### ISSUE TITLE
dracut-network: iscsi module causes device timeout on boots with resume= cmdline arg

### ISSUE THREAD

**Issue by dustymabe** [dracutdevs/dracut#480]
There is an odd interaction at play where having a `resume=` kernel command line arg as well as an initramfs that was built using `--no-hostonly --add iscsi` causes there to be a device timeout of the lvm swap device. This is occurring in Fedora 29 Atomic Host. A Fedora 29 Server system can show the problem easily by making sure `dracut-network` and `iscsi-initiator-utils` are installed and regenerating the initramfs with dracut -f --no-hostonly`. 

I have determined that this behavior [started happening with the `048` release of dracut](https://pagure.io/atomic-wg/issue/513#comment-537020). There were only three commits since `047` on the iscsi module-setup.sh so maybe it is one of them: b31f3fe 9e82732 5e615f4

The symptom you will see is a system that takes 90 seconds longer to boot and error messages something like:

```
Oct 17 23:05:41 localhost systemd[1]: dev-mapper-fedora\x2dswap.device: Job dev-mapper-fedora\x2dswap.device/start timed out.
Oct 17 23:05:41 localhost systemd[1]: Timed out waiting for device dev-mapper-fedora\x2dswap.device.
Oct 17 23:05:41 localhost systemd[1]: Dependency failed for Resume from hibernation using device /dev/mapper/fedora-swap.
```

There is a lot of detailed investigation over in https://pagure.io/atomic-wg/issue/513

**Comment by dustymabe** [comment]
corresponding BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1641268

**Comment by dustymabe** [comment]
if I remove the following code from the iscsi module setup then I don't observe this issue:

https://github.com/dracutdevs/dracut/blob/e54ab383f7529f340d69536709624dffb30046a1/modules.d/95iscsi/module-setup.sh#L262-L267

**Comment by dustymabe** [comment]
oh wow. https://github.com/dracutdevs/dracut/pull/329 looks related

**Comment by haraldh** [comment]
yeah, looks like iscsid.socket socket activation would suffice
