### ISSUE TITLE
Mounting /run with noexec breaks dracut shutdown

### ISSUE THREAD

**Issue by martinwhitaker** [dracutdevs/dracut#481]
systemd-shutdown only pivots into the initramfs if /run/initramfs/shutdown is executable. Since dracut 042, /run is mounted with the noexec option, which prevents this.

A possible fix would be to make the dracut-shutdown service remount /run with the exec option.

**Comment by haraldh** [comment]
Hmm, it's not mounted with noexec on my system:
```bash
$ fgrep '/run ' /proc/self/mountinfo 
26 94 0:23 / /run rw,nosuid,nodev shared:28 - tmpfs tmpfs rw,seclabel,mode=755
```

Anyway... you are right...  dracut-shutdown service should make sure, it's exec.

**Comment by haraldh** [comment]
Would this fix the issue?

```diff
diff --git a/dracut-initramfs-restore.sh b/dracut-initramfs-restore.sh
index 94794804..841c7035 100644
--- a/dracut-initramfs-restore.sh
+++ b/dracut-initramfs-restore.sh
@@ -21,6 +21,8 @@ if [[ $MACHINE_ID ]] && [[ -d /boot/${MACHINE_ID} || -L /boot/${MACHINE_ID} ]] ;
 fi
 [[ -f $IMG ]] || IMG="/boot/initramfs-${KERNEL_VERSION}.img"
 
+mount -t tmpfs -o mode=0755,nosuid,nodev tmpfs /run/initramfs
+
 cd /run/initramfs
 
 [ -f .need_shutdown -a -f "$IMG" ] || exit 1
```

**Comment by martinwhitaker** [comment]
No, because mounting the tmpfs will hide .need_shutdown. That can be worked round by moving the test for .need_shutdown, but mounting the tmpfs will also hide any debug options the user has put in /run/initramfs/etc/cmdline.d.

Changing the mount command to `mount -o remount,exec /run` does fix the problem. Alternatively, putting that command in a script in /lib/systemd/system-shutdown also works.

**Comment by thkala** [comment]
FWIW, putting a script in /lib/systemd/system-shutdown to remount /run no longer works. It looks like a somewhat old systemd commit (https://github.com/systemd/systemd/commit/456b2199f6ef0378da007e71347657bcf83ae465) broke this workaround by inadvertently reversing the order of running the scripts and checking whether /run/initramfs/shutdown is executable.

Maybe put the remount in dracut-initramfs-restore.sh? Or add a separate systemd service to do this at shutdown? It would not be as late as running from system-shutdown, but it would still be preferable to not having /run with noexec at all.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by martinwhitaker** [comment]
This is still an issue in dracut 050.
