### ISSUE TITLE
Shutdown umount loop early-terminates on failure, not on success

### ISSUE THREAD

**Issue by martinwhitaker** [dracutdevs/dracut#483]
From modules.d/99shutdown/shutdown.sh
````
while [ $_cnt -le 40 ]; do
    umount_a 2>/dev/null || break
    _cnt=$(($_cnt+1))
done
````
umount_a returns 0 on success, so the second line should be
````
    umount_a 2>/dev/null && break
````

**Comment by danimo** [comment]
@martinwhitaker @marcosfrm pls check on the pull request. Thanks!

**Comment by martinwhitaker** [comment]
@danimo, no that isn't  right. This is the patch I'm using:
[dracut-046-shutdown-fix-early-exit-in-umount-loop.patch.txt](https://github.com/dracutdevs/dracut/files/3816157/dracut-046-shutdown-fix-early-exit-in-umount-loop.patch.txt)

**Comment by martinwhitaker** [comment]
But on revisiting this, I'm not sure that is sufficient. The `umount_a` function is
````
umount_a() {
    local _did_umount="n"
    while read a mp a || [ -n "$mp" ]; do
        if strstr "$mp" oldroot; then
            if umount "$mp"; then
                _did_umount="y"
                warn "Unmounted $mp."
            fi
        fi
    done </proc/mounts
    losetup -D
    [ "$_did_umount" = "y" ] && return 0
    return 1
}
````
First, shouldn't the while loop be
````
    while read a mp a && [ -n "$mp" ]; do
````
Second, the function will return success (0) if any mount is successfully unmounted and failure (1) otherwise. Isn't the desired behaviour to return success if **all** mounts are successfully unmounted? I would suggest
````
umount_a() {
    local _umount_failed="n"
    while read a mp a && [ -n "$mp" ]; do
        if strstr "$mp" oldroot; then
            if umount "$mp"; then
                warn "Unmounted $mp."
            else
                _umount_failed="y"
            fi
        fi
    done </proc/mounts
    losetup -D
    [ "$_umount_failed" = "y" ] && return 1
    return 0
}
````
but please do check my logic - I've not tested this.

**Comment by haraldh** [comment]
Should probably be renamed to: umount_something ... Then the logic might be clear

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by martinwhitaker** [comment]
The code is unchanged in dracut 050, so this is still broken.
