### ISSUE TITLE
Dependencies of soft dependenies are not included in the initramfs

### ISSUE THREAD

**Issue by jeremycline** [dracutdevs/dracut#491]
Support for soft dependencies was added in commit 4cdee66c8ed5f82bbd0638e30d867318343b0e6c, but it appears that it isn't resolving the dependencies of the soft dependency it adds. 

This was reported as part of a [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1650054). In this particular case, i915/gvt added a ``MODULE_SOFTDEP("pre: kvmgt")`` in Linux v4.19. kvmgt.ko is pulled into the initramfs, but its dependencies (kvm, vfio, mdev) are not.

**Comment by jwrdegoede** [comment]
FWIW I also filed a Fedora bug for this:

https://bugzilla.redhat.com/show_bug.cgi?id=1655304

**Comment by haraldh** [comment]
Fixed with https://github.com/dracutdevs/dracut/commit/c38f9e980c1ee03151dd1c6602907c6228b78d30
