### ISSUE TITLE
Swap files not recognized as swap in resume module

### ISSUE THREAD

**Issue by jonas2515** [dracutdevs/dracut#496]
If a swap file is used for hibernation, dracut doesn't automatically install the resume module to the initramfs, making hibernation impossible.

This happens because in the `check()` function of the resume module, the `host_fs_types` array is checked for file systems of type "swap" and this array doesn't include swap files. To fix this issue and automatically install the resume module if a swapfile is used, the `host_fs_types` array should include swap files or the `check()` function should be adjusted to search for swap files itself.

**Comment by jonas2515** [comment]
Actually it's way better than swap partitions. If you have full disk encryption you don't have to go through the whole hassle of encrypting your swap partition. I can setup a swapfile in 5 minutes without having to resize all my partitions and I can resize it if I want to.

Here's some documentation:
https://wiki.archlinux.org/index.php/Dm-crypt/Swap_encryption#Using_a_swap_file
https://wiki.archlinux.org/index.php/swap#Swap_file

**Comment by l29ah** [comment]
@jonas2515 how did you manage to tell dracut to specify the swap file offset to the kernel?

**Comment by jonas2515** [comment]
@l29ah It's been some time since I set up hibernation on my machine, but IIRC the only thing I had to do was set the kernel parameters as described in the Arch wiki and make sure the resume module is loaded by adding `add_dracutmodules+="resume"` to /etc/dracut.conf.

**Comment by jonas2515** [comment]
@haraldh I'd like to fix that issue, do you have any suggestions or implementation ideas for how we can solve this?

**Comment by l29ah** [comment]
Oh, the hard-coded offset parameter, okay. I was hoping dracut is able to tell the offset itself, since i'm considering producing a swap file on demand only for the suspending purpose.
