### ISSUE TITLE
check for rootfs init is wrong

### ISSUE THREAD

**Issue by nolange** [dracutdevs/dracut#504]
The code in init appears to be wrong for absolute symlinks,
as it checks the file in the initramfs in that case.

```bash
    __p=$(readlink -f "${NEWROOT}/${i}")
    if [ -x "$__p" -o -x "${NEWROOT}/${__p}" ]; then
        INIT="$i"
        break
    fi
```

Consider the following existing symlink (`/lib/systemd/systemd` does not exist)
`lrwxrwxrwx    1 root     0               20 Jun 13  2018 /sysroot//sbin/init -> /lib/systemd/systemd`

This result in the following tests:

```bash
    __p=$(readlink -f "${NEWROOT}/${i}")
    # now __p=/sysroot/sbin/init 
    if [ -x "$__p" -o -x "${NEWROOT}/${__p}" ]; then
    # test /sysroot/sbin/init and /sysroot/sysroot/sbin/init - both fail
    # we would need to test for /sysroot/lib/systemd/systemd instead
```
To avoid false negatives and positives (paths existing only in initramfs),
the code would have to be adopted like this:

```bash
    __p="${NEWROOT}/${i}"
    [ -h "$__p" ] && __p="${NEWROOT}/$(readlink "$__p")"
    if [ -x "$__p" ]; then
        INIT="$i"
        break
    fi
```

If you agree, then I will create a fix

**Comment by haraldh** [comment]
go ahead

**Comment by johannbg** [comment]
Closing issues since fix seems to have been merged.
