### ISSUE TITLE
Check /usr/sbin for fsck programs

### ISSUE THREAD

**Issue by tpgxyz** [dracutdevs/dracut#506]
Some distros put fsck programs in /usr/sbin, and currently dracut's 99fs-lib module checks only /sbin/fsck*

https://github.com/dracutdevs/dracut/blob/f9c96cf56fed390841eac05c43826e62014c9188/modules.d/99fs-lib/module-setup.sh#L72

**Comment by tpgxyz** [comment]
@haraldh Harald can you please take a look on this?

**Comment by mrc0mmand** [comment]
Fixed & merged in #508.
