### ISSUE TITLE
049 not available from kernel.org

### ISSUE THREAD

**Issue by simonvanderveldt** [dracutdevs/dracut#520]
Is seems like the release tarball for 049 isn't available on kernel.org, can a tarball for 049 be added there?
I looked here https://mirrors.edge.kernel.org/pub/linux/utils/boot/dracut/, maybe it's available from a different location?

**Comment by simonvanderveldt** [comment]
Ping. Does anyone have any information/update on this?

**Comment by danimo** [comment]
@haraldh would know about this.

**Comment by johannbg** [comment]
Could have been [1] in anycase it's available now hence closing.

1. https://www.spinics.net/lists/linux-initramfs/msg04830.html
