### ISSUE TITLE
nfsroot_from_dhcp behavior looks unnatural

### ISSUE THREAD

**Issue by tsmish** [dracutdevs/dracut#529]
# Steps to reproduce
1. 10.0.0.1 is main router, which also performs DHCP server role. DHCP network boot is configured to boot from 10.0.0.2. 
2. 10.0.0.2 is automatic deploy server, which uses nfs to boot installation images. FAI does this for example. nfsroot is not set.
3. 10.0.0.3 boots using PXE from tftp server on 10.0.0.2.
# Expected behavior
NFS server is detected as 10.0.0.2
# Actual behavior
NFS server is detected as 10.0.0.1
# Additional info
This behavior stems from order of these lines.
https://github.com/dracutdevs/dracut/blob/master/modules.d/95nfs/nfs-lib.sh#L115-L116
If this is intentional, I'm really interested in rationale of such decision, as dedicated dhcp server looks more common than dedicated tftp server, and, as I understand, server-identifier option must be set by dhcp server, leaving no chance to next-server.

**Comment by johannbg** [comment]
@tsmish has your issue been addressed with #876?

**Comment by johannbg** [comment]
No response from reporter hence closing.
