### ISSUE TITLE
modules.d/35network-manager/nm-run.sh uses basename but does not require it

### ISSUE THREAD

**Issue by devurandom** [dracutdevs/dracut#537]
modules.d/35network-manager/nm-run.sh uses `basename`, but the accompanying module-setup.sh does not require it.

How to reproduce: On my system, sometimes bcache activation hangs forever, which will make `99-nm-run.sh` start before the new rootfs is online.  The console will then log lots of lines similar to: basename - no such file or directory.

Attached patch should fix this.  (Applies cleanly, not yet tested)

[dracut-049-network-manager-dependencies.patch.txt](https://github.com/dracutdevs/dracut/files/2856009/dracut-049-network-manager-dependencies.patch.txt)

See-Also: https://bugs.gentoo.org/677788

**Comment by mmokrejs** [comment]
Supposedly same patch will also fix for me:

`/lib/dracut/hooks/initqueue/settled/99-nm-run.sh: line 13: basename: command not found`
