### ISSUE TITLE
Fails: root=dhcp with DHCP root-path=nbd:server:export

### ISSUE THREAD

**Issue by alkisg** [dracutdevs/dracut#540]
This works in the cmdline:
root=nbd:server:export

The dracut man page says that the following is supported, yet it doesn't work:
- In cmdline: root=dhcp
- And in dnsmasq configuration: dhcp-option=option:root-path,nbd:server:export

The error messages are:
>systemd-fstab-generator: Failed to create unit file /run/systemd/generator/sysroot.mount, as it already exists. Duplicate entry in /etc/fstab?
Starting nbd nbd0...
...
Mounting /sysroot...
[FAILED] Failed to mount /sysroot.
[DEPEND] Dependency failed for Initrd Root File System
[DEPEND] Dependency failed for Reload Configuration from the Real Root

The first line of those errors shows up in successful boot as well.

At that emergency prompt, /dev/nbd0 is **mounted** properly and the /dev/root -> nbd0 symlink exists. I think it would successfully boot, if not for the dependency problem.

Finally, `systemctl status sysroot.mount` says:
> mount: /sysroot: special device dhcp does not exist.

The /run/systemd/generator/sysroot.mount file contains "What=dhcp", so I guess there's the issue?

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by alkisg** [comment]
Hello! I tested dracut while developing https://ltsp.org, and I reported the problems I found, but since they weren't fixed, all ltsp users currently use initramfs-tools based distributions, we have no dracut installations.

Feel free to close it, if any dracut developer or user wants to work on this in the future they can reopen it then. Thanks!

**Comment by johannbg** [comment]
Closing
