### ISSUE TITLE
Enable systemd-resolved on systemd-networkd module

### ISSUE THREAD

**Issue by adamoa** [dracutdevs/dracut#547]
Is there any reason for not having systemd-resolved implemented on the systemd-networkd module? Whenever a module depends on access to internet and name servers the systemd-networkd module alone is not sufficient. There is code commented out on systemd-resolved module.

**Comment by johannbg** [comment]
The reason for that is mostly historical and maturity. Today dracut arguably should be enabling by default upstream the entire system management network and related service stack ( resolved,timesyncd, etc ) plus iwd ( non existing module ) for wifi as an upstream ( if the systemd module is enabled ) but most distribution aren't there yet and perhaps never will be so we need to have a reliable off switch and we need to have proper test cases for this as well etc. You can follow #874 which hopefully will clarify this once an consensus is reached what the default should be here upstream.
