### ISSUE TITLE
Dracut's initramfs rebuild breaks clevis boot

### ISSUE THREAD

**Issue by marbetschar** [dracutdevs/dracut#571]
I've found that dracut breaks the unattended clevis boot (automatically unlocks LUKS encrypted root partition in a trusted network environment) whenever it rebuilds the initramfs if the `_netdev` flags are present in `/etc/crypttab` or `/etc/fstab`. When the `_netdev` flag is removed from both "*tab-files" before dracut is run, and are re-added afterwards, everything starts working again.

For more information see [this issue at the clevis repo](https://github.com/latchset/clevis/issues/99).

The issue occured on CentOS v7, after updating to the latest available kernel.

**Comment by minifiredragon** [comment]
Thank you soooo much for this post.  I have spent hours and hours and hours trying to get luks with clevis and tang to work.  Cloning and recloning one of my VMs trying to figure out what was going on.  Then I read this post.  This is 100% verified.  I had to remove _netdev from "*tab-files*".  

Then I ran dracut -fv --regen-all (may have been overkill).  Re added _netdev back in and rebooted.  And finally, it worked. Kernel: 3.10.0-957.21.2.el7.x86_64

**Comment by siniysv** [comment]
Experienced the same issue, adding a comment with hope it will be better indexed by search engines.

**Comment by haraldh** [comment]
Does it help to install `dracut-config-generic` ? Or specifying the `--no-hostonly` command line flag?

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
