### ISSUE TITLE
crypt-run-generator.sh depends on cryptsetup binary when not strictly required

### ISSUE THREAD

**Issue by liamdennehy** [dracutdevs/dracut#602]
By relying on the line:

https://github.com/dracutdevs/dracut/blob/8238f41b34777c3c75b03a9b598d4b9e1c7bf911/modules.d/90crypt/crypt-run-generator.sh#L14

The entire ``if`` block is skipped if the command fails e.g. if ``cryptsetup`` is not present. Under systemd this command is not required, so the failure incorrectly skips all discard flag processing.

**Comment by haraldh** [comment]
Would this work for you?
```
if [ -n "$DRACUT_SYSTEMD" ] || strstr "$(cryptsetup --help)" "allow-discards"; then
```
