### ISSUE TITLE
initrd hostonly-kernel-modules.txt varies from CPU

### ISSUE THREAD

**Issue by bmwiedemann** [dracutdevs/dracut#617]
While working on reproducible builds for openSUSE, I found that our kernel-obs-build package that contained a dracut-generated initrd would vary between VMs on different hosts, if those had different CPUs.

With commit 7047294617bbdd3ffb2466c73db56fda4e6156db the diff was only about `crc32c_intel` but since 0ef8f50723a2f6e1f5ccd9f7bd3b4d44c7252445 this has grown.

```diff
+++ new//.build.initrd.kvm.cpio.extract/lib/dracut/hostonly-kernel-modules.txt      2019-08-08 14:57:58.190102238 +0000
@@ -8,13 +8,6 @@
 ata_generic
 virtio_rng
 qemu_fw_cfg
-aesni_intel
-ghash_clmulni_intel
-crc32c_intel
-crc32_pclmul
-crct10dif_pclmul
-sb_edac
-intel_rapl
 acpi_cpufreq
```

@ryncsn - I'd like to get identical build results on different build hosts. How could we get there?

**Comment by haraldh** [comment]
Just build a non-hostonly initrd

**Comment by haraldh** [comment]
and specify the dracut modules to include

**Comment by ryncsn** [comment]
Hi, if you are make a hostonly build that is expected to be different per host, as it is a "host only" imag.
You can either make it a non hostonly image, or maybe I can make a PR to let the hostonly-kernel-modules.txt only be generated when "strict" host only mode is used. What do you think, does a non-hostonly image solution works for you?

**Comment by bmwiedemann** [comment]
We build it hostonly in KVM because we know it will only ever be run in KVM in the Open Build Service (OBS) and we need the small size to keep the size and its performance impact low.

The other use-case is around katacontainer images.

So would be nice to have a mode where we skip the hostonly-kernel-modules.txt creation.

**Comment by haraldh** [comment]
Reopen, if PR #624 does not fix your issue
