### ISSUE TITLE
Is the commit introduced a bug in dracut-functions.sh?

### ISSUE THREAD

**Issue by gaoyi1988** [dracutdevs/dracut#619]
https://github.com/dracutdevs/dracut/commit/9ed6eb741f0bc0178167e7063751eb2bb4ac6de5

In function check_vol_slaves_all(), when filter/global_filter is set in /etc/lvm/lvm.conf, dmsetup can get the _vg, but "lvm vgs" may execute failed. Then There is no lvm module in the initrd made by dracut.
filter set example is below:
global_filter = [ "a|^/dev/sda4$|", "r|.*/|" ]
lvm is the slave of sda3

**Comment by gaoyi1988** [comment]
dracut: check_vol_slaves_all must return 1 when lvm vgs failed #621

**Comment by danimo** [comment]
Commit was merged. Closing.
