### ISSUE TITLE
RFC: Drop support for non-systemd environments

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#642]
Over a beer at All Systems Go, we were wondering if we could shrink the code base by removing the non-systemd code paths. Rationale: Main contributors test only in systemd environments, reduce maintenance surface and maybe even explore the possibility of deprecating initqueue in favor of systemd-run (@lnykryn). This is an issues to evaluate if there is still demand for non-systemd environments.

So Is anyone using dracut without systemd?

//cc @mrc0mmand @lnykryn @haraldh @keszybz @tblume

**Comment by ytrezq** [comment]
@danimo I’m using dracut with Openʙꜱᴅ which implies without available cgroups support which in turns means without systemd.

Please don’t make dracut Linux only !

**Comment by marcthe12** [comment]
Gentoo and void the two main systemd free distros use dracut. The alternatives are having slow upstream if not dead

**Comment by netzverweigerer** [comment]
Are you sure that was just one beer?

**Comment by illiliti** [comment]
Don't do that. Linux is not only systemd

**Comment by Yann-Kaelig** [comment]
Drop support for non-systemd.

**Comment by danimo** [comment]
Ok, there are enough users of dracut without systemd. Finding this out was the main idea, so I'll leave it at that.

**Comment by Yann-Kaelig** [comment]
Thank you danimo.
