### ISSUE TITLE
Is It support for zstd compressed initramfs?

### ISSUE THREAD

**Issue by alvin998179** [dracutdevs/dracut#645]
Is It support for zstd compressed initramfs?

**Comment by danimo** [comment]
Yes, since 047. check `dracut --help` or the man page for details.

**Comment by alvin998179** [comment]
Thank you!

**Comment by alvin998179** [comment]
But I can not bootup in arch linux when I use zstd compressed initramfs.

**Comment by alvin998179** [comment]
How to make bootup work if  I use zstd compressed initramfs. Please tell me.

**Comment by haraldh** [comment]
`dracut --zstd …`
or
`compress=zstd` in a dracut configuration file

**Comment by alvin998179** [comment]
Got it, thanks.
