### ISSUE TITLE
Sorting resolv.conf results in failed lookups in some environments

### ISSUE THREAD

**Issue by HeyMerlin** [dracutdevs/dracut#652]
Hi,

I've been tracking down a dns issue I had since upgrading my version of Debian's Fully Automated Installation and have tracked it down to a change in write-ifcfg.sh (https://github.com/dracutdevs/dracut/pull/444/commits/c2692959eb856d12e89f0406ec1ad597d0a516cf).

Using a version that contains dracut prior to this merge works fine.  With this change, the resolv.conf ends up sorted and, coincidentally, exactly reversed.  This causes name lookups to fail during imaging using FAI.

In my case my resolv.conf entries look like this:
search foo.bar.ca
nameserver 192.168.240.5
nameserver 10.200.8.97
nameserver 10.200.8.61

When dracut pipes this through "sort -u" to unique the file the resulting file has the entries reversed.

To fix this I used awk to unique the files without changing the order:
```
write-ifcfg.sh
291c291
<     done | sort -u > /run/initramfs/state/etc/resolv.conf
---
>     done | awk '!($0 in a) { a[$0]; print }' > /run/initramfs/state/etc/resolv.conf
```
Alternatively use the shortened version "awk '!a[$0]++'" if you like.

Being that the change that causes this has been in place for a year and nobody has reported it I'm assuming it only affects certain environments.

**Comment by haraldh** [comment]
good point! Thanks!
