### ISSUE TITLE
Why does dracut logs all the files when it builds an image?

### ISSUE THREAD

**Issue by kowalcj0** [dracutdevs/dracut#653]
Hi,

I just noticed in journal that when `dracut` creates a new image it logs all the files from following directories:
```bash
dev
etc
init
lib
lib64
proc
root
run
sbin
sys
tmp
usr
var
```
Is that necessary?

os: Fedora 30
kernel: 5.3.5-200

here's an example of such listing: https://pastebin.com/mugRFw3Y

**Comment by haraldh** [comment]
This is from:
```bash
if (( maxloglvl >= 5 )) && (( verbosity_mod_l >= 0 )); then
    if [[ $allowlocal ]]; then
    "$dracutbasedir/lsinitrd.sh" "${DRACUT_TMPDIR}/initramfs.img"| ddebug
    else
        lsinitrd "${DRACUT_TMPDIR}/initramfs.img"| ddebug
    fi
fi
```

So, to prevent the logging, you could set `sysloglvl=4` in `/etc/dracut.conf.d/99-loglevel.conf`

**Comment by kowalcj0** [comment]
:+1: 
thanks
