### ISSUE TITLE
 dracut does not include systemd-networkd configuration in initramfs (Fedora 31)

### ISSUE THREAD

**Issue by FelixSchwarz** [dracutdevs/dracut#670]
I'm using Fedora 31 with dracut-049-27.git20181204.fc31.1.x86_64. I uninstalled NetworkManager and enabled systemd-networkd. However networkd does not work in early boot/initramfs.

    # ls -1 /etc/systemd/network
    10-enp3s0.network
    50-wired.link
    # dracut -f --add network
    # lsinitrd /boot/initramfs-5.3.8-300.fc31.x86_64.img | grep systemd/network
    drwxr-xr-x   2 root     root            0 Jul 25 00:24 etc/systemd/network
    -rw-r--r--   1 root     root          232 Jul 25 00:24 etc/systemd/network/50-wired.link
    drwxr-xr-x   2 root     root            0 Jul 25 00:24 usr/lib/systemd/network
    -rw-r--r--   1 root     root          441 Jul 25 00:24 usr/lib/systemd/network/99-default.link

I think a similar bug report was filed for Fedora 28 (https://bugzilla.redhat.com/show_bug.cgi?id=1582941). What puzzles me is that it "just worked" in CentOS 8.

How can I get networkd working in initramfs?

**Comment by FelixSchwarz** [comment]
Obviously I'm a complete n00b here - sorry for that.
I assumed that dracut would include+run networkd in initramfs as I an using that on Fedora. I noticed that this is likely not the case and that all IP configuration is done by other means (e.g. `dhclient`).

Now I am at a loss - regardless of kernel opts and configuration files dracut will not enable my network card (no lights on my ethernet port are not) hence no IP address in early boot (-> clevis fails). I tried adding something like `rd.ip=dhcp` in the kernel command line but still no joy.

This might well be a Fedora-specific failure but I would appreciate any pointers.

**Comment by konstantinblaesi** [comment]
`ip=dhcp` or others should work http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html

**Comment by halfadmin** [comment]
@FelixSchwarz 
Maybe not directly related, but after upgrading to 31 dracut did not include the kernel modules for my NIC as well as other binaries which iirc were usually there (like the ip command)
Without the NIC drivers there won't be an interface at all.
I also have the same issues with Clevis (see the fedora bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1702524).

The dracut version in 31 seems rather oldish, around a year old. I'm not familiar with the dev cycle for fedora/dracut but afaik some related fixes were introduced since then. What is the reason for this large gap between master and what currently is in Fedora 31?

**Comment by haraldh** [comment]
> The dracut version in 31 seems rather oldish, around a year old. I'm not familiar with the dev cycle for fedora/dracut but afaik some related fixes were introduced since then. What is the reason for this large gap between master and what currently is in Fedora 31?

That would be my fault being busy with new born baby and such :baby:

**Comment by anatol** [comment]
Agree with @FelixSchwarz that the networkd config files need to be included if `systemd-networkd` module is enabled.

**Comment by LaserEyess** [comment]
I disagree, they should not be added by default. There is no guarantee that your network environment is the same as before, or that you want all of your interfaces up and running. 

Physical interfaces may be necessary, but virtual ones won't always be. I would much rather choose which files I brought over with `install_items`. Furthermore, when making wireguard and certain tun/tap devices there are private keys that I do *not* want in my initramfs. Having dracut install these automatically (and having no equivalent `omit_install_items=`) would be a security issue for me, I'm sure other people have similar requirements on not including private keys in a world readable file!

Something like only adding `99-dracut-*.{network,netdev,link}` or files fitting some other scheme would be an ok compromise I guess.
