### ISSUE TITLE
overlayfs LiveOS question

### ISSUE THREAD

**Issue by udeved** [dracutdevs/dracut#686]
I am working on replacing our live mkinitcpio with live dracut.

Our iso has two layers, a rootfs and a overlay "livefs" to throw away when the installer extracts rootfs.

Now the question, is it possible to mount the livefs overlay with dracut on livecd?

All I get is an overlayfs mounted root, but dracut always mounts an empty overlay tmpfs. I can't seem to find documentation if and how and where to put the overlay livefs.img in the iso layout.

I am pretty flexible as to how to deploy img files, no matter it is a squash embedded ext img, a flat squash or a direct ext4 img.

Currently, the squashfs.img is a flat squash rootfs.
But what do I chose for the overlay?

Any help would be appreciated.

**Comment by udeved** [comment]
Atm, I am trying with these args

`
rdargs: root=live:LABEL=ARTIX_201911 rd.live.overlay=LABEL=ARTIX_201911:/livefs.img rd.live.overlay.overlayfs=1 rd.live.image ro rd.debug`

**Comment by udeved** [comment]
After looking a bit at the dmsquashlive code, it looks like what I want is not supported by dracut.

I basically want a lower join of the root, like lower=livefs:rootfs.

This would also make it possible to run a console only rootfs joined with a desktop layer, ie bootloader could have multiple entries with different desktops to start.

**Comment by udeved** [comment]
Ok, I have made a hacky patch to support a union join on the rootfs.

I added rd.live.join, but I am entirely unsure about any side effects with other setups.

I can send a PR, but this would have to be properly tested, however, for my purposes, it works.

**Comment by haraldh** [comment]
seems like https://github.com/dracutdevs/dracut/pull/687 is your PR
