### ISSUE TITLE
Dont allow to override cmdline

### ISSUE THREAD

**Issue by brandsimon** [dracutdevs/dracut#689]
Hi,

I use `--hostonly-cmdline` to store the cmdline in my efi binary, which I want to sign later.
While testing I found out, that it is possible to override the cmdline, for example in an efi shell I can execute `linux.efi root=...` and than this cmdline is used instead of my built in one. I dont want to allow this. Is there an option to always use the cmdline used at build time?

**Comment by marcthe12** [comment]
You need to enable secure boot to do this

**Comment by brandsimon** [comment]
Thank you very much, it works!
