### ISSUE TITLE
crypt: essiv module missing when building kernel 5.4 initramfs on running 5.3 kernel

### ISSUE THREAD

**Issue by rgcjonas** [dracutdevs/dracut#706]
I just got bitten by this when fedora updated to kernel 5.4.

My LUKS-encrypted disk is using the `aes-cbc-essiv:sha256` cipher. On kernel 5.4, the `essiv` module is required to decrypt it. On kernel 5.3, there is no `essiv` module, the required functionality appears to be built-in.

When building the initramfs for a 5.4 kernel on a running 5.3 kernel, dracut will not include the `essiv` module since that module is not loaded by the currently running kernel. When booting that 5.4 kernel+initramfs, mounting the encrypted volume will then fail.

As a workaround, I built the initramfs once with `--add-drivers essiv`, then booted that initramfs and regenerated it (without any command-line options) on the running 5.4 kernel. When running on 5.4, the `essiv` module is picked up correctly.

The problem only affects people with `*-essiv` ciphers and only during the 5.3->5.4 transition. Since Google didn't turn up anyone else having this problem, so I guess the number of affected systems is very small.

**Comment by haraldh** [comment]
Thanks for your report!

Sorry for the late reply and sorry for your problems.

What is the output of:
```console
# dmsetup table
```
on this machine?

I am trying to craft a patch, which could have potentially caught this. At least it might fix future kernel config changes.

**Comment by rgcjonas** [comment]
The output of `dmsetup table` is

```
hdd_crypt: 0 976954767 crypt aes-xts-plain64 0000000000000000000000000000000000000000000000000000000000000000 0 8:20 4096
luks-bf741a17-280b-478a-b37c-fb3d2b0e4064: 0 973621248 crypt aes-cbc-essiv:sha256 0000000000000000000000000000000000000000000000000000000000000000 0 8:3 4096 1 allow_discards
system-home: 0 167772160 linear 253:0 2048
system-home: 167772160 671088640 linear 253:0 285509632
system-swap: 0 12877824 linear 253:0 220203008
system-swap: 12877824 8093696 linear 253:0 956598272
system-root: 0 52428800 linear 253:0 167774208
system-root: 52428800 52428800 linear 253:0 233080832
```
