### ISSUE TITLE
Pick FIPS hmac checking tool

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#707]
RH seem to be using `sha512mac` to verify the kernel and other FIPS relevant parts. SUSE uses the kcapi implementation of `fipscheck`, which only depends on the kernel crypto API. Right now, we have a [proprietary patch](https://github.com/openSUSE/dracut/commit/a6090e2f68a4ca727005b1de8a45bf474a782008), that tries to generalize as much as possible, but hardcodes `fipscheck`, because we can't do magic detection of the checker (sha512mac can legitimately be installed on a system without being FIPS compliant). 

Questions:

1. Is RH staying with `sha512sum` or are there plans to move to kcapi `fipscheck`?
2. If not, I would like to introduce an overridable parameter/config settings called `hmac-tool`, which allows for an override. Objections?

**Comment by danimo** [comment]
@haraldh can you find out what the status and plans at RH are regarding this? Will you stick with sha512sum or use fipscheck going forward?

**Comment by danimo** [comment]
@haraldh ping?

**Comment by haraldh** [comment]
@danimo waiting for internal reply.

**Comment by haraldh** [comment]
Tomáš Mráz wrote:
> We are actually using sha512hmac from the libkcapi library already in
Fedora (which means RHEL-9+). The only difference from fipscheck (which
in Fedora has already moved to use libkcapi as well) are different
command line parameters and different HMAC key. I do not see any
particular reason to move to fipscheck from the libkcapi provided
sha512hmac. On the other hand adding the parameter seems harmless.
