### ISSUE TITLE
`systemd-networkd` should be a `network` service provider

### ISSUE THREAD

**Issue by anatol** [dracutdevs/dracut#737]
Currently `dracut` contains two modules that help to setup network at init time: `network` and `systemd-networkd`. Users suppose to use only one of the modules to enable network functionality.

Some third-party modules (e.g. [clevis-pin-tang](https://github.com/latchset/clevis/blob/master/src/luks/systemd/dracut/clevis-pin-tang/module-setup.sh.in#L22)) need network and specify `network` module as a requirement. This unfortunately pulls the `network` module even on the systems that configure `systemd-networkd`.

`dracut` need to be able to specify `module A provides network functionality` so clients should not care about choosing a particular network module implementation.

**Comment by shaba** [comment]
Please, use network.target (or network-online.target). Not network.service.
network.target should include any network service, as network-scripts or NetworkManager or systemd-networkd or ConnMan.

**Comment by johannbg** [comment]
The scope of the pull request I will be working on will be so that systemd-networkd module will be made independent so it can be swapped out with NetworkManager and Wicked and iwd ( which I plan on introducing as well )
