### ISSUE TITLE
35network-manager won't trigger initqueue/online hook

### ISSUE THREAD

**Issue by olahaye74** [dracutdevs/dracut#756]
When using 40network, defaulting to 35network-manager, nothing will triggers initqueue/online hook.
Affected versions: all since the split of 40network with sub modules 35network-manager and 35network-legacy

**Comment by haraldh** [comment]
@tyll @lkundrak  ?

I see
https://github.com/dracutdevs/dracut/blob/fc6f458c3becd55277d1ab87d1608f0fe1fccf08/modules.d/35network-manager/nm-run.sh#L22
which "should" to the thing, though.

**Comment by olahaye74** [comment]
Woohoo, thanks a lot Harald,

You’re perfectly right.
The fact is that I was looking at dracut-network-049-27.git20190906.el8_1.1.x86_64 persent in latest CentOS-8.1 at the time I’m writing this message.

The file in this package lack this magic line! (and some others at the beginning as well)
#!/bin/sh

if getargbool 0 rd.debug -d -y rdinitdebug -d -y rdnetdebug; then
    /usr/sbin/NetworkManager --configure-and-quit=initrd --debug --log-level=trace
else
    /usr/sbin/NetworkManager --configure-and-quit=initrd --no-daemon
fi

for _i in /sys/class/net/*/
do
    state=/run/NetworkManager/devices/$(cat $_i/ifindex)
    grep -q managed=true $state 2>/dev/null || continue
    ifname=$(basename $_i)
    sed -n 's/root-path/new_root_path/p' <$state >/tmp/dhclient.$ifname.dhcpopts
    /sbin/netroot $ifname
Done

I’ll report that upstream. Thanks a lot again for pointing that out 😊

Olivier.


De : Harald Hoyer <notifications@github.com>
Répondre à : dracutdevs/dracut <reply@reply.github.com>
Date : mercredi 11 mars 2020 à 15:21
À : dracutdevs/dracut <dracut@noreply.github.com>
Cc : LAHAYE Olivier <olivier.lahaye@cea.fr>, Author <author@noreply.github.com>
Objet : Re: [dracutdevs/dracut] 35network-manager won't trigger initqueue/online hook (#756)


@tyll<https://github.com/tyll> @lkundrak<https://github.com/lkundrak> ?

I see
https://github.com/dracutdevs/dracut/blob/fc6f458c3becd55277d1ab87d1608f0fe1fccf08/modules.d/35network-manager/nm-run.sh#L22
which "should" to the thing, though.

**Comment by tyll** [comment]
Do you still need something from the NM team?

**Comment by olahaye74** [comment]
No, it's ok for now. thanks a lot. Problem is in RHEL-8.1 and CentOS-8.1 using a unfinished version of dracut 0.50 (the version with 35network-manager module)
I've reported to CentOS bug tracker here: https://bugs.centos.org/view.php?id=17129
