### ISSUE TITLE
Revoked PGP key used to sign dracut 050 release

### ISSUE THREAD

**Issue by diabonas** [dracutdevs/dracut#773]
While trying to update the Arch Linux package for dracut to the latest
version 050, we noticed that the PGP key with fingerprint [0x4C96E1500F9421CCF82D5DCA034EB370014DF270](https://sks-keyservers.net/pks/lookup?op=get&search=0x4C96E1500F9421CCF82D5DCA034EB370014DF270) was revoked on 2020-02-19. This is quite concerning given the fact that the [Git tag for dracut 050](https://github.com/dracutdevs/dracut/releases/tag/050) was signed by this very key on 2020-03-04, i.e. two weeks after it had already been revoked.

Could you please describe what happened and which key you are planning to use going forward?

**Comment by haraldh** [comment]
hmm.. not that I know of doing that willingly

http://ipv4.pool.sks-keyservers.net/pks/lookup?op=vindex&fingerprint=on&search=0x034EB370014DF270

I once revoked a subkey

**Comment by haraldh** [comment]
meh.. might have been when I created a new yubikey...

**Comment by haraldh** [comment]
yes, that's the date... f** macos version

**Comment by grazzolini** [comment]
Hi @haraldh, thanks for your reply. I know that gpg is prone to snafu's and this might be no exception. Just not sure how we can fully validate your new key, without some out of band verification.

**Comment by haraldh** [comment]
@grazzolini I started a new key

https://harald.hoyer.xyz/files/gpg-key.txt
https://pgpkeys.co.uk/pks/lookup?op=vindex&fingerprint=on&search=0x4BC0896FB5693595

I will try to get a signature from Greg Kroah-Hartman.

**Comment by haraldh** [comment]
@grazzolini I contacted helpdesk@kernel.org .. so we will see

**Comment by haraldh** [comment]
https://keybase.io/haraldhoyer might also convince you

**Comment by grazzolini** [comment]
Hi @haraldh, thanks for this. We just want to make sure the validation has a unbroken line. I only noticed this after @diabonas brought it up. Also, you'd be surprised at how many users are using dracut on Arch Linux already. I got tons of emails regarding this new release! Thanks again.

**Comment by haraldh** [comment]
Thanks for the notice. I finally got Greg's signature  🎉

**Comment by haraldh** [comment]
https://github.com/dracutdevs/dracut/security/advisories/GHSA-xpx8-76w2-rgr7

**Comment by grazzolini** [comment]
Thanks for the security notice @haraldh.

**Comment by haraldh** [comment]
Want me to resign the dracut-050 release with the new key?

**Comment by grazzolini** [comment]
@haraldh

Please, that would be quite helpful. I should update it tomorrow.

**Comment by haraldh** [comment]
done :-)
