### ISSUE TITLE
Dracut rootovl command?

### ISSUE THREAD

**Issue by Lucapz** [dracutdevs/dracut#779]
How do you install rootovl on Ubuntu / Debian as i can't find any step by step guides?

**Comment by haraldh** [comment]
I don't even know what you mean.

**Comment by Lucapz** [comment]
If you don't know what someone means then why rudely close a thread until you have a explanation?

The fai project mentions it here:

https://blog.fai-project.org/posts/overlayfs/

>The Debian package of dracut supports the kernel cmdline option rootovl.

and rootovl gets mentioned here but for a Raspberry ARM version

https://www.enricozini.org/blog/2019/himblick/read-only-rootfs/

and Thomas Lange from dracut mentions it here in a bug report of above.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945596

>If you add the parameter rootovl to the kernel cmdline, the initrd created by dracut will make a read only rootfs writable by >putting a tmpfs on top. This also works when using an nfsroot.

**Comment by haraldh** [comment]
So, a quick search in the source code here for `rootovl`, will give you nothing. That means, that it is not part of the dracut project. Please contact your debian maintainer.

Sorry for being rude with closing this issue, but to get information, you have to provide a little bit more context.

**Comment by Lucapz** [comment]
@haraldh 

My bad , I wrongly thought Thomas Lange was a dracut developer but it turns out he is just a package maintainer at Debian.Not sure why people are giving the impression online that rootovl is part of dracut but it explains why people can't get root overlay to work.

Thanks for the explanation and sorry for my confusion and wasting your time for something that isn't even part of your project.
