### ISSUE TITLE
Auto-detected luks unlock fails & cmdline.d not read

### ISSUE THREAD

**Issue by bbaserdem** [dracutdevs/dracut#785]
Good evening.

My use case is I want to embed kernel parameters in the initrd image. I have a LVM on LUKS partition layout; and I want to do as little machine-specific configuration as possible (I deploy most of my configuration files across multiple computers) The reason why I want to embed kernel parameters in the initrd is to use the strength of dracut, and eventually pack the kernel and the initrd image into one efi executable so I can use my own secure boot keys.

Currently, when I generate a dracut initrd, I am unable to boot to it. I'm getting the same error as #723; (our problems seem to be similar; but in my case it's the command line arguments from cmdline.d that are ignored; not from dracut.conf.d)

```
dracut-initqueue[585]: Failed to start systemd-cryptsetup@luks\<UUID with \ seperators>.service: Unit systemd-cryptsetup@luks\<UUID with \ seperators>.service not found. 
```

With trial and error; I found that if I supply my own commandline parameter `rd.luks.name=<UUID>=cryptlvm` by using the bootloader I am able to boot. If I try to supply this parameter through `cmdline.d/*.conf` that line is ignored. I will also add that other autodetected parameters work fine; even when I am on BTRFS on LVM on LUKS; the correct command for mounting the proper subvolume is issued.

# Problem description

* Auto-detecting LUKS volumes fail to unlock the LUKS partition. Unless the parameter `rd.luks.name=<UUID>=cryptlvm` is issued using the boot manager; booting fails.
* My kernel parameters from `/etc/cmdline.d/*.conf` are not being embedded in the initrd; and are completely ignored

# Expected behaviour

* For `hostonly` option; expect the autodetected hook for unlocking LUKS volume to work; and expect to not having to supply the correct parameters externally.
* When I have `hostonly_cmdline="yes"` in `/etc/dracut.conf.d/anyname.conf`, expect to have the parameters from `/etc/cmdline.d/*.conf` be embedded in the initrd.

# Configuration

* Operating system: archlinux
* Kernel: linux (5.6.2-arch1-2)
* Dracut version: 049

Output of lsblk

```
NAME               MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                  8:0    0 931.5G  0 disk  
├─sda1               8:1    0   200G  0 part  /media/windows
└─sda2               8:2    0 731.5G  0 part  
  └─cryptarchive   254:5    0 731.5G  0 crypt /media/archive
nvme0n1            259:0    0 931.5G  0 disk  
├─nvme0n1p1        259:1    0   550M  0 part  /boot/efi
└─nvme0n1p2        259:2    0   931G  0 part  
  └─cryptlvm       254:0    0   931G  0 crypt 
    ├─Linux-Arch   254:1    0    45G  0 lvm   /
    ├─Linux-Home   254:2    0   799G  0 lvm   /home
    ├─Linux-Gentoo 254:3    0    45G  0 lvm   /media/gentoo
    └─Linux-Opt    254:4    0    42G  0 lvm   /opt
```

Content of /etc/dracut.conf.d/sbp.conf

```
# Config file
hostonly="yes"
hostonly_cmdline="yes"
use_fstab="yes"
early_microcode="yes"
show_modules="yes"
compress="lz4"
add_drivers+=" i915 "
i18n_default_font="ter-powerline-v16n"
omit_dracutmodules+=" network iscsi "
```

Content of /etc/cmdline.d/sbp.conf

```
rd.luks.name=<UUID with - seperators>=cryptlvm
rd.shell
rd.debug
log_buf_len=1M
resume=/dev/Linux/Arch
resume_offset=10880182
mem_encrypt=off
i8042.reset
rd.info
```

Output of `dracut /boot/efi/EFI/Arch/initramfs-dracut.img --force`
```
...
dracut: *** Store current command line parameters ***
dracut: Stored kernel commandline:
dracut:  rd.luks.uuid=luks-da9c7226-d355-4dcd-a40a-32418f052f9b
dracut:  rd.lvm.lv=Linux/Arch 
dracut:  root=/dev/mapper/Linux-Arch rootfstype=btrfs rootflags=rw,noatime,nodiratime,compress=lzo,ssd,space_cache,subvol=@root
dracut: *** Creating image file '/boot/efi/EFI/Arch/initramfs-dracut.img' ***
dracut: *** Creating initramfs image file '/boot/efi/EFI/Arch/initramfs-dracut.img' done ***
```

**Comment by pluth** [comment]
I have the same problem. I found that including /etc/cmdline.d/ can be done by just adding
`install_items+=" /etc/cmdline.d/* "`
to your dracut config. I also expected this to happen automatically (and was wondering why my kernel parameters were geting ignored for quite a while).

But I also think the luks hook could be smarter here and generate a parameter like (in my case, no lvm)
`rd.luks.name=$UUID=root`
automatically from the currently mounted root. Especially considering it (correctly, imo) later sets the root parameter to /dev/mapper/root. However, because dracut only passes rd.luks.uuid=$UUID (instead of rd.luks.name), systemd will open the decrypted device at /dev/mapper/luks-UUID instead of the expected /dev/mapper/root. 
A short-term fix for this is to tell dracut to include /etc/crypttab with a line like
`root UUID=$UUID` in the initramfs.
This tells systemd to create /dev/mapper/root instead so we can continue booting.

See https://www.freedesktop.org/software/systemd/man/systemd-cryptsetup-generator.html for how systemd reads rd.luks.uuid, rd.luks.name and /etc/crypttab

**Comment by bbaserdem** [comment]
Your solution does work @pluth ; however the behavior is inconsistent. The docs state that these files should be taken in without having to specify the install_items config option.

This fix also caused my laptop keyboard to be unrecognized during the password prompt phase; so I am still unable to boot using the dracut initrd.

**Comment by haraldh** [comment]
> I have the same problem. I found that including /etc/cmdline.d/ can be done by just adding
> `install_items+=" /etc/cmdline.d/* "`

The documentation never mentions a `/etc/cmdline.d` directory in the host file system... only ever in the initramfs filesystem.

**Comment by X0rg** [comment]
I also have issue with cmdline (see #782): even if files are added with `install_items+=" /etc/cmdline.d/* "` as suggested by @pluth, command line is not applied to kernel.

##### `lsinitrd`:
```
drwxr-xr-x   2 root     root            0 May 23 21:46 etc/cmdline.d
-rw-r--r--   1 root     root          273 May 23 21:46 etc/cmdline.d/95root-dev.conf
-rw-r--r--   1 root     root          104 Apr  5 11:32 etc/cmdline.d/96-initramfs.conf
-rw-r--r--   1 root     root           58 Apr  5 11:32 etc/cmdline.d/97-splash.conf
-rw-r--r--   1 root     root          102 Apr  5 11:32 etc/cmdline.d/98-extra.conf
```

##### `journalctl`:
```
May 23 21:50:26 localhost dracut-cmdline[340]: dracut-dracut-050
May 23 21:50:26 localhost dracut-cmdline[340]: Using kernel command line parameters: root=UUID=62b9dcd3-4b29-4d4f-a57c-84c7d453354e rootfstype=f2fs rootflags=rw,relatime,lazytime,background_gc=on,nodiscard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix rw rd.vconsole.keymap=fr-latin1 rd.vconsole.font=eurlatgr rd.shell=1 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 loglevel=3 udev.log-priority=3 vt.global_cursor_default=0 cgroup_no_v1=all mitigations=off fbcon=scrollback:256k radeon.audio=0 amdgpu.ppfeaturemask=0xfffd7fff \\EFI\archlinux\vmlinuz-linux-ck-zen2 root=/dev/nvme0n1p2 nosplash rd.info
```

##### `cmdline`:
```
\\EFI\archlinux\vmlinuz-linux-ck-zen2 root=/dev/nvme0n1p2 nosplash rd.info
```

Root can not write to file `pp_od_clk_voltage`, that means `amdgpu.ppfeaturemask=0xfffd7fff` is not applied.

***

> The documentation never mentions a /etc/cmdline.d directory in the host file system... only ever in the initramfs filesystem.

@haraldh [ArchWiki does](https://wiki.archlinux.org/index.php/Dracut#Kernel_command_line_options), hence the reason of this confusion I think.

**Comment by bbaserdem** [comment]
@X0rg indeed the issue is with the Archwiki; and it is definitely not in the documentation; as I initially thought. This has been my mistake. I believe from my end; this closes this issue.
