### ISSUE TITLE
dracut-install: Failed to find module 'crc32c'

### ISSUE THREAD

**Issue by joalmjoalm** [dracutdevs/dracut#793]
error when "dracut -f" on ubuntu 18.04.4 kernel  5.3.0-46-generic

dracut-install: Failed to find module 'crc32c'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.lDrmEu/initramfs --kerneldir /lib/modules/5.3.0-46-generic/ -m crc32c

I fixed it by removing the /etc/dracut.conf.d/10-debian.conf as described at https://github.com/antonio-petricca/buddy-linux/issues/2
https://bugs.launchpad.net/ubuntu/+source/dracut/+bug/1781143

Dont know if thats the most appropiate solution, will this be fixed instead of applying mentioned workaround.

**Comment by haraldh** [comment]
File a bug against in your distribution bug database. `/etc/dracut.conf.d/10-debian.conf` is not shipped by the dracut project, but was added by a package (most likely debian) maintainer.
