### ISSUE TITLE
/etc/vconsole.conf must be always included into initrd, even in generic initrds

### ISSUE THREAD

**Issue by mikhailnov** [dracutdevs/dracut#796]
systemd-vconsole-setup is run in initrd for the first time. Seems that all VT settings of newely openned TTYs after startup are inherited from what was set up at initrd stage. See .g. this code: https://github.com/systemd/systemd/blob/1405cb653ae8588404e64af0265bb0bec47537b4/src/vconsole/vconsole-setup.c#L209

Now dracut copies /etc/vconsole.conf only if a host-only initrd is being built.

This results to non-ASCII symbols being krakozybras in TTYs despite correct settings in /etc/vconsole.conf when a generic inird is built. See this screenshot:
![image](https://user-images.githubusercontent.com/15802528/79673386-efdbb700-81e1-11ea-91d8-6258ce359928.png)

The I run `systemctl restart systemd-vconsole-setup` and get a correct font:
![image](https://user-images.githubusercontent.com/15802528/79673412-29acbd80-81e2-11ea-9db0-c08a1776d17c.png)

It is reported that, when `/etc/vconsole.conf` is copied to initrd, this problem does not happen.
I can't understand the current logics in dracut well enough.
And I am not completely sure that copying /etc/vconsole.conf into initrd is a good solution.

**Comment by haraldh** [comment]
Thanks for your analysis and patch!
