### ISSUE TITLE
in some cases we can't override default in 40network

### ISSUE THREAD

**Issue by dustymabe** [dracutdevs/dracut#798]
currently `40network` chooses between `network-legacy` and `network-manager` based on some conditional logic:

https://github.com/dracutdevs/dracut/blob/25c7a13985473ff9714245eaa602225b1a0f9ecb/modules.d/40network/module-setup.sh#L11-L15

So the default on say a Fedora 31+ system should be `network-manager`. What if you want it to be `network-legacy`? `dracut --add network-legacy --force --verbose /tmp/f.img` should work, right?

The answer is yes, and no. It depends really. If I start from a scratch system (the Fedora Cloud Base Image or Vagrant Box are a great starting point) and I install `dracut-network` and then run the command I get expected behavior:

```
sudo dracut --add network-legacy --verbose --force /tmp/f.img
...
dracut: *** Including module: network-legacy ***
dracut: *** Including module: network ***
...
```

However if I add another dracut module (let's say [Ignition](https://github.com/coreos/ignition-dracut)) with `dnf install -y ignition` I now get the wrong/unexpected behavior:

```
sudo dracut --add network-legacy --verbose --force /tmp/f.img
...
dracut: *** Including module: ignition ***      
dracut: *** Including module: network-legacy ***                                                                      
dracut: *** Including module: network-manager ***
dracut: *** Including module: network ***
...
```

If I try to omit `network-manager` specifically I get errors:

```
$ sudo dracut --add network-legacy --omit network-manager --verbose --force /tmp/f.img                                                                                                                                
...
dracut: dracut module 'network-manager' will not be installed, because it's in the list to be omitted!                                                                                                                                       
dracut: dracut module 'network' depends on 'network-manager', which can't be installed                                                                                                                                                       
dracut: dracut module 'url-lib' depends on 'network', which can't be installed                                                                                                                                                               
dracut: dracut module 'ignition' depends on 'url-lib', which can't be installed                                                                                                                                                              
...
```

In this case this happens to be because the dracut module from Ignition runs a priority level `30` and depends on `network` which has a priority level of `40` which is later than `35network-legacy` and `35network-manager`. The logic from the `--add network-legacy` only gets applied when `35network-legacy` gets checked. At the point the `30ignition` module gets checked it reports it depends on `40network` and the conditional logic will run (i.e. before `35`) and it will `network-manager`. 

I have a question and a suggestion related to this bug (I guess maybe not a bug):

- Is it valid for modules at earlier number priority to *depend* on modules at later number priority?
    - i.e. in this case is it invalid for the ignition module to have a priority of `30`?
- Can we just run `check_module` on modules explicitly specified in `--add` on the cli first before any cycling through the priorities start?
    - This would have prevented this problem because `--add network-legacy` would have caused `network-legacy` to get added and reported as included by `dracut_module_included()` the first time it was checked.

Version of dracut tested with: 

```
$ rpm -q dracut dracut-network ignition
dracut-050-26.git20200316.fc32.x86_64
dracut-network-050-26.git20200316.fc32.x86_64
ignition-2.2.1-3.git2d3ff58.fc32.x86_64
```

Note this same thing happens with version of dracut in RHEL 8.2 (or equivalent CentOS) but flip the logic (i.e. `network-legacy` is the default and you're trying to override with `network-manager`)

**Comment by haraldh** [comment]
>     * Can we just run `check_module` on modules explicitly specified in `--add` on the cli first before any cycling through the priorities start?
>       
>       * This would have prevented this problem because `--add network-legacy` would have caused `network-legacy` to get added and reported as included by `dracut_module_included()` the first time it was checked.

I think this might be the solution to the problem.

I don't want to enforce ordering of dependencies via numbering and I really don't want to end up with a complex dependency graph solver.
