### ISSUE TITLE
xxhash_generic isn't automatically added to host-only initramfs, results in boot failure on Btrfs

### ISSUE THREAD

**Issue by cmurf** [dracutdevs/dracut#802]
Fedora 32
dracut-050-26.git20200316.fc32.x86_64

Btrfs optionally supports xxhash64, blake2b, and sha256 checksumming. If xxhash_generic isn't included in the initramfs, booting a btrfs file system using xxhash64 will fail at sysroot mount time.

When manually running dracut, even though lsmod reports xxhash_generic is loaded, the resulting host-only initramfs does not contain xxhash_generic. Instead I need to create `/etc/dracut.conf.d/xxhash64.conf` containing `add_drivers+=" xxhash_generic "`

Alternatively a host-only initramfs, created with -N, does already contain xxhash_generic (without needing a dracut drop-in file).

**Comment by haraldh** [comment]
> Alternatively a host-only initramfs, created with -N, does already contain xxhash_generic (without needing a dracut drop-in file).

       -N, --no-hostonly
           Disable Host-Only mode

**Comment by haraldh** [comment]
Anyway, thanks for reporting.. will prepare a fix
