### ISSUE TITLE
Centralized vendor branches here

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#811]
This repo has vendor branches for RHEL. SUSE currently also has vendor branches in our fork at opensuse/dracutdevs. We would like to integrate them here and generally encourage contributing distros to maintain their vendor branches here.

### Pros
- simplified upstream/master-first policy, since PRs can be directly filed here
- improved mutual awareness of vendor changes
- which can result in reduced even less vendor patches, up to the point where they are mostly backports

**Comment by danimo** [comment]
ref. https://github.com/openSUSE/dracut/issues/27

**Comment by haraldh** [comment]
fine with me.. you have write access, don't you?

**Comment by haraldh** [comment]
We should probably add "Labels" or "Projects" then for these kind of PRs

**Comment by haraldh** [comment]
@lnykryn ?

**Comment by danimo** [comment]
> fine with me.. you have write access, don't you?

Sure, I just wanted to seek consent first :)

**Comment by lnykryn** [comment]
> @lnykryn ?
No problem.

**Comment by danimo** [comment]
Ok, I have created vendor: labels for Fedora and openSUSE, should  we add some for RHEL and SLE, too?

**Comment by lnykryn** [comment]
Yeah, I will add rhel label. Btw, we are doing the same thing for systemd. There we have a bunch of downstream-* labels

**Comment by danimo** [comment]
ok, feel free to change the naming. Also, can you add @tblume to the list of project maintainers? He is co-maintaining dracut for SUSE with me.

**Comment by danimo** [comment]
@lnykryn @haraldh ping?

**Comment by johannbg** [comment]
@danimo I deleted those Vendor labels ( there was only one issue associated with the vendors ) and introduced "downstream" label which is an issue tracker for all downstream distributions then added distribution specific labels for arch,centos,debian,fedora,gentoo,opensuse,rhel,suse,ubuntu,yocto. The general idea behind that was that downstream maintainers push the issue upstream to dracut ( if relevant ) and that issue gets labelled downstream + the distribution so probably the only thing missing are those vendor branches.

**Comment by johannbg** [comment]
If we want to specifically differentiated vendors from downstream we can just created a vendors label which would be an issue tracker for all vendors then just add that label + distro see for example output from the search "label:downstream label:rhel " we would just be changed it to "label:vendors label:rhel instead

**Comment by johannbg** [comment]
Come to think of it it's probably best to just label it for what it is branches + the branch name ( skip the whole vendor/downstream for those branches ) because it could become ugly quite fast if the vendor could have multiple branches due to different supported releases. ( rhel7,rhel8,rhel9 etc )

**Comment by johannbg** [comment]
@danimo I just went ahead and decided on the label branches + branch specific labels and created the "branches" as a catch all and rhel-6 rhel-7 rhel-8 rhel-9 for the RHEL specific branches so just go ahead and created the relevant Suse branch(es) ( you already have a green light from @haraldh to do that ) then just add those suse branch names as labels when done. I will take care of the automatic labelling stuff for the repository in a pull request and if you are done prior to me doing that I can include the suse stuff there as well.
