### ISSUE TITLE
Failure to detect root fs on LVM

### ISSUE THREAD

**Issue by tkoeller-max** [dracutdevs/dracut#816]
My root file system is on LVM, which dracut-initqueue fails to detect. After a **very long** series of retries, I am finally dropped into the emergency shell. After exiting, booting continues normally and finally succeeds.

Kernel command line is:
_BOOT_IMAGE=(hd5,gpt3)/vmlinuz-5.6.8-200.fc31.x86_64 root=/dev/mapper/SysStorage-RootFS ro rd.lvm.vg=SysStorage rd.lvm.lv=RootFS rd.md=0 rd.dm=0 rd.luks=0 rd.shell=1 rd.debug=1 vconsole.keymap=de_

[rdsosreport.txt.gz](https://github.com/dracutdevs/dracut/files/4611975/rdsosreport.txt.gz)

**Comment by puleglot** [comment]
You have an error in cmdline options:
`rd.lvm.lv=RootFS` -> `rd.lvm.lv=SysStorage/RootFS`

**Comment by puleglot** [comment]
Also it doesn't make much sense to use both rd.lvm.vg and rd.lvm.lv in your case.

**Comment by tkoeller-max** [comment]
So, you are saying that rd.lvm.lv takes the full LV path including the volume group, and rd.lvm.vg is not to be used at all? If this is so, I feel tempted to say that the documentation for these parameters is at least misleading.

**Comment by puleglot** [comment]
Indeed, it is not clear from the `dracut.cmdline(7)` man page.
