### ISSUE TITLE
grub2 does not boot with CONFIG_MODULE_SIG=y kernel

### ISSUE THREAD

**Issue by Safari77** [dracutdevs/dracut#817]
4.19.123 compiled with CONFIG_MODULE_SIG=y does not boot Fedora 32 using grub2.
After selecting the kernel in grub2, texts disappear and the background stays in place, but nothing happens for >10 minutes, I have to reset the machine.  On the other hand, when MODULE_SIG is not enabled, the boot continues in about one second.  
I have dracut 049-26.git20181204.fc30 .

The same bzImage and dracut images have been tested to work and boot OK in Fedora 32/syslinux in qemu/kvm.

How to debug this?  dracut or grub2 doesn't give any output.

Kernel boots ok with grub2 without module signing.

```
--- config-4.19.123.txt	2020-05-14 16:12:50.833060065 +0200
+++ config-4.19.123-nomod.txt	2020-05-14 16:13:10.260972342 +0200
@@ -19,7 +19,7 @@
 #
 CONFIG_INIT_ENV_ARG_LIMIT=32
 # CONFIG_COMPILE_TEST is not set
-CONFIG_LOCALVERSION=""
+CONFIG_LOCALVERSION="-nomod"
 # CONFIG_LOCALVERSION_AUTO is not set
 CONFIG_BUILD_SALT="xbjzotszfphjjsts"
 CONFIG_HAVE_KERNEL_GZIP=y
@@ -830,16 +830,8 @@
 CONFIG_MODULE_UNLOAD=y
 # CONFIG_MODULE_FORCE_UNLOAD is not set
 CONFIG_MODVERSIONS=y
-CONFIG_MODULE_SRCVERSION_ALL=y
-CONFIG_MODULE_SIG=y
-CONFIG_MODULE_SIG_FORCE=y
-CONFIG_MODULE_SIG_ALL=y
-# CONFIG_MODULE_SIG_SHA1 is not set
-# CONFIG_MODULE_SIG_SHA224 is not set
-CONFIG_MODULE_SIG_SHA256=y
-# CONFIG_MODULE_SIG_SHA384 is not set
-# CONFIG_MODULE_SIG_SHA512 is not set
-CONFIG_MODULE_SIG_HASH="sha256"
+# CONFIG_MODULE_SRCVERSION_ALL is not set
+# CONFIG_MODULE_SIG is not set
 # CONFIG_MODULE_COMPRESS is not set
 CONFIG_MODULES_TREE_LOOKUP=y
 CONFIG_BLOCK=y
@@ -7853,7 +7845,6 @@
 #
 # Crypto core or helper
 #
-# CONFIG_CRYPTO_FIPS is not set
 CONFIG_CRYPTO_ALGAPI=y
 CONFIG_CRYPTO_ALGAPI2=y
 CONFIG_CRYPTO_AEAD=y
@@ -8065,7 +8056,6 @@
 #
 # Certificates for signature checking
 #
-CONFIG_MODULE_SIG_KEY="certs/signing_key.pem"
 CONFIG_SYSTEM_TRUSTED_KEYRING=y
 CONFIG_SYSTEM_TRUSTED_KEYS=""
 CONFIG_SYSTEM_EXTRA_CERTIFICATE=y
```

**Comment by haraldh** [comment]
dracut is started by the kernel ... try removing `quiet` from the kernel command.. maybe add `loglevel=7` ... if you don't see any messages about the initrd/initramfs, dracut does not even start and you should close this bug. Thank you!

**Comment by Safari77** [comment]
I don't have ```quiet``` or ```rhgb``` options...
So what is happening, is this grub2 bug then?

**Comment by haraldh** [comment]
I don't know. Sorry. Did you add `loglevel=7` ? Did you install the `vmlinuz` correctly?

**Comment by Safari77** [comment]
No logs whatsoever and everything is correctly installed.
