### ISSUE TITLE
Adding a list of binaries and their hashes to the initrd.

### ISSUE THREAD

**Issue by lnykryn** [dracutdevs/dracut#820]
I would like to start a discussion if this makes sense or not or if my problem could be solved some other way.

From time to time we hit an issue where a user has an older version of a file inside the initrd (it can be binary, configuration file,...) and it leads to issues. Just recently we hit a bug in systemd, where older systemctl binary in initrd caused a problem during pivot (but of course that was a bug in systemd).

Some extremists on our team are suggesting that we should rebuild initrd every time we update any package that is used in initrd. But I think users would hate that.

So my idea was to build a list of files in initrd and their hashes and leave rest on other tools. For example, in rhel, we have a tool that runs periodically on customer systems and is giving some suggestions on what should a user do. So we could just ship a rule for this tool that would compare hashes of major daemons binaries and complain if they don't match.

**Comment by danimo** [comment]
Losely related: Do you rebuild the initrd's for all kernels if relevant userland packages change? There are people who don't want all to be rebuilt, as a means of recovery, but if the tools change this could be the very issue of an irrecoverable system.

**Comment by johannbg** [comment]
@lnykryn what's the current status of this?
