### ISSUE TITLE
rd.net.timeout.dhcp does not work with centos8?

### ISSUE THREAD

**Issue by maennlse** [dracutdevs/dracut#823]
Hi, 
dont know if this is the right place... 

when adding `rd.net.timeout.dhcp=5` i get the following errors during boot:
![image](https://user-images.githubusercontent.com/30595783/82741273-cec23500-9d50-11ea-9a82-7a0c122a793e.png)

comparing centos7 man page of `dhclient` with centos8 man page, there is indeed no parameter `-timeout` in centos8, it switched to `--timeout`?

besides that, man page of `dracut.cmdline` (on centos7 and 8) mentions to add `-timeout <arg>`

am i doing anything wrong?

**Comment by haraldh** [comment]
Should be fixed with: https://github.com/dracutdevs/dracut/pull/704

You have to open a bugzilla against RHEL-8

**Comment by haraldh** [comment]
@lnykryn

**Comment by lnykryn** [comment]
@maennlse  This should be fixed in 8.2. What is your version of Dracut?

**Comment by maennlse** [comment]
version of dracut is `dracut-049-27.git20190906.el8_1.1.x86_64` which is shipped with centos8 (`centos-release-8.1-1.1911.0.9.el8.x86_64`)

as centos 8.2 is not yet released, and @haraldh mentioned it should be fixed, no further action needed... 

thanks.
