### ISSUE TITLE
shellcheck error

### ISSUE THREAD

**Issue by LikrOvO** [dracutdevs/dracut#836]
I use the shellcheck tool to scan the source code and find the following errors. Is that the problem? If so, please fix it.
https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/dracut-lib.sh#L822 [SC2104]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90lvm/lvm_scan.sh#L33  [SC2070]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L13 [SC2104]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L14 [SC2104]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L17 [SC2104]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L20 [SC2104]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L25 [SC2104]
https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L28 [SC2104]

https://github.com/koalaman/shellcheck/wiki

**Comment by liquor1110** [comment]
Bash's modification of continue：https://github.com/bminor/bash/blob/master/CHANGES#L1493

**Comment by liquor1110** [comment]
New problems：
https://github.com/dracutdevs/dracut/blob/master/test/TEST-50-MULTINIC/test.sh#L193 [SC2157]
https://github.com/dracutdevs/dracut/blob/master/test/TEST-50-MULTINIC/test.sh#L200 [SC2157]
https://github.com/dracutdevs/dracut/blob/master/test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh#L219 [SC2157]
https://github.com/dracutdevs/dracut/blob/master/test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh#L226 [SC2157]
https://github.com/dracutdevs/dracut/blob/master/test/TEST-20-NFS/test.sh#L250 [SC2157]
