### ISSUE TITLE
Boot from virtio-fs filesystem

### ISSUE THREAD

**Issue by peterjohanson** [dracutdevs/dracut#846]
I'm not sure if it is a dracut or systemd issue ...
Virtio-fs is a new filesystem which allows to share a host directory with a virtual machine. It is also possible to boot from it. However, up to now I only could get it working without using an initrd/systemd.
When using dracut, which uses systemd, I get dropped to an emergency shell. When I press ctrl+D or enter my root password and exit the shell it continues to boot succesfully, so it works to some extend. Also the virtiofs module is loaded.
I use direct kernel boot (kernel 5.8-rc1) + a dracut initrd and "root=/dev/root rootfstype=virtiofs" on the kernel commandline.
The error I get is:
"Timed out waiting for device /dev/root"
"Dependency failed for initrd root device"
...
"dracut-initqueue - starting timeout scripts"|
"Starting Dracut Emergency Shell"

There is no /dev/root in the initrd since systemd (I guess) mounts devtmpfs in the /dev folder.
OS is Fedora 32.
For setting up virtiofs I used:
https://libvirt.org/kbase/virtiofs.html
You need a recent libvirt, qemu and kernel to make it work.

Documentation here: https://virtio-fs.gitlab.io/howto-boot.html
is a bit outdated (you can't use a tag to boot, but need to use /dev/root)

Any ideas how to get this working?
I know it is fairly new. Or is there some way to make dracut ignore the error and just continue to boot as an intermediate solution?

**Comment by danimo** [comment]
Did you try to include the `qemu` module when building the initrd?
