### ISSUE TITLE
regulator modules aren't included in host-only mode (armhfp/jetson-tk1)

### ISSUE THREAD

**Issue by kwizart** [dracutdevs/dracut#847]
Since Fedora kernel 5.6.x (or earlier), the as3722_regulator is built as a module.
This modules is needed to enable various low-level voltage function that are later used by modules involved in mounting rootfs.

As a workaround I need to use that:
cat >/etc/dracut.conf.d/jetson-tk1.conf<<EOF
add_drivers+=" as3722-regulator "
EOF

In the jetson-tk1/as3722 case, there is no dedicated node in device-tree to associate with the given regulator as the "ams,as3722" compatible is handled by the related drivers/mfd/as3722 (builtin) driver.

I would suggest the following fix within dracut:
1/ Have dracut to bundle all regulators (at least on armhfp/aarch64 where that situation might arrive more often as I expect).
That in both cases, as host-only or non-hostonly.
  or
2/  Improves dracut-install to also match regulators (with ams,as3722-regulator) when built as modules when a "ams,as3722" compatible is found in the current device-tree.
  or
3/ solve the solution within the kernel (How ?)

**Comment by nullr0ute** [comment]
We need to look at why the appropriate dep chain doesn't pick this up.

**Comment by kwizart** [comment]
> We need to look at why the appropriate dep chain doesn't pick this up.

So this fall under 3/ and the related question is how?

The problem is that as3722-regulator is loaded by the related mfd device. This part works fine, because I don't need an explicit modprobe once the regulator module is available. But the mfd driver is builtin, so I'm not aware of any mean for dracut to detect such dependency from a builtin driver.

The other way would be for a "module dependent on the regulator" to have an explicit dependency. For example tegra ahci could have a dependency to the as3722_regulator. 
But this would be incorrect because it 's not at all a dependency of the module per see. It's a dependency of the driver on the given board design. So this would be incorrect as a generic solution
(we would end in a situation where unrelated regulators would be added to any drivers)

So I don't see any reliable solution with 3/. That's why I'm suggesting 1/ or 2/.

Please note that despite I've worded this issue as jetson-tk1 hw specific, I foresee this kind of issue to be reproducible on others board design.

**Comment by kwizart** [comment]
I've tried to reproduce the issue without having "add_drivers+=" as3722_regulator " in /etc/dracut.conf.d and for some reason the regulator is bundled as appropriate in the initramfs. I haven't seen any change either between f31/f32 or any kernel update. But for some reason I'm not able to reproduce anymore using current components.

Let's close this.
