### ISSUE TITLE
Support globbing firmware files

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#849]
Some firmware files or firmware auxiliary files (such as the firmware for brcm80211) are non-exhaustive and can thus not be expressed in terms of a fully enumerated firmware list in the module. This was discussed on [LKML](https://lore.kernel.org/lkml/338e3cff-dfa0-c588-cf53-a160d75af2ee@redhat.com/).

I hence propose (and plan to implement) supporting globbing for `dracut_install`'s `install_firmware()` instead.

**Comment by haraldh** [comment]
sure, makes sense... go ahead :)
