### ISSUE TITLE
Improve boot time by sending DHCP only on min BDF device

### ISSUE THREAD

**Issue by anjalidk** [dracutdevs/dracut#850]
On some servers and bare metal instances, there are 2 ethernet devices, on
which DHCP is sent. However, if only first one succeeds, the second one keeps
re-trying DHCP, adding almost a minute to the boot time, before failing.
This patch sends DHCP only for the minimum BDF device.
Once successful, DHCP is not sent on any other DHCP device.
This is enabled only when we add ip=single-dhcp in kernel command parameters.
If the DHCP fails on minimum BDF device for some reason, we keep note of this
failed device in /run/initramfs/dhcpfaildev. This will ensure correctness for
the case when the first device passed to ifup.sh was the minimum BDF, but it
failed; then subsequent calls to ifup.sh for other devices will skip using
the minimum BDF device for sending DHCP, and choose another device.
This patch gives an improvement of about 1 minute to the system bootup time

**Comment by haraldh** [comment]
which patch?

**Comment by anjalidk** [comment]
Sorry for the delay, here is the patch:

On some servers and bare metal instances, when there are 2 ethernet devices, on
which DHCP is sent,but only first one succeeds (the one for the
minimum BDF device, then this adds almost a minute to boot times.
The second one keeps re-trying DHCP, hence adding the minute to the bootup
time, before failing. This patch sends DHCP only for the minimum BDF device.
Once successful, DHCP is not sent on any other DHCP device.
This is enabled only when we add ip=single-dhcp in kernel command parameters.
If the DHCP fails on minimum BDF device for some reason, we keep note of this
failed device in /run/initramfs/dhcpfaildev. This will ensure correctness for
the case when the first device passed to ifup.sh was the minimum BDF, but it
failed; then subsequent calls to ifup.sh for other devices will skip using the
minimum BDF device for sending DHCP, and choose another device.
This patch gives an improvement of about 1 minute to the system bootup time



Signed-off-by: Anjali Kulkarni<anjali.k.kulkarni@oracle.com>
---

diff -up ./modules.d/35network-legacy/ifup.sh.orig ./modules.d/35network-legacy/ifup.sh
--- ./modules.d/35network-legacy/ifup.sh.orig	2020-05-21 10:36:35.197226594 -0700
+++ ./modules.d/35network-legacy/ifup.sh	2020-06-04 16:00:59.170307526 -0700
@@ -23,6 +23,75 @@ if [ "$netif" = "lo" ] ; then
      exit 0
  fi
  
+min_device=""
+DHCP_FAIL="/run/initramfs/dhcpfaildev"
+UDEVLOG="/run/initramfs/udevlog"
+
+min_bdf_device() {
+    devs=$(ls /sys/class/net)
+
+    # Get the udevadm output in file $UDEVLOG
+    udevadm info -e > "$UDEVLOG"
+
+    for netdev in $devs; do
+        if [ "$netdev" = "lo" ]; then
+            continue
+        fi
+        if [ -e  "$DHCP_FAIL" ]; then
+            faildh=$(awk -v patrn="$netdev" '$0==patrn' "$DHCP_FAIL")
+            if [ "$faildh" = "$netdev" ]; then
+                warn "DHCP failed on $netdev earlier, skipping"
+                continue
+            fi
+        fi
+
+        # As an example, relevant output of udevadm when searching for a
+        # string ending with net/eno2 (eg. for device eno2), gives:
+        # P: /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/net/eno2
+        # E: DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/net/eno2
+        # Choosing 5th field (with FS=/) and then the first line gives us the
+        # domain:bus:slot.func (in $pcinfo below)
+
+        # Initialize awk variable pat, which holds the pattern $nif to match
+        nf="net/$netdev$"
+        pcinfo=$(awk -v pat="$nf" '$0 ~ pat{print $5}' FS=/ "$UDEVLOG" | awk 'NR==1')
+
+        # We flatten the BDF by removing the : and . characters from the BDF,
+        # convert BDF to decimal and then compare the result without needing to
+        # split the BDF into sub-components and comparing them
+        # eg. 16#00003b000 < 16#00003b001
+
+        hex_pcinfo="${pcinfo//:}"
+        hex_pcinfo="${hex_pcinfo//.}"
+        dpcinfo=$(( 16#$hex_pcinfo ))
+
+        if [ -z "$min_dpcinfo" ] || [ "$dpcinfo" -lt "$min_dpcinfo" ]; then
+            min_dpcinfo=$dpcinfo
+            min_device=$netdev
+        fi
+    done
+    echo "Device for DHCP is $min_device"
+    rm -f "$UDEVLOG"
+}
+
+do_single_dhcp() {
+    min_device=""
+    min_bdf_device
+    if [ "$min_device" = "$netif" ]; then
+        do_dhcp -4
+        dhret=$?
+        if [ $dhret -eq 0 ]; then
+            return 0
+        else
+            warn "DHCP failed for min BDF device, removing it for DHCP"
+            echo "$min_device" >> "$DHCP_FAIL"
+            return 1
+        fi
+    else
+        return 1
+    fi
+}
+
  # Run dhclient
  do_dhcp() {
      # dhclient-script will mark the netif up and generate the online
@@ -432,6 +501,8 @@ for p in $(getargs ip=); do
          case $autoopt in
              dhcp|on|any)
                  do_dhcp -4 ;;
+            single-dhcp)
+                do_single_dhcp ;;
              dhcp6)
                  load_ipv6
                  do_dhcp -6 ;;
diff -up ./modules.d/35network-legacy/parse-ip-opts.sh.orig ./modules.d/35network-legacy/parse-ip-opts.sh
--- ./modules.d/35network-legacy/parse-ip-opts.sh.orig	2020-05-21 10:36:46.163604983 -0700
+++ ./modules.d/35network-legacy/parse-ip-opts.sh	2020-05-21 10:46:12.504400915 -0700
@@ -1,7 +1,7 @@
  #!/bin/sh
  #
  # Format:
-#       ip=[dhcp|on|any]
+#       ip=[dhcp|on|any|single-dhcp]
  #
  #       ip=<interface>:[dhcp|on|any][:[<mtu>][:<macaddr>]]
  #
@@ -77,7 +77,7 @@ for p in $(getargs ip=); do
                  ;;
              auto6);;
              either6);;
-            dhcp|dhcp6|on|any) \
+            dhcp|dhcp6|on|any|single-dhcp) \
                  [ -n "$NEEDBOOTDEV" ] && [ -z "$dev" ] && \
                      die "Sorry, 'ip=$p' does not make sense for multiple interface configurations"

                  [ -n "$ip" ] && \

**Comment by haraldh** [comment]
Please file this as a pull request.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by anjalidk** [comment]
Thanks, submitted:

https://github.com/dracutdevs/dracut/pull/853

**Comment by anjalidk** [comment]
2 test cases failed - but I do not understand why or how to debug - can 
someone please help?

Anjali
