### ISSUE TITLE
Specifying IPv6 address in netroot=iscsi:... broken

### ISSUE THREAD

**Issue by LubosD** [dracutdevs/dracut#856]
It seems the code that parses the `iscsi:` string removes `[` and `]` from any IPv6 address passed in this parameter. That causes problems down the road once the port number is appended to the IP address and passed to `iscsiadm`.

Example:
Using this kernel parameter: `netroot=iscsi:[fd00:1::2]::::iqn.2003-01.org.linux-iscsi.gentoo:ro`

Results in this error (see how the default iSCSI port of  3260 becomes part of the IP address):
![iscsiadm](https://user-images.githubusercontent.com/878801/87320153-da4d0380-c52a-11ea-8ebc-61b540bc7b7f.png)

**Comment by danimo** [comment]
@tblume can you take a look?

**Comment by tblume** [comment]
That should be fixed with:

https://github.com/dracutdevs/dracut/commit/3b869230a08088a4f51d5bde8d5cfc8497779815

Lubos, could you retry with the latest code?
