### ISSUE TITLE
dracut: i18n_vars not set!  Please set up i18n_vars in  configuration file.

### ISSUE THREAD

**Issue by barmadrid** [dracutdevs/dracut#868]
I'm setting console font in kernel parameters via `/etc/dracut.conf.d/myconf.conf` using:
`kernel_cmdline="rd.vconsole.keymap=us rd.vconsole.font=ter-v22b"`

The efi image is generated with: `dracut --force --uefi /boot/linux.efi`

During build I see the following messages:
```
dracut: i18n_vars not set!  Please set up i18n_vars in  configuration file.
dracut: No KEYMAP configured.
```
Although the font get applied on boot regardless of messages above, the image does not contain `/etc/vconsole.conf` as described in [DRACUT.CMDLINE(7)](https://man7.org/linux/man-pages/man7/dracut.cmdline.7.html):
> rd.vconsole.font=<font base file name>
>            console font; taken from consolefonts directory; will be written
>            as FONT to /etc/vconsole.conf in the initramfs.

Is this normal or am I missing something?

**Comment by danimo** [comment]
Do ```setfont loadkeys kbd_mode``` exist? is the i18n module part of your initrd? (check with lsinitrd)

**Comment by barmadrid** [comment]
> Do the binaries `setfont, loadkeys and kbd_mode` exist on your machine? is the i18n module part of your initrd? (check with lsinitrd)

@danimo Yes all three exists on my machine and also in the initrd image under `/usr/bin`. Yes, i18n module is included too.

**Comment by johannbg** [comment]
@barmadrid what distro is this, what release of dracut and could you double check and see if the keymap and font actually exist on the initrd ( highly unlikely that the us keymap is missing but ter-v22b.psf.gz might ).

**Comment by barmadrid** [comment]
@johannbg The distro is Arch Linux and dracut version is `050`
Yes, keymap is present and also the font:

```
$ lsinitrd /boot/linux.efi | less
:
-rw-r--r--   1 root     root        34557 Jun 29 12:28 usr/share/kbd/consolefonts/ter-v22b.psf
:
```

**Comment by barmadrid** [comment]
I can confirm that I'm still experiencing this in 051.

**Comment by barmadrid** [comment]
I can confirm that I'm still experiencing this in 051.

**Comment by haraldh** [comment]
Fedora ships with `/usr/lib/dracut/dracut.conf.d/01-dist.conf`:
```
# dracut config file customized for RedHat/Fedora.

# i18n
i18n_vars="/etc/sysconfig/keyboard:KEYTABLE-KEYMAP /etc/sysconfig/i18n:SYSFONT-FONT,FONTACM-FONT_MAP,FONT_UNIMAP"
i18n_default_font="eurlatgr"
i18n_install_all="yes"


stdloglvl=3
sysloglvl=5
install_optional_items+=" vi /etc/virc ps grep cat rm "
prefix="/"
systemdutildir=/usr/lib/systemd
systemdsystemunitdir=/usr/lib/systemd/system
systemdsystemconfdir=/etc/systemd/system
udevdir=/usr/lib/udev
hostonly="yes"
hostonly_cmdline="no"
early_microcode="yes"
reproducible="yes"
```

Your distro seems to be missing such file

**Comment by barmadrid** [comment]
Still, that does not fix that. Even if I add that i18n_vars to my config file pointed to my consolefonts and keymaps directory.

(I can fix my issue if I manually create `/etc/vconsole.conf` then generate dracut image.

But why is dracut not creating it, if I don't have it and I set it via  `kernel_cmdline="rd.vconsole.keymap=us rd.vconsole.font=ter-v22b"` as it says in [DRACUT.CMDLINE(7)](https://man7.org/linux/man-pages/man7/dracut.cmdline.7.html)?

**Comment by barmadrid** [comment]
The paths to consolefonts and keymaps in Arch are:

`/usr/share/kbd/consolefonts`
`/usr/share/kbd/keymaps`

I included that in `i18n_vars`, trying different combination as mentioned in `dracut/modules.d/10i18n/README` with no success!

Not sure at this point!

**Comment by deimosian** [comment]
I do not think this is a bug. The issue can be resolved on Arch Linux by adding `i18n_vars=` to a file in `/etc/dracut.conf.d/`.

**Comment by LaszloGombos** [comment]
Closing..

@barmadrid Please let us know if you think dracut does not work as it intended/documented.
