### ISSUE TITLE
The future of the network stack in Dracut.

### ISSUE THREAD

**Issue by johannbg** [dracutdevs/dracut#874]
Distributions and end users have started to move more towards using what the system management framework offers ( networkd,resolved etc ) and iwd as their primary network stack on the core/baseOS level while things like NetworkManager/Connman are evolving at best just being front ends on top of that. 

Where is Dracut at and heading in general and in that regard and what work remains to be done in which all the legacy bit's are either removed or made entirely modular encase I wanted to take a stab at doing that like obsoleting NM and introduce iwd ( if it should be introduced? and then as a module? ) remove any usage of /etc/sysconfig, ifcfg and other archaic stuff which is probably is just being used by RHEL these days and perhaps Suse enterprise or something ( which they could just maintain entirely downstream for their customer base for as long they are forced to support it, arguably the work I'm signing myself up to do ( with the exception of iwd ) should have been done and included in RHEL 8 and Suse's equivalent ) and properly integrated the service that come with systemd into Dracut.

**Comment by danimo** [comment]
See also #880 which would potentially rid opensuse of the need for legacy scripts (but, possibly, not the config files, as they are still read by wicked as a fallback).

**Comment by johannbg** [comment]
I'll have a look.

**Comment by johannbg** [comment]
.

**Comment by johannbg** [comment]
.
