### ISSUE TITLE
Gardening dracut

### ISSUE THREAD

**Issue by johannbg** [dracutdevs/dracut#878]
@haraldh I cant see the wood for the leaves in your git tree which I find annoying hence I would like do to some gardening work ( which involves heighten permission on the repository unless you want me to ping you with all that stuff ) by picking low hanging fruits like triaging and closing old issues ( which date back all the way to 2013! ) properly label all issue and add missing label ( vendor should include atleast all of the primary distributions it's missing Arch Debian Gentoo ) etc. 

I wont be touching pull requests those are still something you should go through and any work I will be doing in the root itself will be submitted with pull requests. ( like cleaning up the TODO does not reflect reality, add support for mkosi and bunch of minor stuff like that ) and from the looks of it you are getting the short end of the stick in the enarx project if you end up having to maintain it in Fedora ( with the additional load that follows ) which means you wont have any time focusing on low hanging fruits in dracut and probably elsewhere as well.

Once I have completed that work ( going through all those issues ) you can remove those permissions again.

**Comment by haraldh** [comment]
I am more than happy to let you grow some flowers :-) Thanks for stepping up! Much appreciated!

**Comment by danimo** [comment]
@johannbg I will be glad to assist. I am currently reviewing PRs and also trying to tag stuff that needs to be fixed for a future 051 release.
