### ISSUE TITLE
Decide on nvme|f module split

### ISSUE THREAD

**Issue by danimo** [dracutdevs/dracut#881]
There are numerous ways to use nvme via fabric. FC, RDMA, TCP. Maybe that needs to be split into more modules.

**Comment by danimo** [comment]
Note to self: Once done, we need to check wether adding the module to the denylist for hibernation (480aa9695f8c2e2b30c8f41ae8483140020d23db) is necessary.

**Comment by ematsumiya** [comment]
IMHO at least splitting FC from RDMA and TCP makes sense, since the latter are IP based and a generic approach could be used.

This would reduce complexity and unnecessary dependencies for the FC case.
