### ISSUE TITLE
mknod errors when dracut is executed inside a container

### ISSUE THREAD

**Issue by DaanDeMeyer** [dracutdevs/dracut#890]
```
mknod: /var/tmp/dracut.C0dc2h/initramfs/dev/kmsg: Operation not permitted
mknod: /var/tmp/dracut.C0dc2h/initramfs/dev/console: Operation not permitted
```

I wasn't immediately able to find a way that allows to check if we have CAP_MKNOD. Is it OK if I make a PR that silences failures for these two calls to mknod?

**Comment by johannbg** [comment]
@DaanDeMeyer probably an actual fix is needed not something that is papered over or "silenced". @haraldh what's the reason for dracut creating those device nodes? ( or to phrase this differently cant dracut not just rely on the kernel devtmpfs creating those device nodes? )

**Comment by DaanDeMeyer** [comment]
This is still a problem.

**Comment by DaanDeMeyer** [comment]
This is still a problem.

**Comment by DaanDeMeyer** [comment]
@johannbg This is getting a bit ridiculous. I don't mind if it takes a while for this to be fixed but just closing the issue because no one else is commenting on it seems a bit ridiculous.

**Comment by johannbg** [comment]
@DaanDeMeyer  It's more like no one is working on it, and as such it's gone stale ( If anyone is working on it he should assign it to her or himself ). Anyway I filed a PR that exempts all issues with the label bug and put a label on this issue, which should prevent this issue from being processed by the stalebot.

**Comment by haraldh** [comment]
> Is it OK if I make a PR that silences failures for these two calls to mknod?

yes, please
