### ISSUE TITLE
Description/documentation of module functions

### ISSUE THREAD

**Issue by dbasinge** [dracutdevs/dracut#901]
The modules need some sort of documentation of the function they provide added to the man page, or less a readme.

**Comment by danimo** [comment]
I would propose something more dynamic, which accounts for the fact that other sources, e.g. other packages can contribute their own modules. I propose the following:

extend the module interface to expect

* `synopsis()`, the content of which is added to the output of `list-modules`.
* `usage()`, the contents of which will be displayed when running `dracut --module-usage <module>`

` --module-usage could show the contents of `module/README` (which often exists) as a fallback.

**Comment by danimo** [comment]
I'd take this one if @johannbg @haraldh agree.

**Comment by johannbg** [comment]
I say go for it. It wont hurt having this as a fallback.

**Comment by danimo** [comment]
Haven't had time for that and won't in the forseeable future. Maybe someone else does.

**Comment by johannbg** [comment]
This will be handled in #1072 hence closing...
