### ISSUE TITLE
Customize output filename

### ISSUE THREAD

**Issue by leo-lb** [dracutdevs/dracut#921]
Hello!

I am generating an UEFI application using dracut and for now that one is automatically installed on the system, however that is not what I want, I would just want the UEFI application to be written somewhere so I can do what I have to do with it later.

The manual says:

> The default output filename is <EFI>/EFI/Linux/linux-$kernel$-<MACHINE_ID>-<BUILD_ID>.efi. <EFI> might be /efi, /boot or /boot/efi depending on where the ESP partition is mounted. The <BUILD_ID> is taken from BUILD_ID in /usr/lib/os-release or if it exists /etc/os-release and is left out, if BUILD_ID is non-existant or empty.

I would like not to use the default, it says it's default but that means it should be possible to not use the default?

How could I modify the output filename?

Thank you

**Comment by leo-lb** [comment]
Turns out the undocumented `outfile` in a configuration file works, however there's no way to do it using command line only.

**Comment by barmadrid** [comment]
I generate my .efi using: `dracut --force --uefi /boot/linux.efi` (overrides the default EFI path) and it always works.

What does `--uefi-output` do differently? (Sorry, not so clear to me).

**Comment by leo-lb** [comment]
@barmadrid If that's the case then it would be useful documenting it more obviously and revert my now merged commits.

**Comment by barmadrid** [comment]
@leo-lb Thanks for reply..... I agree it should have been documented.
Maybe @danimo can verify and revert the merged commit if they wish.

**Comment by danimo** [comment]
Confirmed, see #980
