### ISSUE TITLE
Send DHCP requests in parallel on all interfaces to improve boot time

### ISSUE THREAD

**Issue by anjalidk** [dracutdevs/dracut#962]
We can drastically improve boot times on some machines, or BM or VM
shapes, which have more than 1 interfaces, if we send DHCP requests
in parallel on all interfaces.
Add ip=single-dhcp as a kernel boot parameter, to send DHCP requests in
parallel on all interfaces. Thus, DHCP on each interface is overlapped with
other interfaces, reducing boot times for multiple interface machines.
This can help reduce the boot time by 1 minute per interface.
In addition, we may also save another 40 secs delay per interface, if
the link on which we try to send DHCP is in DOWN state. This can be reduced
by giving the following kernel command line parameter while booting -
rd.net.timeout.carrier=<timeout>
The fix is submitted via pull request:
https://github.com/dracutdevs/dracut/pull/961

**Comment by johannbg** [comment]
Afaikt this was resolved when  #1048 got merged hence closing.
