### ISSUE TITLE
Emergency mode

### ISSUE THREAD

**Issue by LikrOvO** [dracutdevs/dracut#973]
I have a little doubt about the change（#499 ）
Why use sulogin -e instead of sh -i -l ？Is it for safety reasons？
https://github.com/dracutdevs/dracut/blob/4339d47cf810d8a79f20cf2b86d15af7ec859052/modules.d/98dracut-systemd/dracut-emergency.sh#L37
If I forget the root password, I can also use rd.break into emergency mode to change the password

**Comment by danimo** [comment]
It's mostly to spawn a shell on every available on every available console (i.e. when you specify console= on the kernel command line multiple times). Asking for the password is a nice side effect...

>  If I forget the root password, I can also use rd.break into emergency mode to change the password

If you forgot your root password, you can simply init=/bin/bash, unless editing your bootloader options is also password protected. But what do you mean? rd.break anywhere will ask for a password (assuming the initrd is host specific)...

**Comment by LikrOvO** [comment]
Thank you for your reply！
