### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DaanDeMeyer** [dracutdevs/dracut#983]
Currently, anyone on systemd v246 or higher gets a ton of deprecation warnings on boot when using dracut. This was fixed in e1130a83405648777210fdc99f7eee087eebaadc but this commit is not yet in a public release. Would it be possible to release a new version to get rid of these deprecation warnings?

**Comment by johannbg** [comment]
@haraldh @danimo is something in the pipeline preventing a new release?

**Comment by haraldh** [comment]
Let me do one on Monday

**Comment by danimo** [comment]
@haraldh fine by me, but I would like some minor things adjusted before we tag a release. Let's meet on gitter.

**Comment by danimo** [comment]
done! :)
